Repository OCA/manufacture, pull requests merged in 2019-04, with the labels that each got.

#346 [FIX] quality_control: Constraint methods should raise ValidationError
  quality_control/models/qc_test_category.py
Labels: approved

#352 [11.0][IMP] mrp_production_request: Add product and BoM search filters
  mrp_production_request/__manifest__.py
  mrp_production_request/views/mrp_production_request_view.xml
Labels: approved, ready to merge

#348 [12.0][FIX] repair_refurbish, product with tracking show error when end repair order
  repair_refurbish/__manifest__.py
  repair_refurbish/models/repair.py
  repair_refurbish/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge

#351 [MIG] mrp_bom_component_menu: Migration to 12.0
  mrp_bom_component_menu/README.rst
  mrp_bom_component_menu/__init__.py
  mrp_bom_component_menu/__manifest__.py
  mrp_bom_component_menu/i18n/de.po
  mrp_bom_component_menu/i18n/mrp_bom_component_menu.pot
  mrp_bom_component_menu/static/description/icon.png
  mrp_bom_component_menu/views/mrp_bom_component_view.xml
Labels: approved, needs review, ready to merge

#356 [10.0][mrp_production_request] Fix return of _generate_finished_moves method
  mrp_production_request/models/mrp_production.py
Labels: approved

#343 [MIG] mrp_bom_location: Migration to 12.0
  mrp_bom_location/README.rst
  mrp_bom_location/__init__.py
  mrp_bom_location/__manifest__.py
  mrp_bom_location/i18n/de.po
  mrp_bom_location/i18n/mrp_bom_location.pot
  mrp_bom_location/models/__init__.py
  mrp_bom_location/models/mrp_bom.py
  mrp_bom_location/readme/CONTRIBUTORS.rst
  mrp_bom_location/readme/DESCRIPTION.rst
  mrp_bom_location/readme/USAGE.rst
  mrp_bom_location/report/__init__.py
  mrp_bom_location/report/bom_structure.py
  mrp_bom_location/static/description/icon.png
  mrp_bom_location/static/description/index.html
  mrp_bom_location/views/mrp_view.xml
  mrp_bom_location/views/report_mrpbomstructure.xml
Labels: approved

#355 [12.0][FIX] repair_refurbish - pyflakes issue with inverse method naming
  repair_refurbish/models/product_template.py
Labels: approved

#353 [MIG] mrp_production_grouped_by_product: Migration to 12.0
  mrp_production_grouped_by_product/README.rst
  mrp_production_grouped_by_product/__init__.py
  mrp_production_grouped_by_product/__manifest__.py
  mrp_production_grouped_by_product/i18n/de.po
  mrp_production_grouped_by_product/i18n/es.po
  mrp_production_grouped_by_product/i18n/mrp_production_grouped_by_product.pot
  mrp_production_grouped_by_product/models/__init__.py
  mrp_production_grouped_by_product/models/mrp_production.py
  mrp_production_grouped_by_product/models/stock_picking_type.py
  mrp_production_grouped_by_product/models/stock_rule.py
  mrp_production_grouped_by_product/readme/CONFIGURE.rst
  mrp_production_grouped_by_product/readme/CONTRIBUTORS.rst
  mrp_production_grouped_by_product/readme/DESCRIPTION.rst
  mrp_production_grouped_by_product/readme/ROADMAP.rst
  mrp_production_grouped_by_product/static/description/icon.png
  mrp_production_grouped_by_product/static/description/index.html
  mrp_production_grouped_by_product/tests/__init__.py
  mrp_production_grouped_by_product/tests/test_mrp_production_grouped_by_product.py
  mrp_production_grouped_by_product/views/stock_picking_type_views.xml
Labels: approved, ready to merge
