Repository OCA/manufacture, pull requests merged in 2019-09, with the labels that each got.

#393 [IMP] quality_control_stock: use read_group
  quality_control_stock/README.rst
  quality_control_stock/models/stock_picking.py
  quality_control_stock/models/stock_production_lot.py
  quality_control_stock/readme/CONTRIBUTORS.rst
Labels: approved

#401 [10.0][FIX] update travis definition
  .travis.yml
Labels: approved

#399 [12.0][ADD] product_mrp_info
  product_mrp_info/README.rst
  product_mrp_info/__init__.py
  product_mrp_info/__manifest__.py
  product_mrp_info/models/__init__.py
  product_mrp_info/models/product.py
  product_mrp_info/readme/CONTRIBUTORS.rst
  product_mrp_info/readme/DESCRIPTION.rst
  product_mrp_info/readme/USAGE.rst
  product_mrp_info/static/description/icon.png
  product_mrp_info/static/description/index.html
  product_mrp_info/tests/__init__.py
  product_mrp_info/tests/test_product_mrp_info.py
  product_mrp_info/views/product_views.xml
Labels: approved, ready to merge

#400 [11.0][IMP] mrp_multi_level: add support for multi-company
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_move.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/security/mrp_multi_level_security.xml
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
Labels: approved, ready to merge

#403 [12.0][FIX]repair_refurbish. Set correct destination location in stock move lines
  repair_refurbish/models/stock_move.py
  repair_refurbish/tests/test_repair_refurbish.py
Labels: approved, ready to merge

#390 [12.0][ADD] mrp_multi_level_estimate
  mrp_multi_level_estimate/README.rst
  mrp_multi_level_estimate/__init__.py
  mrp_multi_level_estimate/__manifest__.py
  mrp_multi_level_estimate/models/__init__.py
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/readme/CONFIGURE.rst
  mrp_multi_level_estimate/readme/CONTRIBUTORS.rst
  mrp_multi_level_estimate/readme/DESCRIPTION.rst
  mrp_multi_level_estimate/static/description/icon.png
  mrp_multi_level_estimate/static/description/index.html
  mrp_multi_level_estimate/tests/__init__.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/views/product_mrp_area_views.xml
  mrp_multi_level_estimate/wizards/__init__.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: approved, needs review, ready to merge
