Repository OCA/manufacture, pull requests merged in 2019-02, with the labels that each got.

#336 [10.0][ADD] mrp_no_partial
  mrp_no_partial/README.rst
  mrp_no_partial/__init__.py
  mrp_no_partial/__manifest__.py
  mrp_no_partial/models/__init__.py
  mrp_no_partial/models/mrp_production.py
  mrp_no_partial/models/stock_picking_type.py
  mrp_no_partial/readme/CONTRIBUTORS.rst
  mrp_no_partial/readme/DESCRIPTION.rst
  mrp_no_partial/readme/HISTORY.rst
  mrp_no_partial/readme/USAGE.rst
  mrp_no_partial/static/description/icon.png
  mrp_no_partial/static/description/index.html
  mrp_no_partial/tests/__init__.py
  mrp_no_partial/tests/test_no_partial.py
  mrp_no_partial/views/stock_picking_type.xml
  setup/mrp_no_partial/odoo/__init__.py
  setup/mrp_no_partial/odoo/addons/__init__.py
  setup/mrp_no_partial/odoo/addons/mrp_no_partial
  setup/mrp_no_partial/setup.py
Labels: approved

#339 [11.0][ADD] account_move_line_manufacture_info
  account_move_line_manufacture_info/README.rst
  account_move_line_manufacture_info/__init__.py
  account_move_line_manufacture_info/__manifest__.py
  account_move_line_manufacture_info/models/__init__.py
  account_move_line_manufacture_info/models/account_move_line.py
  account_move_line_manufacture_info/models/stock_move.py
  account_move_line_manufacture_info/readme/CONTRIBUTORS.rst
  account_move_line_manufacture_info/readme/DESCRIPTION.rst
  account_move_line_manufacture_info/readme/USAGE.rst
  account_move_line_manufacture_info/security/ir.model.access.csv
  account_move_line_manufacture_info/static/description/icon.png
  account_move_line_manufacture_info/static/description/index.html
  account_move_line_manufacture_info/tests/__init__.py
  account_move_line_manufacture_info/tests/test_account_move_line_manufacture_info.py
  account_move_line_manufacture_info/views/account_move_line_view.xml
  account_move_line_manufacture_info/views/mrp_production_views.xml
  account_move_line_manufacture_info/views/mrp_unbuild_views.xml
Labels: approved, ready to merge

#340 [11.0][ADD] mrp_production_auto_post_inventory
  mrp_production_auto_post_inventory/README.rst
  mrp_production_auto_post_inventory/__init__.py
  mrp_production_auto_post_inventory/__manifest__.py
  mrp_production_auto_post_inventory/models/__init__.py
  mrp_production_auto_post_inventory/models/company.py
  mrp_production_auto_post_inventory/models/res_config_settings.py
  mrp_production_auto_post_inventory/readme/CONTRIBUTORS.rst
  mrp_production_auto_post_inventory/readme/DESCRIPTION.rst
  mrp_production_auto_post_inventory/readme/USAGE.rst
  mrp_production_auto_post_inventory/static/description/AutoPostInventory_Option.png
  mrp_production_auto_post_inventory/static/description/index.html
  mrp_production_auto_post_inventory/tests/__init__.py
  mrp_production_auto_post_inventory/tests/test_mrp_production.py
  mrp_production_auto_post_inventory/views/res_config_settings.xml
  mrp_production_auto_post_inventory/wizard/__init__.py
  mrp_production_auto_post_inventory/wizard/mrp_product_produce.py
Labels: approved

#328 [11.0][ADD] mrp_stock_orderpoint_manual_procurement
  mrp_stock_orderpoint_manual_procurement/README.rst
  mrp_stock_orderpoint_manual_procurement/__init__.py
  mrp_stock_orderpoint_manual_procurement/__manifest__.py
  mrp_stock_orderpoint_manual_procurement/models/__init__.py
  mrp_stock_orderpoint_manual_procurement/models/mrp_production.py
  mrp_stock_orderpoint_manual_procurement/models/procurement.py
  mrp_stock_orderpoint_manual_procurement/readme/CONTRIBUTORS.rst
  mrp_stock_orderpoint_manual_procurement/readme/DESCRIPTION.rst
  mrp_stock_orderpoint_manual_procurement/readme/USAGE.rst
  mrp_stock_orderpoint_manual_procurement/static/description/icon.png
  mrp_stock_orderpoint_manual_procurement/static/description/index.html
  mrp_stock_orderpoint_manual_procurement/tests/__init__.py
  mrp_stock_orderpoint_manual_procurement/tests/test_mrp_manual_procurement.py
  mrp_stock_orderpoint_manual_procurement/views/mrp_production_view.xml
  oca_dependencies.txt
Labels: approved, needs review

#341 [11.0][IMP] account_move_line_manufacture_info
  account_move_line_manufacture_info/views/mrp_production_views.xml
  account_move_line_manufacture_info/views/mrp_unbuild_views.xml
Labels: approved
