Repository OCA/manufacture, pull requests merged in 2020-03, with the labels that each got.

#468 [13.0][IMP] mrp_multi_level: Minor changes
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/readme/CONTRIBUTORS.rst
  mrp_multi_level/readme/HISTORY.rst
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, ready to merge

#452 [12.0][MIG] product_quick_bom: Migration to 12.0
  product_quick_bom/README.rst
  product_quick_bom/__init__.py
  product_quick_bom/__manifest__.py
  product_quick_bom/i18n/ca.po
  product_quick_bom/i18n/de.po
  product_quick_bom/i18n/el_GR.po
  product_quick_bom/i18n/es.po
  product_quick_bom/i18n/es_ES.po
  product_quick_bom/i18n/es_MX.po
  product_quick_bom/i18n/eu.po
  product_quick_bom/i18n/fi.po
  product_quick_bom/i18n/fr.po
  product_quick_bom/i18n/fr_CH.po
  product_quick_bom/i18n/fr_FR.po
  product_quick_bom/i18n/gl.po
  product_quick_bom/i18n/hr.po
  product_quick_bom/i18n/hr_HR.po
  product_quick_bom/i18n/it.po
  product_quick_bom/i18n/lt.po
  product_quick_bom/i18n/nl.po
  product_quick_bom/i18n/nl_NL.po
  product_quick_bom/i18n/product_quick_bom.pot
  product_quick_bom/i18n/pt.po
  product_quick_bom/i18n/pt_BR.po
  product_quick_bom/i18n/ro.po
  product_quick_bom/i18n/ru.po
  product_quick_bom/i18n/sk.po
  product_quick_bom/i18n/sl.po
  product_quick_bom/i18n/tr.po
  product_quick_bom/i18n/tr_TR.po
  product_quick_bom/i18n/vi_VN.po
  product_quick_bom/i18n/zh_CN.po
  product_quick_bom/models/__init__.py
  product_quick_bom/models/product.py
  product_quick_bom/readme/CONTRIBUTORS.rst
  product_quick_bom/readme/DESCRIPTION.rst
  product_quick_bom/readme/USAGE.rst
  product_quick_bom/static/description/icon.png
  product_quick_bom/static/description/icon.svg
  product_quick_bom/static/description/index.html
  product_quick_bom/tests/__init__.py
  product_quick_bom/tests/test_quick_bom.py
  product_quick_bom/views/product_view.xml
Labels: approved, ready to merge

#446 [12.0][mrp_multi_level] define a name_search strategy for the product_mrp_area
  mrp_multi_level/models/product_mrp_area.py
Labels: approved

#472 [13.0][FWPORT] mrp_multi_level: implement name_search on product parameters
  mrp_multi_level/models/product_mrp_area.py
Labels: approved

#474 [13.0][MIG] mrp_bom_line_sequence
  mrp_bom_line_sequence/README.rst
  mrp_bom_line_sequence/__init__.py
  mrp_bom_line_sequence/__manifest__.py
  mrp_bom_line_sequence/i18n/hr.po
  mrp_bom_line_sequence/i18n/mrp_bom_line_sequence.pot
  mrp_bom_line_sequence/models/__init__.py
  mrp_bom_line_sequence/models/mrp.py
  mrp_bom_line_sequence/readme/CONTRIBUTORS.rst
  mrp_bom_line_sequence/readme/DESCRIPTION.rst
  mrp_bom_line_sequence/readme/USAGE.rst
  mrp_bom_line_sequence/static/description/icon.png
  mrp_bom_line_sequence/static/description/index.html
  mrp_bom_line_sequence/views/stock_view.xml
Labels: approved

#473 [12.0][FWPORT] mrp_multi_level: origin for "mv" was never being set.
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved

#480 [13.0][FIX] mrp_multi_level: origin for "mv" was never being set.
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved

#443 [MIG] [11.0] Migration of 'quality_control_mrp'
  quality_control_mrp/README.rst
  quality_control_mrp/__init__.py
  quality_control_mrp/__manifest__.py
  quality_control_mrp/data/quality_control_mrp_data.xml
  quality_control_mrp/i18n/ca.po
  quality_control_mrp/i18n/de.po
  quality_control_mrp/i18n/el_GR.po
  quality_control_mrp/i18n/es.po
  quality_control_mrp/i18n/es_ES.po
  quality_control_mrp/i18n/es_MX.po
  quality_control_mrp/i18n/eu.po
  quality_control_mrp/i18n/fi.po
  quality_control_mrp/i18n/fr.po
  quality_control_mrp/i18n/fr_CH.po
  quality_control_mrp/i18n/fr_FR.po
  quality_control_mrp/i18n/gl.po
  quality_control_mrp/i18n/hr.po
  quality_control_mrp/i18n/hr_HR.po
  quality_control_mrp/i18n/it.po
  quality_control_mrp/i18n/nl.po
  quality_control_mrp/i18n/nl_NL.po
  quality_control_mrp/i18n/pt.po
  quality_control_mrp/i18n/pt_BR.po
  quality_control_mrp/i18n/quality_control_mrp.pot
  quality_control_mrp/i18n/ro.po
  quality_control_mrp/i18n/ru.po
  quality_control_mrp/i18n/sk.po
  quality_control_mrp/i18n/sl.po
  quality_control_mrp/i18n/tr.po
  quality_control_mrp/i18n/tr_TR.po
  quality_control_mrp/i18n/vi_VN.po
  quality_control_mrp/i18n/zh_CN.po
  quality_control_mrp/migrations/10.0.1.0.0/pre-migration.py
  quality_control_mrp/models/__init__.py
  quality_control_mrp/models/mrp_production.py
  quality_control_mrp/models/qc_inspection.py
  quality_control_mrp/readme/CONTRIBUTORS.rst
  quality_control_mrp/readme/DESCRIPTION.rst
  quality_control_mrp/static/description/icon.png
  quality_control_mrp/static/description/index.html
  quality_control_mrp/tests/__init__.py
  quality_control_mrp/tests/test_quality_control_mrp.py
  quality_control_mrp/views/mrp_production_view.xml
  quality_control_mrp/views/qc_inspection_view.xml
Labels: approved, needs review, ready to merge

#478 [13.0][MIG] mrp_workorder_sequence
  mrp_workorder_sequence/README.rst
  mrp_workorder_sequence/__init__.py
  mrp_workorder_sequence/__manifest__.py
  mrp_workorder_sequence/i18n/mrp_workorder_sequence.pot
  mrp_workorder_sequence/models/__init__.py
  mrp_workorder_sequence/models/mrp_production.py
  mrp_workorder_sequence/models/mrp_workorder.py
  mrp_workorder_sequence/readme/CONTRIBUTORS.rst
  mrp_workorder_sequence/readme/DESCRIPTION.rst
  mrp_workorder_sequence/readme/USAGE.rst
  mrp_workorder_sequence/static/description/icon.png
  mrp_workorder_sequence/static/description/index.html
  mrp_workorder_sequence/views/mrp_workorder_view.xml
  setup/mrp_workorder_sequence/odoo/addons/mrp_workorder_sequence
  setup/mrp_workorder_sequence/setup.py
Labels: approved, ready to merge

#485 [12.0][FIX] round icon
  quality_control/static/description/icon.png
  quality_control/static/description/icon.svg
Labels: approved

#482 [13.0] repair_refurbish
  repair_refurbish/README.rst
  repair_refurbish/__init__.py
  repair_refurbish/__manifest__.py
  repair_refurbish/data/stock_data.xml
  repair_refurbish/i18n/de.po
  repair_refurbish/i18n/mrp_repair_refurbish.pot
  repair_refurbish/i18n/repair_refurbish.pot
  repair_refurbish/models/__init__.py
  repair_refurbish/models/product_product.py
  repair_refurbish/models/product_template.py
  repair_refurbish/models/repair.py
  repair_refurbish/models/stock_move.py
  repair_refurbish/readme/CONFIGURE.rst
  repair_refurbish/readme/CONTRIBUTORS.rst
  repair_refurbish/readme/CREDITS.rst
  repair_refurbish/readme/DESCRIPTION.rst
  repair_refurbish/readme/USAGE.rst
  repair_refurbish/static/description/icon.png
  repair_refurbish/static/description/index.html
  repair_refurbish/tests/__init__.py
  repair_refurbish/tests/test_repair_refurbish.py
  repair_refurbish/views/product_product_view.xml
  repair_refurbish/views/product_template_view.xml
  repair_refurbish/views/repair_view.xml
  setup/repair_refurbish/odoo/addons/repair_refurbish
  setup/repair_refurbish/setup.py
Labels: approved

#489 [13.0][mrp_multi_level] improve planned orders
  mrp_multi_level/__manifest__.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/readme/HISTORY.rst
  mrp_multi_level/views/mrp_planned_order_views.xml
Labels: approved

#487 [13.0][MIG] mrp_multi_level_estimate
  mrp_multi_level_estimate/README.rst
  mrp_multi_level_estimate/__init__.py
  mrp_multi_level_estimate/__manifest__.py
  mrp_multi_level_estimate/i18n/mrp_multi_level_estimate.pot
  mrp_multi_level_estimate/models/__init__.py
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/readme/CONFIGURE.rst
  mrp_multi_level_estimate/readme/CONTRIBUTORS.rst
  mrp_multi_level_estimate/readme/DESCRIPTION.rst
  mrp_multi_level_estimate/static/description/icon.png
  mrp_multi_level_estimate/static/description/index.html
  mrp_multi_level_estimate/tests/__init__.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/views/product_mrp_area_views.xml
  mrp_multi_level_estimate/wizards/__init__.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
  oca_dependencies.txt
  setup/mrp_multi_level_estimate/odoo/addons/mrp_multi_level_estimate
  setup/mrp_multi_level_estimate/setup.py
Labels: approved

#431 Migrated mrp_production_putaway_strategy to v13.
  mrp_production_putaway_strategy/README.rst
  mrp_production_putaway_strategy/__init__.py
  mrp_production_putaway_strategy/__manifest__.py
  mrp_production_putaway_strategy/i18n/de.po
  mrp_production_putaway_strategy/i18n/es.po
  mrp_production_putaway_strategy/i18n/es_MX.po
  mrp_production_putaway_strategy/i18n/fr.po
  mrp_production_putaway_strategy/i18n/gl.po
  mrp_production_putaway_strategy/i18n/hr.po
  mrp_production_putaway_strategy/i18n/it.po
  mrp_production_putaway_strategy/i18n/mrp_production_putaway_strategy.pot
  mrp_production_putaway_strategy/i18n/pt_BR.po
  mrp_production_putaway_strategy/i18n/ro.po
  mrp_production_putaway_strategy/i18n/sl.po
  mrp_production_putaway_strategy/i18n/tr.po
  mrp_production_putaway_strategy/i18n/vi_VN.po
  mrp_production_putaway_strategy/i18n/zh_CN.po
  mrp_production_putaway_strategy/models/__init__.py
  mrp_production_putaway_strategy/models/mrp_production.py
  mrp_production_putaway_strategy/readme/CONFIGURE.rst
  mrp_production_putaway_strategy/readme/CONTRIBUTORS.rst
  mrp_production_putaway_strategy/readme/DESCRIPTION.rst
  mrp_production_putaway_strategy/readme/USAGE.rst
  mrp_production_putaway_strategy/static/description/icon.png
  mrp_production_putaway_strategy/static/description/index.html
  mrp_production_putaway_strategy/tests/__init__.py
  mrp_production_putaway_strategy/tests/test_mrp_production.py
  setup/mrp_production_putaway_strategy/odoo/addons/mrp_production_putaway_strategy
  setup/mrp_production_putaway_strategy/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#430 [12.0] [MIG] [WIP] Migration of 'quality_control_mrp'
  quality_control_mrp/README.rst
  quality_control_mrp/__init__.py
  quality_control_mrp/__manifest__.py
  quality_control_mrp/data/quality_control_mrp_data.xml
  quality_control_mrp/i18n/ca.po
  quality_control_mrp/i18n/de.po
  quality_control_mrp/i18n/el_GR.po
  quality_control_mrp/i18n/es.po
  quality_control_mrp/i18n/es_ES.po
  quality_control_mrp/i18n/es_MX.po
  quality_control_mrp/i18n/eu.po
  quality_control_mrp/i18n/fi.po
  quality_control_mrp/i18n/fr.po
  quality_control_mrp/i18n/fr_CH.po
  quality_control_mrp/i18n/fr_FR.po
  quality_control_mrp/i18n/gl.po
  quality_control_mrp/i18n/hr.po
  quality_control_mrp/i18n/hr_HR.po
  quality_control_mrp/i18n/it.po
  quality_control_mrp/i18n/nl.po
  quality_control_mrp/i18n/nl_NL.po
  quality_control_mrp/i18n/pt.po
  quality_control_mrp/i18n/pt_BR.po
  quality_control_mrp/i18n/quality_control_mrp.pot
  quality_control_mrp/i18n/ro.po
  quality_control_mrp/i18n/ru.po
  quality_control_mrp/i18n/sk.po
  quality_control_mrp/i18n/sl.po
  quality_control_mrp/i18n/tr.po
  quality_control_mrp/i18n/tr_TR.po
  quality_control_mrp/i18n/vi_VN.po
  quality_control_mrp/i18n/zh_CN.po
  quality_control_mrp/migrations/12.0.1.0.0/pre-migration.py
  quality_control_mrp/models/__init__.py
  quality_control_mrp/models/mrp_production.py
  quality_control_mrp/models/qc_inspection.py
  quality_control_mrp/readme/CONTRIBUTORS.rst
  quality_control_mrp/readme/DESCRIPTION.rst
  quality_control_mrp/static/description/icon.png
  quality_control_mrp/static/description/index.html
  quality_control_mrp/tests/__init__.py
  quality_control_mrp/tests/test_quality_control_mrp.py
  quality_control_mrp/views/mrp_production_view.xml
  quality_control_mrp/views/qc_inspection_view.xml
Labels: bot is merging ⏳
