Repository OCA/manufacture, pull requests merged in 2020-11, with the labels that each got.

#551 [12.0][FIX] mrp_multi_level: send company recordset to _get_rule
  mrp_multi_level/models/product_mrp_area.py
Labels: approved, bot is merging ⏳

#546 [12.0][FIX] quality_control_stock: Fix qc.trigger creation
  quality_control_stock/models/stock_picking_type.py
  quality_control_stock/tests/test_quality_control_stock.py
Labels: bot is merging ⏳

#475 [13.0][MIG] mrp_bom_note
  mrp_bom_note/README.rst
  mrp_bom_note/__init__.py
  mrp_bom_note/__manifest__.py
  mrp_bom_note/i18n/de.po
  mrp_bom_note/i18n/es.po
  mrp_bom_note/i18n/fi.po
  mrp_bom_note/i18n/fr.po
  mrp_bom_note/i18n/gl.po
  mrp_bom_note/i18n/hr.po
  mrp_bom_note/i18n/hr_HR.po
  mrp_bom_note/i18n/it.po
  mrp_bom_note/i18n/lt.po
  mrp_bom_note/i18n/mrp_bom_note.pot
  mrp_bom_note/i18n/mrp_bom_notes.pot
  mrp_bom_note/i18n/nl_NL.po
  mrp_bom_note/i18n/pt_BR.po
  mrp_bom_note/i18n/ro.po
  mrp_bom_note/i18n/sl.po
  mrp_bom_note/i18n/tr.po
  mrp_bom_note/i18n/tr_TR.po
  mrp_bom_note/i18n/zh_CN.po
  mrp_bom_note/models/__init__.py
  mrp_bom_note/models/mrp_bom.py
  mrp_bom_note/readme/CONTRIBUTORS.rst
  mrp_bom_note/readme/DESCRIPTION.rst
  mrp_bom_note/readme/USAGE.rst
  mrp_bom_note/static/description/icon.png
  mrp_bom_note/static/description/index.html
  mrp_bom_note/tests/__init__.py
  mrp_bom_note/tests/test_mrp_bom_note.py
  mrp_bom_note/views/mrp_bom_view.xml
  setup/mrp_bom_note/odoo/addons/mrp_bom_note
  setup/mrp_bom_note/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#547 [11.0][IMP]mrp_multi_level
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, ready to merge

#554 [13.0][IMP]mrp_multi_level
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#553 [12.0][IMP]mrp_multi_level
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#510 [12.0][IMP] Add repair duration field in repair_calendar_view (like maintenance)
  repair_calendar_view/README.rst
  repair_calendar_view/models/repair.py
  repair_calendar_view/readme/CONTRIBUTORS.rst
  repair_calendar_view/readme/CREDITS.rst
  repair_calendar_view/views/mrp_repair_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#541 [FIX] when a bom has quantity multiplier, consider it
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, ready to merge

#477 [13.0][MIG] mrp_unbuild_tracked_raw_material
  mrp_unbuild_tracked_raw_material/README.rst
  mrp_unbuild_tracked_raw_material/__init__.py
  mrp_unbuild_tracked_raw_material/__manifest__.py
  mrp_unbuild_tracked_raw_material/i18n/mrp_unbuild_tracked_raw_material.pot
  mrp_unbuild_tracked_raw_material/models/__init__.py
  mrp_unbuild_tracked_raw_material/models/product.py
  mrp_unbuild_tracked_raw_material/models/unbuild.py
  mrp_unbuild_tracked_raw_material/readme/CONFIGURE.rst
  mrp_unbuild_tracked_raw_material/readme/CONTRIBUTORS.rst
  mrp_unbuild_tracked_raw_material/readme/DESCRIPTION.rst
  mrp_unbuild_tracked_raw_material/readme/ROADMAP.rst
  mrp_unbuild_tracked_raw_material/readme/USAGE.rst
  mrp_unbuild_tracked_raw_material/static/description/icon.png
  mrp_unbuild_tracked_raw_material/static/description/index.html
  mrp_unbuild_tracked_raw_material/tests/__init__.py
  mrp_unbuild_tracked_raw_material/tests/test_unbuild.py
  mrp_unbuild_tracked_raw_material/views/product_view.xml
  setup/mrp_unbuild_tracked_raw_material/odoo/addons/mrp_unbuild_tracked_raw_material
  setup/mrp_unbuild_tracked_raw_material/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#561 [12.0][FIX] mrp_subcontracting: Skip processed MO when validating receipt
  mrp_subcontracting/models/stock_picking.py
Labels: approved, bot is merging ⏳

#523 [12.0][ADD] quality_control: Menu for quality triggers
  quality_control/views/qc_trigger_view.xml
Labels: approved, bot is merging ⏳, ready to merge
