Repository OCA/manufacture, pull requests merged in 2020-09, with the labels that each got.

#520 [13.0][IMP] mrp_multi_level
  mrp_multi_level/models/product_product.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#476 [13.0][MIG] mrp_production_note
  mrp_production_note/README.rst
  mrp_production_note/__init__.py
  mrp_production_note/__manifest__.py
  mrp_production_note/i18n/de.po
  mrp_production_note/i18n/es.po
  mrp_production_note/i18n/es_MX.po
  mrp_production_note/i18n/fi.po
  mrp_production_note/i18n/fr.po
  mrp_production_note/i18n/gl.po
  mrp_production_note/i18n/hr.po
  mrp_production_note/i18n/hr_HR.po
  mrp_production_note/i18n/it.po
  mrp_production_note/i18n/lt.po
  mrp_production_note/i18n/mrp_production_note.pot
  mrp_production_note/i18n/nl_NL.po
  mrp_production_note/i18n/pt_BR.po
  mrp_production_note/i18n/ro.po
  mrp_production_note/i18n/sl.po
  mrp_production_note/i18n/tr.po
  mrp_production_note/i18n/tr_TR.po
  mrp_production_note/i18n/vi_VN.po
  mrp_production_note/i18n/zh_CN.po
  mrp_production_note/models/__init__.py
  mrp_production_note/models/mrp_production.py
  mrp_production_note/readme/CONTRIBUTORS.rst
  mrp_production_note/readme/DESCRIPTION.rst
  mrp_production_note/readme/USAGE.rst
  mrp_production_note/static/description/icon.png
  mrp_production_note/static/description/index.html
  mrp_production_note/views/mrp_production_view.xml
  setup/mrp_production_note/odoo/addons/mrp_production_note
  setup/mrp_production_note/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#479 [13.0][MIG] product_quick_bom
  product_quick_bom/README.rst
  product_quick_bom/__init__.py
  product_quick_bom/__manifest__.py
  product_quick_bom/i18n/ca.po
  product_quick_bom/i18n/de.po
  product_quick_bom/i18n/el_GR.po
  product_quick_bom/i18n/es.po
  product_quick_bom/i18n/es_ES.po
  product_quick_bom/i18n/es_MX.po
  product_quick_bom/i18n/eu.po
  product_quick_bom/i18n/fi.po
  product_quick_bom/i18n/fr.po
  product_quick_bom/i18n/fr_CH.po
  product_quick_bom/i18n/fr_FR.po
  product_quick_bom/i18n/gl.po
  product_quick_bom/i18n/hr.po
  product_quick_bom/i18n/hr_HR.po
  product_quick_bom/i18n/it.po
  product_quick_bom/i18n/lt.po
  product_quick_bom/i18n/nl.po
  product_quick_bom/i18n/nl_NL.po
  product_quick_bom/i18n/product_quick_bom.pot
  product_quick_bom/i18n/pt.po
  product_quick_bom/i18n/pt_BR.po
  product_quick_bom/i18n/ro.po
  product_quick_bom/i18n/ru.po
  product_quick_bom/i18n/sk.po
  product_quick_bom/i18n/sl.po
  product_quick_bom/i18n/tr.po
  product_quick_bom/i18n/tr_TR.po
  product_quick_bom/i18n/vi_VN.po
  product_quick_bom/i18n/zh_CN.po
  product_quick_bom/models/__init__.py
  product_quick_bom/models/product.py
  product_quick_bom/readme/CONTRIBUTORS.rst
  product_quick_bom/readme/DESCRIPTION.rst
  product_quick_bom/readme/USAGE.rst
  product_quick_bom/static/description/icon.png
  product_quick_bom/static/description/icon.svg
  product_quick_bom/static/description/index.html
  product_quick_bom/tests/__init__.py
  product_quick_bom/tests/test_quick_bom.py
  product_quick_bom/views/product_view.xml
  setup/product_quick_bom/odoo/addons/product_quick_bom
  setup/product_quick_bom/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#506 [12.0][FIX] mrp_multi_level: Check BoM Line Attrs
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, ready to merge

#527 [12.0][FIX] mrp_subcontracting: Overwrite active_id context in create()
  mrp_subcontracting/models/stock_picking.py
  mrp_subcontracting/tests/test_subcontracting.py
Labels: approved, bot is merging ⏳

#448 [12.0][ADD] mrp_auto_create_lot
  mrp_auto_create_lot/README.rst
  mrp_auto_create_lot/__init__.py
  mrp_auto_create_lot/__manifest__.py
  mrp_auto_create_lot/models/__init__.py
  mrp_auto_create_lot/models/mrp_workorder.py
  mrp_auto_create_lot/readme/CONTRIBUTORS.rst
  mrp_auto_create_lot/readme/DESCRIPTION.rst
  mrp_auto_create_lot/readme/HISTORY.rst
  mrp_auto_create_lot/readme/USAGE.rst
  mrp_auto_create_lot/static/description/icon.png
  mrp_auto_create_lot/static/description/index.html
  mrp_auto_create_lot/tests/__init__.py
  mrp_auto_create_lot/tests/test_auto_create_lot.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, needs review, ready to merge

#434 [10.0][IMP] mrp_no_partial: Restrict 'Produce' for lots
  mrp_no_partial/__init__.py
  mrp_no_partial/readme/DESCRIPTION.rst
  mrp_no_partial/tests/test_no_partial.py
  mrp_no_partial/wizards/__init__.py
  mrp_no_partial/wizards/mrp_product_produce.py
Labels: approved, bot is merging ⏳, ready to merge

#323 [12.0][MIG] Migrated mrp_progress_button to v12.
  mrp_progress_button/README.rst
  mrp_progress_button/__init__.py
  mrp_progress_button/__manifest__.py
  mrp_progress_button/i18n/de.po
  mrp_progress_button/i18n/es.po
  mrp_progress_button/i18n/es_MX.po
  mrp_progress_button/i18n/fr.po
  mrp_progress_button/i18n/gl.po
  mrp_progress_button/i18n/hr.po
  mrp_progress_button/i18n/hr_HR.po
  mrp_progress_button/i18n/lt.po
  mrp_progress_button/i18n/mrp_progress_button.pot
  mrp_progress_button/i18n/nl_NL.po
  mrp_progress_button/i18n/pt_BR.po
  mrp_progress_button/i18n/ro.po
  mrp_progress_button/i18n/sl.po
  mrp_progress_button/i18n/tr.po
  mrp_progress_button/i18n/vi_VN.po
  mrp_progress_button/i18n/zh_CN.po
  mrp_progress_button/models/__init__.py
  mrp_progress_button/models/mrp_production.py
  mrp_progress_button/readme/CONTRIBUTORS.rst
  mrp_progress_button/readme/DESCRIPTION.rst
  mrp_progress_button/readme/USAGE.rst
  mrp_progress_button/static/description/icon.png
  mrp_progress_button/static/description/index.html
  mrp_progress_button/tests/__init__.py
  mrp_progress_button/tests/test_progress_button.py
  mrp_progress_button/views/production.xml
Labels: approved, needs review, ready to merge

#531 [12.0][ADD] mrp_production_show_post_inventory
  mrp_production_show_post_inventory/__init__.py
  mrp_production_show_post_inventory/__manifest__.py
  mrp_production_show_post_inventory/readme/CONTRIBUTORS.rst
  mrp_production_show_post_inventory/readme/DESCRIPTION.rst
  mrp_production_show_post_inventory/views/mrp_production.xml
Labels: approved, bot is merging ⏳

#491 [13.0][mrp_multi_level] fix error in _compute_order_release_date of mrp.inventory
  mrp_multi_level/models/mrp_inventory.py
Labels: approved, bot is merging ⏳
