Repository OCA/manufacture, pull requests merged in 2020-12, with the labels that each got.

#563 [12.0] [FIX] quality_control_stock: expected singleton when setting multiple stock pickings to Done
  quality_control_stock/models/stock_picking.py
Labels: approved, bot is merging ⏳

#557 ADD module mrp_request_workcenter_cycle 12.0
  mrp_request_workcenter_cycle/__init__.py
  mrp_request_workcenter_cycle/__manifest__.py
  mrp_request_workcenter_cycle/demo/request.xml
  mrp_request_workcenter_cycle/demo/workcenter.xml
  mrp_request_workcenter_cycle/models/__init__.py
  mrp_request_workcenter_cycle/models/product.py
  mrp_request_workcenter_cycle/models/product_workcenter_quantity.py
  mrp_request_workcenter_cycle/models/request.py
  mrp_request_workcenter_cycle/models/request_workcenter.py
  mrp_request_workcenter_cycle/readme/CONFIGURE.rst
  mrp_request_workcenter_cycle/readme/CONTRIBUTORS.rst
  mrp_request_workcenter_cycle/readme/DESCRIPTION.rst
  mrp_request_workcenter_cycle/readme/ROADMAP.rst
  mrp_request_workcenter_cycle/readme/USAGE.rst
  mrp_request_workcenter_cycle/security/ir.model.access.csv
  mrp_request_workcenter_cycle/static/description/request.png
  mrp_request_workcenter_cycle/static/description/settings.png
  mrp_request_workcenter_cycle/tests/__init__.py
  mrp_request_workcenter_cycle/tests/test_cycle.py
  mrp_request_workcenter_cycle/views/product.xml
  mrp_request_workcenter_cycle/views/request.xml
  mrp_request_workcenter_cycle/wizards/__init__.py
  mrp_request_workcenter_cycle/wizards/request_create_mo.py
Labels: approved, bot is merging ⏳, ready to merge

#579 12.0 FIX update travis file to recent format, remove old env vars
  .travis.yml
Labels: bot is merging ⏳

#558 12.0 ADD module mrp_request_bom_structure
  mrp_request_bom_structure/__init__.py
  mrp_request_bom_structure/__manifest__.py
  mrp_request_bom_structure/data/config_parameter.xml
  mrp_request_bom_structure/i18n/fr.po
  mrp_request_bom_structure/models/__init__.py
  mrp_request_bom_structure/models/bom_structure.py
  mrp_request_bom_structure/models/mrp_request.py
  mrp_request_bom_structure/readme/CONTRIBUTORS.rst
  mrp_request_bom_structure/readme/DESCRIPTION.rst
  mrp_request_bom_structure/readme/ROADMAP.rst
  mrp_request_bom_structure/readme/USAGE.rst
  mrp_request_bom_structure/tests/__init__.py
  mrp_request_bom_structure/tests/test_request_structure.py
  mrp_request_bom_structure/views/mrp_request.xml
Labels: bot is merging ⏳
