Repository OCA/manufacture, pull requests merged in 2021-11, with the labels that each got.

#692 [14.0][MIG] mrp_progress_button
  mrp_progress_button/README.rst
  mrp_progress_button/__init__.py
  mrp_progress_button/__manifest__.py
  mrp_progress_button/i18n/de.po
  mrp_progress_button/i18n/es.po
  mrp_progress_button/i18n/es_MX.po
  mrp_progress_button/i18n/fr.po
  mrp_progress_button/i18n/gl.po
  mrp_progress_button/i18n/hr.po
  mrp_progress_button/i18n/hr_HR.po
  mrp_progress_button/i18n/lt.po
  mrp_progress_button/i18n/mrp_progress_button.pot
  mrp_progress_button/i18n/nl_NL.po
  mrp_progress_button/i18n/pt_BR.po
  mrp_progress_button/i18n/ro.po
  mrp_progress_button/i18n/sl.po
  mrp_progress_button/i18n/tr.po
  mrp_progress_button/i18n/vi_VN.po
  mrp_progress_button/i18n/zh_CN.po
  mrp_progress_button/models/__init__.py
  mrp_progress_button/models/mrp_production.py
  mrp_progress_button/readme/CONTRIBUTORS.rst
  mrp_progress_button/readme/DESCRIPTION.rst
  mrp_progress_button/readme/USAGE.rst
  mrp_progress_button/static/description/icon.png
  mrp_progress_button/static/description/index.html
  mrp_progress_button/tests/__init__.py
  mrp_progress_button/tests/test_progress_button.py
  mrp_progress_button/views/production.xml
  setup/mrp_progress_button/odoo/addons/mrp_progress_button
  setup/mrp_progress_button/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#696 [13.0][FIX] mrp_production_grouped_by product: MO duplicate lines
  mrp_production_grouped_by_product/models/__init__.py
  mrp_production_grouped_by_product/models/stock_move.py
  mrp_production_grouped_by_product/tests/test_mrp_production_grouped_by_product.py
Labels: approved, ready to merge, bot is merging ⏳

#699 [ADD] 12.0 stock_mts_mto_rule_mrp
  stock_mts_mto_rule_mrp/README.rst
  stock_mts_mto_rule_mrp/__init__.py
  stock_mts_mto_rule_mrp/__manifest__.py
  stock_mts_mto_rule_mrp/models/__init__.py
  stock_mts_mto_rule_mrp/models/mrp_production.py
  stock_mts_mto_rule_mrp/readme/CONFIGURE.rst
  stock_mts_mto_rule_mrp/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule_mrp/readme/DESCRIPTION.rst
  stock_mts_mto_rule_mrp/readme/HISTORY.rst
  stock_mts_mto_rule_mrp/readme/USAGE.rst
  stock_mts_mto_rule_mrp/tests/__init__.py
  stock_mts_mto_rule_mrp/tests/test_mto_mts_route_mrp.py
Labels: bot is merging ⏳

#685 [14.0][MIG] mrp_planned_order_matrix
  mrp_planned_order_matrix/README.rst
  mrp_planned_order_matrix/__init__.py
  mrp_planned_order_matrix/__manifest__.py
  mrp_planned_order_matrix/i18n/mrp_planned_order_matrix.pot
  mrp_planned_order_matrix/readme/CONTRIBUTORS.rst
  mrp_planned_order_matrix/readme/DESCRIPTION.rst
  mrp_planned_order_matrix/readme/INSTALL.rst
  mrp_planned_order_matrix/readme/USAGE.rst
  mrp_planned_order_matrix/security/ir.model.access.csv
  mrp_planned_order_matrix/static/description/icon.png
  mrp_planned_order_matrix/static/description/index.html
  mrp_planned_order_matrix/tests/__init__.py
  mrp_planned_order_matrix/tests/test_mrp_planned_order_matrix.py
  mrp_planned_order_matrix/wizards/__init__.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
  setup/mrp_planned_order_matrix/odoo/addons/mrp_planned_order_matrix
  setup/mrp_planned_order_matrix/setup.py
Labels: bot is merging ⏳

#411 [12.0][MIG] mrp_mto_with_stock
  mrp_mto_with_stock/README.rst
  mrp_mto_with_stock/__init__.py
  mrp_mto_with_stock/__manifest__.py
  mrp_mto_with_stock/demo/product.xml
  mrp_mto_with_stock/i18n/ca.po
  mrp_mto_with_stock/i18n/de.po
  mrp_mto_with_stock/i18n/es.po
  mrp_mto_with_stock/i18n/es_MX.po
  mrp_mto_with_stock/i18n/fi.po
  mrp_mto_with_stock/i18n/fr.po
  mrp_mto_with_stock/i18n/fr_CH.po
  mrp_mto_with_stock/i18n/hr.po
  mrp_mto_with_stock/i18n/hr_HR.po
  mrp_mto_with_stock/i18n/it.po
  mrp_mto_with_stock/i18n/lt.po
  mrp_mto_with_stock/i18n/mrp_mto_with_stock.pot
  mrp_mto_with_stock/i18n/nl_NL.po
  mrp_mto_with_stock/i18n/pt_BR.po
  mrp_mto_with_stock/i18n/ro.po
  mrp_mto_with_stock/i18n/sl.po
  mrp_mto_with_stock/i18n/tr_TR.po
  mrp_mto_with_stock/i18n/vi_VN.po
  mrp_mto_with_stock/i18n/zh_CN.po
  mrp_mto_with_stock/models/__init__.py
  mrp_mto_with_stock/models/mrp_production.py
  mrp_mto_with_stock/models/product_template.py
  mrp_mto_with_stock/models/stock_warehouse.py
  mrp_mto_with_stock/readme/CONFIGURE.rst
  mrp_mto_with_stock/readme/CONTRIBUTORS.rst
  mrp_mto_with_stock/readme/DESCRIPTION.rst
  mrp_mto_with_stock/readme/USAGE.rst
  mrp_mto_with_stock/static/description/icon.png
  mrp_mto_with_stock/static/description/index.html
  mrp_mto_with_stock/tests/__init__.py
  mrp_mto_with_stock/tests/test_mrp_mto_with_stock.py
  mrp_mto_with_stock/views/product_template_view.xml
  mrp_mto_with_stock/views/stock_warehouse.xml
  setup/mrp_mto_with_stock/odoo/addons/mrp_mto_with_stock
  setup/mrp_mto_with_stock/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#705 [14.0][mrp_multi_level][fix] allow to procure from planned orders
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_move.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/wizards/mrp_inventory_procure.py
Labels: bot is merging ⏳

#706 [14.0][IMP] mrp_progress_button: Unstart button and date_start field added
  mrp_progress_button/models/mrp_production.py
  mrp_progress_button/readme/CONTRIBUTORS.rst
  mrp_progress_button/tests/test_progress_button.py
  mrp_progress_button/views/production.xml
Labels: approved, bot is merging ⏳

#687 [14.0][ADD]repair_type
  repair_type/__init__.py
  repair_type/__manifest__.py
  repair_type/models/__init__.py
  repair_type/models/repair.py
  repair_type/models/repair_type.py
  repair_type/readme/CONFIGURE.rst
  repair_type/readme/CONTRIBUTORS.rst
  repair_type/readme/DESCRIPTION.rst
  repair_type/readme/ROADMAP.rst
  repair_type/readme/USAGE.rst
  repair_type/security/ir.model.access.csv
  repair_type/tests/__init__.py
  repair_type/tests/test_repair_type.py
  repair_type/views/repair.xml
  repair_type/views/repair_type.xml
  setup/repair_type/odoo/addons/repair_type
  setup/repair_type/setup.py
Labels: approved, bot is merging ⏳

#710 [14.0][MIG] mrp_production_grouped_by_product
  mrp_production_grouped_by_product/README.rst
  mrp_production_grouped_by_product/__init__.py
  mrp_production_grouped_by_product/__manifest__.py
  mrp_production_grouped_by_product/i18n/de.po
  mrp_production_grouped_by_product/i18n/es.po
  mrp_production_grouped_by_product/i18n/mrp_production_grouped_by_product.pot
  mrp_production_grouped_by_product/models/__init__.py
  mrp_production_grouped_by_product/models/mrp_production.py
  mrp_production_grouped_by_product/models/stock_move.py
  mrp_production_grouped_by_product/models/stock_picking_type.py
  mrp_production_grouped_by_product/models/stock_rule.py
  mrp_production_grouped_by_product/readme/CONFIGURE.rst
  mrp_production_grouped_by_product/readme/CONTRIBUTORS.rst
  mrp_production_grouped_by_product/readme/DESCRIPTION.rst
  mrp_production_grouped_by_product/readme/HISTORY.rst
  mrp_production_grouped_by_product/readme/ROADMAP.rst
  mrp_production_grouped_by_product/static/description/icon.png
  mrp_production_grouped_by_product/static/description/index.html
  mrp_production_grouped_by_product/tests/__init__.py
  mrp_production_grouped_by_product/tests/test_mrp_production_grouped_by_product.py
  mrp_production_grouped_by_product/views/stock_picking_type_views.xml
  setup/mrp_production_grouped_by_product/odoo/addons/mrp_production_grouped_by_product
  setup/mrp_production_grouped_by_product/setup.py
Labels: approved, bot is merging ⏳

#709 [15.0][MIG] mrp_progress_button
  mrp_progress_button/README.rst
  mrp_progress_button/__init__.py
  mrp_progress_button/__manifest__.py
  mrp_progress_button/i18n/de.po
  mrp_progress_button/i18n/es.po
  mrp_progress_button/i18n/es_MX.po
  mrp_progress_button/i18n/fr.po
  mrp_progress_button/i18n/gl.po
  mrp_progress_button/i18n/hr.po
  mrp_progress_button/i18n/hr_HR.po
  mrp_progress_button/i18n/lt.po
  mrp_progress_button/i18n/mrp_progress_button.pot
  mrp_progress_button/i18n/nl_NL.po
  mrp_progress_button/i18n/pt_BR.po
  mrp_progress_button/i18n/ro.po
  mrp_progress_button/i18n/sl.po
  mrp_progress_button/i18n/tr.po
  mrp_progress_button/i18n/vi_VN.po
  mrp_progress_button/i18n/zh_CN.po
  mrp_progress_button/models/__init__.py
  mrp_progress_button/models/mrp_production.py
  mrp_progress_button/readme/CONTRIBUTORS.rst
  mrp_progress_button/readme/DESCRIPTION.rst
  mrp_progress_button/readme/USAGE.rst
  mrp_progress_button/static/description/icon.png
  mrp_progress_button/static/description/index.html
  mrp_progress_button/tests/__init__.py
  mrp_progress_button/tests/test_progress_button.py
  mrp_progress_button/views/production.xml
  setup/mrp_progress_button/odoo/addons/mrp_progress_button
  setup/mrp_progress_button/setup.py
Labels: approved, bot is merging ⏳

#703 [15.0][MIG] mrp_bom_location
  mrp_bom_location/README.rst
  mrp_bom_location/__init__.py
  mrp_bom_location/__manifest__.py
  mrp_bom_location/i18n/de.po
  mrp_bom_location/i18n/mrp_bom_location.pot
  mrp_bom_location/models/__init__.py
  mrp_bom_location/models/mrp_bom.py
  mrp_bom_location/readme/CONTRIBUTORS.rst
  mrp_bom_location/readme/DESCRIPTION.rst
  mrp_bom_location/readme/USAGE.rst
  mrp_bom_location/report/__init__.py
  mrp_bom_location/report/bom_structure.py
  mrp_bom_location/static/description/icon.png
  mrp_bom_location/static/description/index.html
  mrp_bom_location/views/mrp_view.xml
  mrp_bom_location/views/report_mrpbomstructure.xml
  setup/mrp_bom_location/odoo/addons/mrp_bom_location
  setup/mrp_bom_location/setup.py
Labels: bot is merging ⏳

#708 [14.0][MIG] stock_picking_product_kit_helper
  setup/stock_picking_product_kit_helper/odoo/addons/stock_picking_product_kit_helper
  setup/stock_picking_product_kit_helper/setup.py
  stock_picking_product_kit_helper/README.rst
  stock_picking_product_kit_helper/__init__.py
  stock_picking_product_kit_helper/__manifest__.py
  stock_picking_product_kit_helper/i18n/stock_picking_product_kit_helper.pot
  stock_picking_product_kit_helper/models/__init__.py
  stock_picking_product_kit_helper/models/stock_picking.py
  stock_picking_product_kit_helper/readme/CONTRIBUTORS.rst
  stock_picking_product_kit_helper/readme/DESCRIPTION.rst
  stock_picking_product_kit_helper/readme/HISTORY.rst
  stock_picking_product_kit_helper/readme/USAGE.rst
  stock_picking_product_kit_helper/security/ir.model.access.csv
  stock_picking_product_kit_helper/static/description/icon.png
  stock_picking_product_kit_helper/static/description/icon.svg
  stock_picking_product_kit_helper/static/description/index.html
  stock_picking_product_kit_helper/tests/__init__.py
  stock_picking_product_kit_helper/tests/test_stock_picking_product_kit_helper.py
  stock_picking_product_kit_helper/views/stock_view.xml
Labels: approved, ready to merge, bot is merging ⏳
