Repository OCA/manufacture, pull requests merged in 2021-05, with the labels that each got.

#639 [11.0][FIX] mrp_multi_level: Consider timezone of the warehouse to generate…
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, ready to merge

#638 [13.0][FIX] mrp_multi_level: Consider timezone of the warehouse to generate mrp inventory records.
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, ready to merge

#643 [14.0][FIX] mrp_multi_level: Consider timezone of the warehouse to generate mrp inventory records.
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#642 [12.0][FIX] mrp_multi_level: Consider timezone of the warehouse to generate mrp inventory records.
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#644 [12.0] mrp_bom_tracking: Wrong model reference
  mrp_bom_tracking/models/mrp_bom.py
Labels: approved, bot is merging ⏳

#626 [12.0][FIX] add modules table and fix translation status on README.md
  README.md
Labels: bot is merging ⏳

#632 [12.0] stock_whole_kit_constraint: New Addon
  stock_whole_kit_constraint/README.rst
  stock_whole_kit_constraint/__init__.py
  stock_whole_kit_constraint/__manifest__.py
  stock_whole_kit_constraint/i18n/es.po
  stock_whole_kit_constraint/i18n/stock_whole_kit_constraint.pot
  stock_whole_kit_constraint/models/__init__.py
  stock_whole_kit_constraint/models/product_template.py
  stock_whole_kit_constraint/models/stock_move.py
  stock_whole_kit_constraint/models/stock_picking.py
  stock_whole_kit_constraint/readme/CONFIGURE.rst
  stock_whole_kit_constraint/readme/CONTRIBUTORS.rst
  stock_whole_kit_constraint/readme/DESCRIPTION.rst
  stock_whole_kit_constraint/readme/USAGE.rst
  stock_whole_kit_constraint/static/description/icon.png
  stock_whole_kit_constraint/static/description/index.html
  stock_whole_kit_constraint/tests/__init__.py
  stock_whole_kit_constraint/tests/test_stock_whole_kit_constraint.py
  stock_whole_kit_constraint/views/product_template_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#395 [12.0] Port of mrp_production_hierarchy #274
  mrp_production_hierarchy/README.rst
  mrp_production_hierarchy/__init__.py
  mrp_production_hierarchy/__manifest__.py
  mrp_production_hierarchy/i18n/fr.po
  mrp_production_hierarchy/i18n/mrp_production_hierarchy.pot
  mrp_production_hierarchy/models/__init__.py
  mrp_production_hierarchy/models/mrp_production.py
  mrp_production_hierarchy/models/stock_rule.py
  mrp_production_hierarchy/readme/CONTRIBUTORS.rst
  mrp_production_hierarchy/readme/DESCRIPTION.rst
  mrp_production_hierarchy/readme/ROADMAP.rst
  mrp_production_hierarchy/readme/USAGE.rst
  mrp_production_hierarchy/static/description/icon.png
  mrp_production_hierarchy/static/description/index.html
  mrp_production_hierarchy/static/description/mrp_production_hierarchy_1.png
  mrp_production_hierarchy/static/description/mrp_production_hierarchy_2.png
  mrp_production_hierarchy/static/description/mrp_production_hierarchy_3.png
  mrp_production_hierarchy/tests/__init__.py
  mrp_production_hierarchy/tests/test_mrp_production_hierarchy.py
  mrp_production_hierarchy/views/mrp_production.xml
  setup/mrp_production_hierarchy/odoo/addons/mrp_production_hierarchy
  setup/mrp_production_hierarchy/setup.py
Labels: bot is merging ⏳, needs review

#637 [14.0][MIG] mrp_sale_info: migration to 14.0
  mrp_sale_info/README.rst
  mrp_sale_info/__init__.py
  mrp_sale_info/__manifest__.py
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/readme/CONTRIBUTORS.rst
  mrp_sale_info/readme/DESCRIPTION.rst
  mrp_sale_info/readme/USAGE.rst
  mrp_sale_info/static/description/icon.png
  mrp_sale_info/static/description/index.html
  mrp_sale_info/tests/__init__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
Labels: bot is merging ⏳
