Repository OCA/manufacture, pull requests merged in 2021-12, with the labels that each got.

#627 [13.0][REM] repair_calendar_view: remove this module (this resource was assimilated by the base_repair module)
  repair_calendar_view/README.rst
  repair_calendar_view/__init__.py
  repair_calendar_view/__manifest__.py
  repair_calendar_view/i18n/ar.po
  repair_calendar_view/i18n/bs.po
  repair_calendar_view/i18n/ca.po
  repair_calendar_view/i18n/cs.po
  repair_calendar_view/i18n/de.po
  repair_calendar_view/i18n/en_GB.po
  repair_calendar_view/i18n/es.po
  repair_calendar_view/i18n/es_CR.po
  repair_calendar_view/i18n/es_EC.po
  repair_calendar_view/i18n/es_MX.po
  repair_calendar_view/i18n/es_VE.po
  repair_calendar_view/i18n/et.po
  repair_calendar_view/i18n/fi.po
  repair_calendar_view/i18n/fr.po
  repair_calendar_view/i18n/gl.po
  repair_calendar_view/i18n/hr.po
  repair_calendar_view/i18n/hr_HR.po
  repair_calendar_view/i18n/hu.po
  repair_calendar_view/i18n/id.po
  repair_calendar_view/i18n/it.po
  repair_calendar_view/i18n/ja.po
  repair_calendar_view/i18n/lt.po
  repair_calendar_view/i18n/lv.po
  repair_calendar_view/i18n/mk.po
  repair_calendar_view/i18n/mn.po
  repair_calendar_view/i18n/mrp_repair_calendar_view.pot
  repair_calendar_view/i18n/nb.po
  repair_calendar_view/i18n/nl.po
  repair_calendar_view/i18n/nl_BE.po
  repair_calendar_view/i18n/nl_NL.po
  repair_calendar_view/i18n/pl.po
  repair_calendar_view/i18n/pt.po
  repair_calendar_view/i18n/pt_BR.po
  repair_calendar_view/i18n/pt_PT.po
  repair_calendar_view/i18n/repair_calendar_view.pot
  repair_calendar_view/i18n/ro.po
  repair_calendar_view/i18n/ru.po
  repair_calendar_view/i18n/sl.po
  repair_calendar_view/i18n/sr@latin.po
  repair_calendar_view/i18n/sv.po
  repair_calendar_view/i18n/th.po
  repair_calendar_view/i18n/tr.po
  repair_calendar_view/i18n/tr_TR.po
  repair_calendar_view/i18n/vi.po
  repair_calendar_view/i18n/zh_CN.po
  repair_calendar_view/i18n/zh_TW.po
  repair_calendar_view/models/__init__.py
  repair_calendar_view/models/repair.py
  repair_calendar_view/readme/CONTRIBUTORS.rst
  repair_calendar_view/readme/DESCRIPTION.rst
  repair_calendar_view/static/description/icon.png
  repair_calendar_view/static/description/index.html
  repair_calendar_view/views/mrp_repair_view.xml
  setup/repair_calendar_view/odoo/addons/repair_calendar_view
  setup/repair_calendar_view/setup.py
Labels: bot is merging ⏳

#724 [14.0] [MIG] mrp_bom_tracking
  mrp_bom_tracking/README.rst
  mrp_bom_tracking/__init__.py
  mrp_bom_tracking/__manifest__.py
  mrp_bom_tracking/i18n/de.po
  mrp_bom_tracking/i18n/mrp_bom_tracking.pot
  mrp_bom_tracking/models/__init__.py
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/readme/CONTRIBUTORS.rst
  mrp_bom_tracking/readme/DESCRIPTION.rst
  mrp_bom_tracking/static/description/icon.png
  mrp_bom_tracking/static/description/index.html
  mrp_bom_tracking/tests/__init__.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
  mrp_bom_tracking/views/bom_template.xml
  setup/mrp_bom_tracking/odoo/addons/mrp_bom_tracking
  setup/mrp_bom_tracking/setup.py
Labels: approved, bot is merging ⏳

#701 [14.0][mrp_multi_level][imp] improve speed by creating mrp.move records using the create_multi capabilities
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, ready to merge, bot is merging ⏳
