Repository OCA/manufacture, pull requests merged in 2021-03, with the labels that each got.

#610 [12.0][IMP] quality_control: Added triggers on product.product views
  quality_control/README.rst
  quality_control/readme/CONTRIBUTORS.rst
  quality_control/static/description/index.html
  quality_control/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#615 [12.0][FIX] repair_timeline: fix colors attribute
  repair_timeline/views/repair_order.xml
Labels: approved, bot is merging ⏳

#614 [MIG] mrp_sale_info: migration to 13.0
  mrp_sale_info/README.rst
  mrp_sale_info/__init__.py
  mrp_sale_info/__manifest__.py
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/readme/CONTRIBUTORS.rst
  mrp_sale_info/readme/DESCRIPTION.rst
  mrp_sale_info/readme/USAGE.rst
  mrp_sale_info/static/description/icon.png
  mrp_sale_info/static/description/index.html
  mrp_sale_info/tests/__init__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
  setup/mrp_sale_info/odoo/addons/mrp_sale_info
  setup/mrp_sale_info/setup.py
Labels: approved, bot is merging ⏳

#616 [13.0][IMP] quality_control_oca: Added triggers on product.product views
  quality_control_oca/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#612 [13.0] [MIG] quality_control_mrp: Migration to v13
  quality_control_mrp_oca/README.rst
  quality_control_mrp_oca/__init__.py
  quality_control_mrp_oca/__manifest__.py
  quality_control_mrp_oca/data/quality_control_mrp_data.xml
  quality_control_mrp_oca/i18n/ca.po
  quality_control_mrp_oca/i18n/de.po
  quality_control_mrp_oca/i18n/el_GR.po
  quality_control_mrp_oca/i18n/es.po
  quality_control_mrp_oca/i18n/es_ES.po
  quality_control_mrp_oca/i18n/es_MX.po
  quality_control_mrp_oca/i18n/eu.po
  quality_control_mrp_oca/i18n/fi.po
  quality_control_mrp_oca/i18n/fr.po
  quality_control_mrp_oca/i18n/fr_CH.po
  quality_control_mrp_oca/i18n/fr_FR.po
  quality_control_mrp_oca/i18n/gl.po
  quality_control_mrp_oca/i18n/hr.po
  quality_control_mrp_oca/i18n/hr_HR.po
  quality_control_mrp_oca/i18n/it.po
  quality_control_mrp_oca/i18n/nl.po
  quality_control_mrp_oca/i18n/nl_NL.po
  quality_control_mrp_oca/i18n/pt.po
  quality_control_mrp_oca/i18n/pt_BR.po
  quality_control_mrp_oca/i18n/quality_control_mrp_oca.pot
  quality_control_mrp_oca/i18n/ro.po
  quality_control_mrp_oca/i18n/ru.po
  quality_control_mrp_oca/i18n/sk.po
  quality_control_mrp_oca/i18n/sl.po
  quality_control_mrp_oca/i18n/tr.po
  quality_control_mrp_oca/i18n/tr_TR.po
  quality_control_mrp_oca/i18n/vi_VN.po
  quality_control_mrp_oca/i18n/zh_CN.po
  quality_control_mrp_oca/models/__init__.py
  quality_control_mrp_oca/models/mrp_production.py
  quality_control_mrp_oca/models/qc_inspection.py
  quality_control_mrp_oca/readme/CONTRIBUTORS.rst
  quality_control_mrp_oca/readme/DESCRIPTION.rst
  quality_control_mrp_oca/static/description/icon.png
  quality_control_mrp_oca/static/description/index.html
  quality_control_mrp_oca/tests/__init__.py
  quality_control_mrp_oca/tests/test_quality_control_mrp.py
  quality_control_mrp_oca/views/mrp_production_view.xml
  quality_control_mrp_oca/views/qc_inspection_view.xml
  setup/quality_control_mrp_oca/odoo/addons/quality_control_mrp_oca
  setup/quality_control_mrp_oca/setup.py
Labels: approved, bot is merging ⏳

#630 [UPD] apply copier template to repository
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  base_repair/__manifest__.py
  mrp_planned_order_matrix/__manifest__.py
  mrp_production_grouped_by_product/__manifest__.py
  mrp_sale_info/__manifest__.py
  mrp_warehouse_calendar/__manifest__.py
Labels: bot is merging ⏳

#592 [14.0] [MIG] mrp_multi_level
  mrp_multi_level/README.rst
  mrp_multi_level/__init__.py
  mrp_multi_level/__manifest__.py
  mrp_multi_level/data/mrp_area_data.xml
  mrp_multi_level/data/mrp_multi_level_cron.xml
  mrp_multi_level/demo/initial_on_hand_demo.xml
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_category_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/demo/res_partner_demo.xml
  mrp_multi_level/docs/mrp_multi_level_test_run.ods
  mrp_multi_level/i18n/de.po
  mrp_multi_level/i18n/es.po
  mrp_multi_level/i18n/hr.po
  mrp_multi_level/i18n/mrp_multi_level.pot
  mrp_multi_level/models/__init__.py
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_move.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/mrp_production.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/models/product_product.py
  mrp_multi_level/models/product_template.py
  mrp_multi_level/models/stock_location.py
  mrp_multi_level/models/stock_rule.py
  mrp_multi_level/readme/CONFIGURE.rst
  mrp_multi_level/readme/CONTRIBUTORS.rst
  mrp_multi_level/readme/DESCRIPTION.rst
  mrp_multi_level/readme/HISTORY.rst
  mrp_multi_level/readme/USAGE.rst
  mrp_multi_level/security/ir.model.access.csv
  mrp_multi_level/security/mrp_multi_level_security.xml
  mrp_multi_level/static/description/icon.png
  mrp_multi_level/static/description/index.html
  mrp_multi_level/static/src/img/icon.png
  mrp_multi_level/tests/__init__.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_menuitem.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/views/product_product_views.xml
  mrp_multi_level/views/product_template_views.xml
  mrp_multi_level/views/stock_location_views.xml
  mrp_multi_level/wizards/__init__.py
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_inventory_procure_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level_views.xml
  setup/mrp_multi_level/odoo/addons/mrp_multi_level
  setup/mrp_multi_level/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#631 [UPD] apply latest copier template
  .copier-answers.yml
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳

#623 [13.0][FIX] remove user_id (duplicate)
  base_repair/models/repair_order.py
  base_repair/readme/DESCRIPTION.rst
  base_repair/views/repair_order.xml
Labels: approved, bot is merging ⏳

#621 [14.0][MIG] base repair
  base_repair/README.rst
  base_repair/__init__.py
  base_repair/__manifest__.py
  base_repair/i18n/base_repair.pot
  base_repair/i18n/pt_BR.po
  base_repair/models/__init__.py
  base_repair/models/repair_order.py
  base_repair/readme/CONTRIBUTORS.rst
  base_repair/readme/CREDITS.rst
  base_repair/readme/DESCRIPTION.rst
  base_repair/static/description/banner.png
  base_repair/static/description/icon.png
  base_repair/static/description/index.html
  base_repair/views/repair_order.xml
  setup/base_repair/odoo/addons/base_repair
  setup/base_repair/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#624 [12.0][NEW] Repair Payment Term
  repair_payment_term/README.rst
  repair_payment_term/__init__.py
  repair_payment_term/__manifest__.py
  repair_payment_term/models/__init__.py
  repair_payment_term/models/repair_order.py
  repair_payment_term/readme/CONFIGURE.rst
  repair_payment_term/readme/CONTRIBUTORS.rst
  repair_payment_term/readme/CREDITS.rst
  repair_payment_term/readme/DESCRIPTION.rst
  repair_payment_term/readme/USAGE.rst
  repair_payment_term/report/repair_report_templates.xml
  repair_payment_term/static/description/icon.png
  repair_payment_term/static/description/index.html
  repair_payment_term/tests/__init__.py
  repair_payment_term/tests/test_repair.py
  repair_payment_term/views/repair_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#609 [14.0] [MIG] mrp_multi_level_estimate
  mrp_multi_level_estimate/README.rst
  mrp_multi_level_estimate/__init__.py
  mrp_multi_level_estimate/__manifest__.py
  mrp_multi_level_estimate/i18n/mrp_multi_level_estimate.pot
  mrp_multi_level_estimate/models/__init__.py
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/readme/CONFIGURE.rst
  mrp_multi_level_estimate/readme/CONTRIBUTORS.rst
  mrp_multi_level_estimate/readme/DESCRIPTION.rst
  mrp_multi_level_estimate/static/description/icon.png
  mrp_multi_level_estimate/static/description/index.html
  mrp_multi_level_estimate/tests/__init__.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/views/product_mrp_area_views.xml
  mrp_multi_level_estimate/wizards/__init__.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
  setup/mrp_multi_level_estimate/odoo/addons/mrp_multi_level_estimate
  setup/mrp_multi_level_estimate/setup.py
Labels: bot is merging ⏳

#634 [14.0][FIX] mrp_multi_level: error with 3 step delivery
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳
