Repository OCA/manufacture, pull requests merged in 2021-01, with the labels that each got.

#573 [WIP] [14.0] [ADD] mrp_analytic_cost_material: Added new module to track the cost of raw materials.
  mrp_analytic_cost_material/README.rst
  mrp_analytic_cost_material/__init__.py
  mrp_analytic_cost_material/__manifest__.py
  mrp_analytic_cost_material/models/__init__.py
  mrp_analytic_cost_material/models/account_analytic_line.py
  mrp_analytic_cost_material/models/mrp_production.py
  mrp_analytic_cost_material/readme/CONTRIBUTORS.rst
  mrp_analytic_cost_material/readme/DESCRIPTION.rst
  mrp_analytic_cost_material/readme/USAGE.rst
  mrp_analytic_cost_material/views/account_analytic_line_view.xml
  mrp_analytic_cost_material/views/mrp_production_views.xml
  oca_dependencies.txt
  setup/mrp_analytic_cost_material/odoo/addons/mrp_analytic_cost_material
  setup/mrp_analytic_cost_material/setup.py
Labels: bot is merging ⏳

#543 [12.0][ADD] mrp_subcontracting_purchase_link
  mrp_subcontracting_purchase_link/README.rst
  mrp_subcontracting_purchase_link/__init__.py
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/i18n/ja.po
  mrp_subcontracting_purchase_link/i18n/mrp_subcontracting_purchase_link.pot
  mrp_subcontracting_purchase_link/models/__init__.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/readme/CONTRIBUTORS.rst
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_link/static/description/index.html
  mrp_subcontracting_purchase_link/tests/__init__.py
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
  mrp_subcontracting_purchase_link/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#467 [11.0] [ADD] new module quality_control_plan
  oca_dependencies.txt
  quality_control_plan/README.rst
  quality_control_plan/__init__.py
  quality_control_plan/__manifest__.py
  quality_control_plan/i18n/it.po
  quality_control_plan/i18n/quality_control_plan.pot
  quality_control_plan/models/__init__.py
  quality_control_plan/models/mgmtsystem_nonconformity_inspection.py
  quality_control_plan/models/partner_quality.py
  quality_control_plan/models/product_trigger.py
  quality_control_plan/models/qc_inspection_plan.py
  quality_control_plan/models/qc_plan.py
  quality_control_plan/models/qc_trigger.py
  quality_control_plan/models/qc_trigger_partner_line.py
  quality_control_plan/models/stock_picking_inspection.py
  quality_control_plan/readme/CONFIGURE.rst
  quality_control_plan/readme/CONTRIBUTORS.rst
  quality_control_plan/readme/DESCRIPTION.rst
  quality_control_plan/readme/HISTORY.rst
  quality_control_plan/readme/INSTALL.rst
  quality_control_plan/readme/USAGE.rst
  quality_control_plan/security/ir.model.access.csv
  quality_control_plan/static/description/icon.png
  quality_control_plan/static/description/index.html
  quality_control_plan/tests/__init__.py
  quality_control_plan/tests/test_plan.py
  quality_control_plan/views/mgmtsystem_nonconformity_view.xml
  quality_control_plan/views/partner_view.xml
  quality_control_plan/views/product_view.xml
  quality_control_plan/views/qc_inspection_view.xml
  quality_control_plan/views/qc_menu.xml
  quality_control_plan/views/qc_plan_view.xml
Labels: approved, bot is merging ⏳, ready to merge, work in progress

#578 [12.0][IMP] mrp_production_auto_post_inventory, add cron job
  mrp_production_auto_post_inventory/__manifest__.py
  mrp_production_auto_post_inventory/data/cron.xml
  mrp_production_auto_post_inventory/models/__init__.py
  mrp_production_auto_post_inventory/models/company.py
  mrp_production_auto_post_inventory/models/mrp_production.py
  mrp_production_auto_post_inventory/models/res_config_settings.py
  mrp_production_auto_post_inventory/readme/CONTRIBUTORS.rst
  mrp_production_auto_post_inventory/readme/DESCRIPTION.rst
  mrp_production_auto_post_inventory/tests/test_mrp_production.py
  mrp_production_auto_post_inventory/views/res_config_settings.xml
  mrp_production_auto_post_inventory/wizard/mrp_product_produce.py
Labels: approved, bot is merging ⏳, ready to merge

#586 [12.0][ADD] mrp_production_quant_manual_assign
  mrp_production_quant_manual_assign/README.rst
  mrp_production_quant_manual_assign/__init__.py
  mrp_production_quant_manual_assign/__manifest__.py
  mrp_production_quant_manual_assign/i18n/mrp_production_quant_manual_assign.pot
  mrp_production_quant_manual_assign/readme/CONTRIBUTORS.rst
  mrp_production_quant_manual_assign/readme/DESCRIPTION.rst
  mrp_production_quant_manual_assign/readme/USAGE.rst
  mrp_production_quant_manual_assign/static/description/icon.png
  mrp_production_quant_manual_assign/static/description/index.html
  mrp_production_quant_manual_assign/views/mrp_production_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#544 ADD 14.0 mrp_workcenter_hierarchical
  mrp_workcenter_hierarchical/README.rst
  mrp_workcenter_hierarchical/__init__.py
  mrp_workcenter_hierarchical/__manifest__.py
  mrp_workcenter_hierarchical/data/mrp_demo.xml
  mrp_workcenter_hierarchical/models/__init__.py
  mrp_workcenter_hierarchical/models/mrp_workcenter.py
  mrp_workcenter_hierarchical/readme/CONFIGURE.rst
  mrp_workcenter_hierarchical/readme/CONTRIBUTORS.rst
  mrp_workcenter_hierarchical/readme/DESCRIPTION.rst
  mrp_workcenter_hierarchical/readme/USAGE.rst
  mrp_workcenter_hierarchical/static/description/index.html
  mrp_workcenter_hierarchical/static/src/img/icon.png
  mrp_workcenter_hierarchical/static/src/img/img1.png
  mrp_workcenter_hierarchical/tests/__init__.py
  mrp_workcenter_hierarchical/tests/test_compute_level.py
  mrp_workcenter_hierarchical/views/workcenter_view.xml
  setup/mrp_workcenter_hierarchical/odoo/addons/mrp_workcenter_hierarchical
  setup/mrp_workcenter_hierarchical/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#580 [12.0][FIX] mrp_auto_create_lot: be able to force existing lot
  mrp_auto_create_lot/models/mrp_workorder.py
Labels: approved, bot is merging ⏳, ready to merge

#535 Fix ACL error
  mrp_production_request/models/stock_warehouse_orderpoint.py
Labels: approved, bot is merging ⏳, ready to merge
