Repository OCA/manufacture, pull requests merged in 2021-09, with the labels that each got.

#662 [14.0][MIG] mrp_production_quant_manual_assign
  mrp_production_quant_manual_assign/README.rst
  mrp_production_quant_manual_assign/__init__.py
  mrp_production_quant_manual_assign/__manifest__.py
  mrp_production_quant_manual_assign/i18n/mrp_production_quant_manual_assign.pot
  mrp_production_quant_manual_assign/i18n/pt_BR.po
  mrp_production_quant_manual_assign/models/__init__.py
  mrp_production_quant_manual_assign/models/stock_move.py
  mrp_production_quant_manual_assign/readme/CONTRIBUTORS.rst
  mrp_production_quant_manual_assign/readme/DESCRIPTION.rst
  mrp_production_quant_manual_assign/readme/USAGE.rst
  mrp_production_quant_manual_assign/static/description/icon.png
  mrp_production_quant_manual_assign/static/description/index.html
  mrp_production_quant_manual_assign/views/mrp_production_views.xml
  mrp_production_quant_manual_assign/wizards/__init__.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants_view.xml
  setup/mrp_production_quant_manual_assign/odoo/addons/mrp_production_quant_manual_assign
  setup/mrp_production_quant_manual_assign/setup.py
Labels: approved, bot is merging ⏳

#666 [14.0[ADD] mrp_account_analytic: generate Analytic Items for manufacturing consumptions.
  mrp_account_analytic/README.rst
  mrp_account_analytic/__init__.py
  mrp_account_analytic/__manifest__.py
  mrp_account_analytic/models/__init__.py
  mrp_account_analytic/models/account_analytic_line.py
  mrp_account_analytic/models/mrp_workorder.py
  mrp_account_analytic/models/stock_move.py
  mrp_account_analytic/readme/CONTRIBUTORS.rst
  mrp_account_analytic/readme/DESCRIPTION.rst
  mrp_account_analytic/readme/USAGE.rst
  mrp_account_analytic/tests/__init__.py
  mrp_account_analytic/tests/test_mrp_analytic.py
  mrp_account_analytic/views/account_analytic_line_view.xml
  setup/mrp_account_analytic/odoo/addons/mrp_account_analytic
  setup/mrp_account_analytic/setup.py
Labels: bot is merging ⏳

#471 [13.0][MIG] mrp_stock_orderpoint_manual_procurement
  mrp_stock_orderpoint_manual_procurement/README.rst
  mrp_stock_orderpoint_manual_procurement/__init__.py
  mrp_stock_orderpoint_manual_procurement/__manifest__.py
  mrp_stock_orderpoint_manual_procurement/i18n/mrp_stock_orderpoint_manual_procurement.pot
  mrp_stock_orderpoint_manual_procurement/models/__init__.py
  mrp_stock_orderpoint_manual_procurement/models/mrp_production.py
  mrp_stock_orderpoint_manual_procurement/models/stock_rule.py
  mrp_stock_orderpoint_manual_procurement/readme/CONTRIBUTORS.rst
  mrp_stock_orderpoint_manual_procurement/readme/DESCRIPTION.rst
  mrp_stock_orderpoint_manual_procurement/readme/USAGE.rst
  mrp_stock_orderpoint_manual_procurement/static/description/icon.png
  mrp_stock_orderpoint_manual_procurement/static/description/index.html
  mrp_stock_orderpoint_manual_procurement/tests/__init__.py
  mrp_stock_orderpoint_manual_procurement/tests/test_mrp_manual_procurement.py
  mrp_stock_orderpoint_manual_procurement/views/mrp_production_view.xml
  setup/mrp_stock_orderpoint_manual_procurement/odoo/addons/mrp_stock_orderpoint_manual_procurement
  setup/mrp_stock_orderpoint_manual_procurement/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#674 [13.0][FIX] quality_control_oca: Remove object_id and type fields in Quality control test model because they have no use.
  quality_control_oca/demo/quality_control_demo.xml
  quality_control_oca/models/qc_test.py
  quality_control_oca/views/qc_test_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#673 [14.0][ADD] mrp_production_serial_matrix
  mrp_production_serial_matrix/README.rst
  mrp_production_serial_matrix/__init__.py
  mrp_production_serial_matrix/__manifest__.py
  mrp_production_serial_matrix/models/__init__.py
  mrp_production_serial_matrix/models/mrp_production.py
  mrp_production_serial_matrix/readme/CONTRIBUTORS.rst
  mrp_production_serial_matrix/readme/DESCRIPTION.rst
  mrp_production_serial_matrix/readme/ROADMAP.rst
  mrp_production_serial_matrix/readme/USAGE.rst
  mrp_production_serial_matrix/security/ir.model.access.csv
  mrp_production_serial_matrix/static/description/icon.png
  mrp_production_serial_matrix/static/description/index.html
  mrp_production_serial_matrix/tests/__init__.py
  mrp_production_serial_matrix/tests/test_mrp_production_serial_matrix.py
  mrp_production_serial_matrix/views/mrp_production_views.xml
  mrp_production_serial_matrix/wizards/__init__.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_line.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_view.xml
  setup/mrp_production_serial_matrix/odoo/addons/mrp_production_serial_matrix
  setup/mrp_production_serial_matrix/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#664 [FIX] mrp_analytic_cost: the module has to be depend on account_analytic_wip
  mrp_analytic_cost/__manifest__.py
Labels: bot is merging ⏳

#663 [IMP] mrp_sale_info: add Customer Reference to Manufacturing Order and Work Order
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/readme/CONTRIBUTORS.rst
  mrp_sale_info/readme/DESCRIPTION.rst
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
Labels: bot is merging ⏳
