Repository OCA/manufacture, pull requests merged in 2021-02, with the labels that each got.

#577 [14.0][MIG] repair_refurbish
  repair_refurbish/README.rst
  repair_refurbish/__init__.py
  repair_refurbish/__manifest__.py
  repair_refurbish/data/stock_data.xml
  repair_refurbish/i18n/de.po
  repair_refurbish/i18n/mrp_repair_refurbish.pot
  repair_refurbish/i18n/repair_refurbish.pot
  repair_refurbish/models/__init__.py
  repair_refurbish/models/product_product.py
  repair_refurbish/models/product_template.py
  repair_refurbish/models/repair.py
  repair_refurbish/models/stock_move.py
  repair_refurbish/readme/CONFIGURE.rst
  repair_refurbish/readme/CONTRIBUTORS.rst
  repair_refurbish/readme/CREDITS.rst
  repair_refurbish/readme/DESCRIPTION.rst
  repair_refurbish/readme/USAGE.rst
  repair_refurbish/static/description/icon.png
  repair_refurbish/static/description/index.html
  repair_refurbish/tests/__init__.py
  repair_refurbish/tests/test_repair_refurbish.py
  repair_refurbish/views/product_product_view.xml
  repair_refurbish/views/product_template_view.xml
  repair_refurbish/views/repair_view.xml
  setup/repair_refurbish/odoo/addons/repair_refurbish
  setup/repair_refurbish/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#589 [14.0][MIG] mrp_bom_location
  mrp_bom_location/README.rst
  mrp_bom_location/__init__.py
  mrp_bom_location/__manifest__.py
  mrp_bom_location/i18n/de.po
  mrp_bom_location/i18n/mrp_bom_location.pot
  mrp_bom_location/models/__init__.py
  mrp_bom_location/models/mrp_bom.py
  mrp_bom_location/readme/CONTRIBUTORS.rst
  mrp_bom_location/readme/DESCRIPTION.rst
  mrp_bom_location/readme/USAGE.rst
  mrp_bom_location/report/__init__.py
  mrp_bom_location/report/bom_structure.py
  mrp_bom_location/static/description/icon.png
  mrp_bom_location/static/description/index.html
  mrp_bom_location/views/mrp_view.xml
  mrp_bom_location/views/report_mrpbomstructure.xml
  setup/mrp_bom_location/odoo/addons/mrp_bom_location
  setup/mrp_bom_location/setup.py
Labels: approved, bot is merging ⏳

#588 [IMP] mrp_analytic_cost_material: trigger Analytic Item on consumption of raw materials
  mrp_analytic_cost_material/__manifest__.py
  mrp_analytic_cost_material/models/__init__.py
  mrp_analytic_cost_material/models/account_analytic_line.py
  mrp_analytic_cost_material/models/mrp_production.py
  mrp_analytic_cost_material/models/stock_move.py
  mrp_analytic_cost_material/views/account_analytic_line_view.xml
  mrp_analytic_cost_material/views/mrp_production_views.xml
Labels: bot is merging ⏳

#590 [14.0] [MIG] mrp_warehouse_calendar
  mrp_warehouse_calendar/README.rst
  mrp_warehouse_calendar/__init__.py
  mrp_warehouse_calendar/__manifest__.py
  mrp_warehouse_calendar/i18n/de.po
  mrp_warehouse_calendar/i18n/mrp_warehouse_calendar.pot
  mrp_warehouse_calendar/models/__init__.py
  mrp_warehouse_calendar/models/mrp_production.py
  mrp_warehouse_calendar/models/stock_rule.py
  mrp_warehouse_calendar/readme/CONFIGURE.rst
  mrp_warehouse_calendar/readme/CONTRIBUTORS.rst
  mrp_warehouse_calendar/readme/DESCRIPTION.rst
  mrp_warehouse_calendar/readme/USAGE.rst
  mrp_warehouse_calendar/static/description/icon.png
  mrp_warehouse_calendar/static/description/index.html
  mrp_warehouse_calendar/tests/__init__.py
  mrp_warehouse_calendar/tests/test_mrp_warehouse_calendar.py
Labels: approved, bot is merging ⏳

#593 [12.0][ADD] base_repair_config
  base_repair_config/README.rst
  base_repair_config/__init__.py
  base_repair_config/__manifest__.py
  base_repair_config/i18n/base_repair_config.pot
  base_repair_config/i18n/pt_BR.po
  base_repair_config/readme/CONFIGURE.rst
  base_repair_config/readme/CONTRIBUTORS.rst
  base_repair_config/readme/DESCRIPTION.rst
  base_repair_config/readme/USAGE.rst
  base_repair_config/static/description/banner.png
  base_repair_config/static/description/icon.png
  base_repair_config/static/description/index.html
  base_repair_config/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, ready to merge

#594 [12.0] add base_repair
  base_repair/README.rst
  base_repair/__init__.py
  base_repair/__manifest__.py
  base_repair/i18n/base_repair.pot
  base_repair/i18n/pt_BR.po
  base_repair/models/__init__.py
  base_repair/models/repair_order.py
  base_repair/readme/CONTRIBUTORS.rst
  base_repair/readme/CREDITS.rst
  base_repair/readme/DESCRIPTION.rst
  base_repair/static/description/banner.png
  base_repair/static/description/icon.png
  base_repair/static/description/index.html
  base_repair/views/repair_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#524 [12.0][ADD] repair_timeline
  repair_timeline/README.rst
  repair_timeline/__init__.py
  repair_timeline/__manifest__.py
  repair_timeline/i18n/pt_BR.po
  repair_timeline/i18n/repair_timeline.pot
  repair_timeline/readme/CONTRIBUTORS.rst
  repair_timeline/readme/CREDITS.rst
  repair_timeline/readme/DESCRIPTION.rst
  repair_timeline/static/description/banner.png
  repair_timeline/static/description/icon.png
  repair_timeline/static/description/index.html
  repair_timeline/views/repair_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#596 [13.0] [MIG] quality_control_oca_stock: Migration to v13.0
  quality_control_stock_oca/README.rst
  quality_control_stock_oca/__init__.py
  quality_control_stock_oca/__manifest__.py
  quality_control_stock_oca/i18n/ca.po
  quality_control_stock_oca/i18n/de.po
  quality_control_stock_oca/i18n/el_GR.po
  quality_control_stock_oca/i18n/es.po
  quality_control_stock_oca/i18n/es_AR.po
  quality_control_stock_oca/i18n/es_ES.po
  quality_control_stock_oca/i18n/es_MX.po
  quality_control_stock_oca/i18n/eu.po
  quality_control_stock_oca/i18n/fi.po
  quality_control_stock_oca/i18n/fr.po
  quality_control_stock_oca/i18n/fr_CH.po
  quality_control_stock_oca/i18n/fr_FR.po
  quality_control_stock_oca/i18n/gl.po
  quality_control_stock_oca/i18n/hr.po
  quality_control_stock_oca/i18n/hr_HR.po
  quality_control_stock_oca/i18n/it.po
  quality_control_stock_oca/i18n/nl.po
  quality_control_stock_oca/i18n/nl_NL.po
  quality_control_stock_oca/i18n/pt.po
  quality_control_stock_oca/i18n/pt_BR.po
  quality_control_stock_oca/i18n/quality_control_stock_oca.pot
  quality_control_stock_oca/i18n/ro.po
  quality_control_stock_oca/i18n/ru.po
  quality_control_stock_oca/i18n/sk.po
  quality_control_stock_oca/i18n/sl.po
  quality_control_stock_oca/i18n/tr.po
  quality_control_stock_oca/i18n/tr_TR.po
  quality_control_stock_oca/i18n/vi_VN.po
  quality_control_stock_oca/i18n/zh_CN.po
  quality_control_stock_oca/models/__init__.py
  quality_control_stock_oca/models/qc_inspection.py
  quality_control_stock_oca/models/qc_trigger.py
  quality_control_stock_oca/models/stock_picking.py
  quality_control_stock_oca/models/stock_picking_type.py
  quality_control_stock_oca/models/stock_production_lot.py
  quality_control_stock_oca/readme/CONTRIBUTORS.rst
  quality_control_stock_oca/readme/DESCRIPTION.rst
  quality_control_stock_oca/readme/ROADMAP.rst
  quality_control_stock_oca/security/ir.model.access.csv
  quality_control_stock_oca/static/description/icon.png
  quality_control_stock_oca/static/description/index.html
  quality_control_stock_oca/tests/__init__.py
  quality_control_stock_oca/tests/test_quality_control_stock.py
  quality_control_stock_oca/views/qc_inspection_view.xml
  quality_control_stock_oca/views/stock_picking_view.xml
  quality_control_stock_oca/views/stock_production_lot_view.xml
  setup/quality_control_stock_oca/odoo/addons/quality_control_stock_oca
  setup/quality_control_stock_oca/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#602 [12.0][IMP] base_repair: repair order graph view and menu reporting
  base_repair/README.rst
  base_repair/i18n/base_repair.pot
  base_repair/i18n/pt_BR.po
  base_repair/readme/DESCRIPTION.rst
  base_repair/static/description/index.html
  base_repair/views/repair_order.xml
Labels: approved, bot is merging ⏳

#600 [13.0][MIG] base_repair: Migration to 13.0
  base_repair/README.rst
  base_repair/__init__.py
  base_repair/__manifest__.py
  base_repair/i18n/base_repair.pot
  base_repair/i18n/pt_BR.po
  base_repair/models/__init__.py
  base_repair/models/repair_order.py
  base_repair/readme/CONTRIBUTORS.rst
  base_repair/readme/CREDITS.rst
  base_repair/readme/DESCRIPTION.rst
  base_repair/static/description/banner.png
  base_repair/static/description/icon.png
  base_repair/static/description/index.html
  base_repair/views/repair_order.xml
  setup/base_repair/odoo/addons/base_repair
  setup/base_repair/setup.py
Labels: approved, bot is merging ⏳
