Repository OCA/manufacture, pull requests merged in 2022-03, with the labels that each got.

#766 [13.0][FIX] mrp_multi_level: Fix case when Purchase Uom is different from Uom
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#741 [15.0][MIG] mrp_production_putaway_strategy
  mrp_production_putaway_strategy/README.rst
  mrp_production_putaway_strategy/__init__.py
  mrp_production_putaway_strategy/__manifest__.py
  mrp_production_putaway_strategy/i18n/de.po
  mrp_production_putaway_strategy/i18n/es.po
  mrp_production_putaway_strategy/i18n/es_MX.po
  mrp_production_putaway_strategy/i18n/fr.po
  mrp_production_putaway_strategy/i18n/gl.po
  mrp_production_putaway_strategy/i18n/hr.po
  mrp_production_putaway_strategy/i18n/it.po
  mrp_production_putaway_strategy/i18n/mrp_production_putaway_strategy.pot
  mrp_production_putaway_strategy/i18n/pt_BR.po
  mrp_production_putaway_strategy/i18n/ro.po
  mrp_production_putaway_strategy/i18n/sl.po
  mrp_production_putaway_strategy/i18n/tr.po
  mrp_production_putaway_strategy/i18n/vi_VN.po
  mrp_production_putaway_strategy/i18n/zh_CN.po
  mrp_production_putaway_strategy/models/__init__.py
  mrp_production_putaway_strategy/models/mrp_production.py
  mrp_production_putaway_strategy/readme/CONFIGURE.rst
  mrp_production_putaway_strategy/readme/CONTRIBUTORS.rst
  mrp_production_putaway_strategy/readme/DESCRIPTION.rst
  mrp_production_putaway_strategy/readme/USAGE.rst
  mrp_production_putaway_strategy/static/description/icon.png
  mrp_production_putaway_strategy/static/description/index.html
  mrp_production_putaway_strategy/tests/__init__.py
  mrp_production_putaway_strategy/tests/test_mrp_production.py
  setup/mrp_production_putaway_strategy/odoo/addons/mrp_production_putaway_strategy
  setup/mrp_production_putaway_strategy/setup.py
Labels: approved, bot is merging ⏳

#769 [15.0][FIX] mrp_multi_level: Fix case when Purchase Uom is different from U…
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#767 [15.0][IMP] mrp_multi_level: allow to specify distribution LT
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
Labels: approved, bot is merging ⏳

#771 [13.0][FIX] mrp_bom_tracking: Correct UoM model when changing it on a bom line
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
Labels: approved, bot is merging ⏳

#773 [14.0][ADD] mrp_attachment_mgmt: New addon.
  mrp_attachment_mgmt/README.rst
  mrp_attachment_mgmt/__init__.py
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/i18n/es.po
  mrp_attachment_mgmt/i18n/mrp_attachment_mgmt.pot
  mrp_attachment_mgmt/models/__init__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/models/mrp_workorder.py
  mrp_attachment_mgmt/models/product.py
  mrp_attachment_mgmt/readme/CONFIGURE.rst
  mrp_attachment_mgmt/readme/CONTRIBUTORS.rst
  mrp_attachment_mgmt/readme/DESCRIPTION.rst
  mrp_attachment_mgmt/readme/USAGE.rst
  mrp_attachment_mgmt/static/description/icon.png
  mrp_attachment_mgmt/static/description/index.html
  mrp_attachment_mgmt/static/src/js/mrp_documents_controller_mixin.js
  mrp_attachment_mgmt/template/assets.xml
  mrp_attachment_mgmt/tests/__init__.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
  mrp_attachment_mgmt/views/mrp_bom_view.xml
  mrp_attachment_mgmt/views/product_views.xml
  mrp_attachment_mgmt/views/workorder_attachments_views.xml
  setup/mrp_attachment_mgmt/odoo/addons/mrp_attachment_mgmt
  setup/mrp_attachment_mgmt/setup.py
Labels: approved, bot is merging ⏳

#772 [15.0][IMP] mrp_multi_level: Add mrp_move form view
  mrp_multi_level/__manifest__.py
  mrp_multi_level/views/mrp_move_views.xml
Labels: approved, bot is merging ⏳

#775 [14.0][IMP] mrp_attachment_mgmt: Show in the smart-button of the bom the attachments (ir.attachment) uploaded from bom and the attachments of the components.
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/static/src/js/mrp_documents_controller_mixin.js
  mrp_attachment_mgmt/template/assets.xml
  mrp_attachment_mgmt/tests/common.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
Labels: approved, ready to merge, bot is merging ⏳

#749 [15.0][PORT] mrp_multi_level #690 from 14.0
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_move.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#765 [13.0][IMP] mrp_multi_level: Archiving a product should archive related MRP parameters
  mrp_multi_level/models/product_product.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#778 [15.0][IMP] mrp_multi_level: Archiving a product should archive related MRP parameters
  mrp_multi_level/models/product_product.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#777 [14.0][IMP] mrp_multi_level: Archiving a product should archive related MRP parameters
  mrp_multi_level/models/product_product.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳
