Repository OCA/manufacture, pull requests merged in 2022-12, with the labels that each got.

#871 [14.0][IMP] mrp_subcontracting_partner_management
  mrp_subcontracting_partner_management/__manifest__.py
  mrp_subcontracting_partner_management/models/res_partner.py
  mrp_subcontracting_partner_management/readme/CONFIGURE.rst
  mrp_subcontracting_partner_management/readme/USAGE.rst
  mrp_subcontracting_partner_management/static/description/icon.png
  mrp_subcontracting_partner_management/tests/__init__.py
  mrp_subcontracting_partner_management/tests/test_create_subcontractor_partner_location.py
  mrp_subcontracting_partner_management/views/res_partner.xml
  mrp_subcontracting_partner_management/views/res_partner_views.xml
  mrp_subcontracting_partner_management/views/stock_picking_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#819 [15.0][MIG] mrp_tag : Migration to 15.0
  mrp_tag/README.rst
  mrp_tag/__init__.py
  mrp_tag/__manifest__.py
  mrp_tag/i18n/mrp_tag.pot
  mrp_tag/models/__init__.py
  mrp_tag/models/mrp_production.py
  mrp_tag/models/mrp_tag.py
  mrp_tag/readme/CONTRIBUTORS.rst
  mrp_tag/readme/DESCRIPTION.rst
  mrp_tag/readme/USAGE.rst
  mrp_tag/security/ir.model.access.csv
  mrp_tag/static/description/icon.png
  mrp_tag/static/description/index.html
  mrp_tag/views/mrp_production_view.xml
  mrp_tag/views/mrp_tag_view.xml
  setup/mrp_tag/odoo/addons/mrp_tag
  setup/mrp_tag/setup.py
Labels: bot is merging ⏳

#913 [15.0] [ADD] `mrp_production_component_availability_search`
  mrp_production_component_availability_search/README.rst
  mrp_production_component_availability_search/__init__.py
  mrp_production_component_availability_search/__manifest__.py
  mrp_production_component_availability_search/models/__init__.py
  mrp_production_component_availability_search/models/mrp_production.py
  mrp_production_component_availability_search/readme/CONTRIBUTORS.rst
  mrp_production_component_availability_search/readme/DESCRIPTION.rst
  mrp_production_component_availability_search/tests/__init__.py
  mrp_production_component_availability_search/tests/test_search.py
  mrp_production_component_availability_search/views/mrp_production.xml
  setup/mrp_production_component_availability_search/odoo/addons/mrp_production_component_availability_search
  setup/mrp_production_component_availability_search/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#919 [13.0][UPD] repo template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#908 [14.0][ADD] mrp_unbuild_move_link
  mrp_unbuild_move_link/README.rst
  mrp_unbuild_move_link/__init__.py
  mrp_unbuild_move_link/__manifest__.py
  mrp_unbuild_move_link/models/__init__.py
  mrp_unbuild_move_link/models/mrp_unbuild.py
  mrp_unbuild_move_link/models/stock_move.py
  mrp_unbuild_move_link/readme/CONTRIBUTORS.rst
  mrp_unbuild_move_link/readme/DESCRIPTION.rst
  mrp_unbuild_move_link/static/description/icon.png
  mrp_unbuild_move_link/tests/__init__.py
  mrp_unbuild_move_link/tests/test_mrp_unbuild_move_link.py
  mrp_unbuild_move_link/views/stock_move_views.xml
  setup/mrp_unbuild_move_link/odoo/addons/mrp_unbuild_move_link
  setup/mrp_unbuild_move_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#909 [14.0][IMP] account_move_line_mrp_info: journal items are now accessed from a smart button
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/readme/USAGE.rst
  account_move_line_mrp_info/tests/__init__.py
  account_move_line_mrp_info/tests/test_mrp_journal_items.py
  account_move_line_mrp_info/views/mrp_production_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#822 [14.0][MIG] product_mrp_info
  product_mrp_info/README.rst
  product_mrp_info/__init__.py
  product_mrp_info/__manifest__.py
  product_mrp_info/i18n/product_mrp_info.pot
  product_mrp_info/models/__init__.py
  product_mrp_info/models/product.py
  product_mrp_info/readme/CONTRIBUTORS.rst
  product_mrp_info/readme/DESCRIPTION.rst
  product_mrp_info/readme/USAGE.rst
  product_mrp_info/static/description/icon.png
  product_mrp_info/static/description/index.html
  product_mrp_info/tests/__init__.py
  product_mrp_info/tests/test_product_mrp_info.py
  product_mrp_info/views/product_views.xml
  setup/product_mrp_info/odoo/addons/product_mrp_info
  setup/product_mrp_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#888 [15.0] [MIG] `mrp_bom_attribute_match`: Migration to 15.0
  mrp_bom_attribute_match/README.rst
  mrp_bom_attribute_match/__init__.py
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/i18n/hr.po
  mrp_bom_attribute_match/i18n/it.po
  mrp_bom_attribute_match/i18n/mrp_bom_attribute_match.pot
  mrp_bom_attribute_match/models/__init__.py
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/models/mrp_production.py
  mrp_bom_attribute_match/models/product.py
  mrp_bom_attribute_match/readme/CONTRIBUTORS.rst
  mrp_bom_attribute_match/readme/DESCRIPTION.rst
  mrp_bom_attribute_match/readme/USAGE.rst
  mrp_bom_attribute_match/static/description/icon.png
  mrp_bom_attribute_match/static/description/index.html
  mrp_bom_attribute_match/tests/__init__.py
  mrp_bom_attribute_match/tests/common.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match.py
  mrp_bom_attribute_match/views/mrp_bom_views.xml
  setup/mrp_bom_attribute_match/odoo/addons/mrp_bom_attribute_match
  setup/mrp_bom_attribute_match/setup.py
Labels: approved, bot is merging ⏳

#886 [IMP] mrp_bom_attribute_match: Avoid write same product
  mrp_bom_attribute_match/models/mrp_bom.py
Labels: approved, bot is merging ⏳

#877 [14.0][FIX] mrp_bom_attribute_match: writing on multiple products
  mrp_bom_attribute_match/models/product.py
Labels: approved, ready to merge, bot is merging ⏳

#921 [15.0][IMP] mrp_workorder_sequence: Multiple improvements
  mrp_workorder_sequence/__init__.py
  mrp_workorder_sequence/__manifest__.py
  mrp_workorder_sequence/hooks.py
  mrp_workorder_sequence/models/mrp_production.py
  mrp_workorder_sequence/models/mrp_workorder.py
  mrp_workorder_sequence/readme/CONTRIBUTORS.rst
  mrp_workorder_sequence/tests/test_mrp_workorder_sequence.py
Labels: approved, ready to merge, bot is merging ⏳

#828 [14.0][MIG] mrp_bom_line_sequence : Migration to 14.0
  mrp_bom_line_sequence/README.rst
  mrp_bom_line_sequence/__init__.py
  mrp_bom_line_sequence/__manifest__.py
  mrp_bom_line_sequence/i18n/mrp_bom_line_sequence.pot
  mrp_bom_line_sequence/models/__init__.py
  mrp_bom_line_sequence/models/mrp.py
  mrp_bom_line_sequence/readme/CONTRIBUTORS.rst
  mrp_bom_line_sequence/readme/DESCRIPTION.rst
  mrp_bom_line_sequence/readme/USAGE.rst
  mrp_bom_line_sequence/static/description/icon.png
  mrp_bom_line_sequence/static/description/index.html
  mrp_bom_line_sequence/views/stock_view.xml
  setup/mrp_bom_line_sequence/odoo/addons/mrp_bom_line_sequence
  setup/mrp_bom_line_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#914 [15.0][ADD] mrp_production_date_planned_finished
  mrp_production_date_planned_finished/README.rst
  mrp_production_date_planned_finished/__init__.py
  mrp_production_date_planned_finished/__manifest__.py
  mrp_production_date_planned_finished/models/__init__.py
  mrp_production_date_planned_finished/models/mrp_production.py
  mrp_production_date_planned_finished/readme/CONTRIBUTORS.rst
  mrp_production_date_planned_finished/readme/DESCRIPTION.rst
  mrp_production_date_planned_finished/tests/__init__.py
  mrp_production_date_planned_finished/tests/test_date_planned_finished.py
  mrp_production_date_planned_finished/views/mrp_production.xml
  setup/mrp_production_date_planned_finished/odoo/addons/mrp_production_date_planned_finished
  setup/mrp_production_date_planned_finished/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#906 [15.0][MIG] mrp_sale_info: Migration to `15.0`
  mrp_sale_info/README.rst
  mrp_sale_info/__init__.py
  mrp_sale_info/__manifest__.py
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/readme/CONTRIBUTORS.rst
  mrp_sale_info/readme/DESCRIPTION.rst
  mrp_sale_info/readme/USAGE.rst
  mrp_sale_info/static/description/icon.png
  mrp_sale_info/static/description/index.html
  mrp_sale_info/tests/__init__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
  setup/mrp_sale_info/odoo/addons/mrp_sale_info
  setup/mrp_sale_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#865 [14.0][IMP] mrp_workcenter_hierarchical: Parents level identification
  mrp_workcenter_hierarchical/models/mrp_workcenter.py
Labels: approved, ready to merge, bot is merging ⏳

#815 [15.0][MIG] mrp_bom_component_menu
  mrp_bom_component_menu/README.rst
  mrp_bom_component_menu/__init__.py
  mrp_bom_component_menu/__manifest__.py
  mrp_bom_component_menu/i18n/de.po
  mrp_bom_component_menu/i18n/mrp_bom_component_menu.pot
  mrp_bom_component_menu/i18n/zh_CN.po
  mrp_bom_component_menu/readme/CONTRIBUTORS.rst
  mrp_bom_component_menu/readme/DESCRIPTION.rst
  mrp_bom_component_menu/readme/USAGE.rst
  mrp_bom_component_menu/static/description/icon.png
  mrp_bom_component_menu/static/description/index.html
  mrp_bom_component_menu/views/mrp_bom_component_view.xml
  setup/mrp_bom_component_menu/odoo/addons/mrp_bom_component_menu
  setup/mrp_bom_component_menu/setup.py
Labels: approved, bot is merging ⏳

#843 [15.0][ADD] mrp_lot_number_propagation
  mrp_lot_number_propagation/README.rst
  mrp_lot_number_propagation/__init__.py
  mrp_lot_number_propagation/__manifest__.py
  mrp_lot_number_propagation/models/__init__.py
  mrp_lot_number_propagation/models/mrp_bom.py
  mrp_lot_number_propagation/models/mrp_bom_line.py
  mrp_lot_number_propagation/models/mrp_production.py
  mrp_lot_number_propagation/models/product_product.py
  mrp_lot_number_propagation/models/product_template.py
  mrp_lot_number_propagation/models/stock_move.py
  mrp_lot_number_propagation/readme/CONTRIBUTORS.rst
  mrp_lot_number_propagation/readme/DESCRIPTION.rst
  mrp_lot_number_propagation/readme/ROADMAP.rst
  mrp_lot_number_propagation/tests/__init__.py
  mrp_lot_number_propagation/tests/common.py
  mrp_lot_number_propagation/tests/test_mrp_bom.py
  mrp_lot_number_propagation/tests/test_mrp_production.py
  mrp_lot_number_propagation/views/mrp_bom.xml
  mrp_lot_number_propagation/views/mrp_production.xml
  setup/mrp_lot_number_propagation/odoo/addons/mrp_lot_number_propagation
  setup/mrp_lot_number_propagation/setup.py
Labels: approved, bot is merging ⏳
