Repository OCA/manufacture, pull requests merged in 2022-07, with the labels that each got.

#790 [13.0][MIG] product_mrp_info
  product_mrp_info/README.rst
  product_mrp_info/__init__.py
  product_mrp_info/__manifest__.py
  product_mrp_info/i18n/product_mrp_info.pot
  product_mrp_info/models/__init__.py
  product_mrp_info/models/product.py
  product_mrp_info/readme/CONTRIBUTORS.rst
  product_mrp_info/readme/DESCRIPTION.rst
  product_mrp_info/readme/USAGE.rst
  product_mrp_info/static/description/icon.png
  product_mrp_info/static/description/index.html
  product_mrp_info/tests/__init__.py
  product_mrp_info/tests/test_product_mrp_info.py
  product_mrp_info/views/product_views.xml
  setup/product_mrp_info/odoo/addons/product_mrp_info
  setup/product_mrp_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#824 [13.0][FIX] mrp_multi_level_estimate: group_estimate_days smaller than date range.
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#827 [15.0][FIX] mrp_multi_level_estimate: group_estimate_days smaller than date range
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#742 [15.0][FIX] mrp_warehouse_calendar: date_planned_finished calculated with warehouse calendar
  mrp_warehouse_calendar/models/mrp_production.py
  mrp_warehouse_calendar/tests/test_mrp_warehouse_calendar.py
Labels: approved, bot is merging ⏳

#779 [12.0][ADD] mrp_production_filter_lot
  mrp_production_filter_lot/README.rst
  mrp_production_filter_lot/__init__.py
  mrp_production_filter_lot/__manifest__.py
  mrp_production_filter_lot/i18n/it.po
  mrp_production_filter_lot/readme/CONTRIBUTORS.rst
  mrp_production_filter_lot/readme/DESCRIPTION.rst
  mrp_production_filter_lot/readme/USAGE.rst
  mrp_production_filter_lot/static/description/index.html
  mrp_production_filter_lot/wizards/__init__.py
  mrp_production_filter_lot/wizards/mrp_product_produce_line.py
  mrp_production_filter_lot/wizards/mrp_product_produce_views.xml
Labels: approved, ready to merge, bot is merging ⏳
