Repository OCA/manufacture, pull requests merged in 2022-02, with the labels that each got.

#686 [14.0][FIX] repair_refurbish: Change destination location
  repair_refurbish/models/repair.py
  repair_refurbish/tests/test_repair_refurbish.py
Labels: approved, ready to merge, bot is merging ⏳

#744 [15.0][FIX] mrp_progress_button: Fix unstart functionality
  mrp_progress_button/models/mrp_production.py
  mrp_progress_button/views/production.xml
Labels: approved, bot is merging ⏳

#719 [14.0][MIG] mrp_workorder_sequence
  mrp_workorder_sequence/README.rst
  mrp_workorder_sequence/__init__.py
  mrp_workorder_sequence/__manifest__.py
  mrp_workorder_sequence/i18n/mrp_workorder_sequence.pot
  mrp_workorder_sequence/models/__init__.py
  mrp_workorder_sequence/models/mrp_production.py
  mrp_workorder_sequence/models/mrp_workorder.py
  mrp_workorder_sequence/readme/CONTRIBUTORS.rst
  mrp_workorder_sequence/readme/DESCRIPTION.rst
  mrp_workorder_sequence/readme/USAGE.rst
  mrp_workorder_sequence/static/description/icon.png
  mrp_workorder_sequence/static/description/index.html
  mrp_workorder_sequence/views/mrp_workorder_view.xml
  setup/mrp_workorder_sequence/odoo/addons/mrp_workorder_sequence
  setup/mrp_workorder_sequence/setup.py
Labels: approved, bot is merging ⏳

#750 [13.0][FIX] mrp_multi_level_estimate: do not overstate estimates
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#754 [14.0][FIX] mrp_multi_level_estimate: do not overstate estimates
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: needs review, bot is merging ⏳

#740 [14.0][MIG] mrp_production_putaway_strategy
  mrp_production_putaway_strategy/README.rst
  mrp_production_putaway_strategy/__init__.py
  mrp_production_putaway_strategy/__manifest__.py
  mrp_production_putaway_strategy/i18n/de.po
  mrp_production_putaway_strategy/i18n/es.po
  mrp_production_putaway_strategy/i18n/es_MX.po
  mrp_production_putaway_strategy/i18n/fr.po
  mrp_production_putaway_strategy/i18n/gl.po
  mrp_production_putaway_strategy/i18n/hr.po
  mrp_production_putaway_strategy/i18n/it.po
  mrp_production_putaway_strategy/i18n/mrp_production_putaway_strategy.pot
  mrp_production_putaway_strategy/i18n/pt_BR.po
  mrp_production_putaway_strategy/i18n/ro.po
  mrp_production_putaway_strategy/i18n/sl.po
  mrp_production_putaway_strategy/i18n/tr.po
  mrp_production_putaway_strategy/i18n/vi_VN.po
  mrp_production_putaway_strategy/i18n/zh_CN.po
  mrp_production_putaway_strategy/models/__init__.py
  mrp_production_putaway_strategy/models/mrp_production.py
  mrp_production_putaway_strategy/readme/CONFIGURE.rst
  mrp_production_putaway_strategy/readme/CONTRIBUTORS.rst
  mrp_production_putaway_strategy/readme/DESCRIPTION.rst
  mrp_production_putaway_strategy/readme/USAGE.rst
  mrp_production_putaway_strategy/static/description/icon.png
  mrp_production_putaway_strategy/static/description/index.html
  mrp_production_putaway_strategy/tests/__init__.py
  mrp_production_putaway_strategy/tests/test_mrp_production.py
  setup/mrp_production_putaway_strategy/odoo/addons/mrp_production_putaway_strategy
  setup/mrp_production_putaway_strategy/setup.py
Labels: approved, bot is merging ⏳

#758 [15.0][MIG] mrp_planned_order_matrix
  mrp_planned_order_matrix/README.rst
  mrp_planned_order_matrix/__init__.py
  mrp_planned_order_matrix/__manifest__.py
  mrp_planned_order_matrix/i18n/mrp_planned_order_matrix.pot
  mrp_planned_order_matrix/readme/CONTRIBUTORS.rst
  mrp_planned_order_matrix/readme/DESCRIPTION.rst
  mrp_planned_order_matrix/readme/INSTALL.rst
  mrp_planned_order_matrix/readme/USAGE.rst
  mrp_planned_order_matrix/security/ir.model.access.csv
  mrp_planned_order_matrix/static/description/icon.png
  mrp_planned_order_matrix/static/description/index.html
  mrp_planned_order_matrix/tests/__init__.py
  mrp_planned_order_matrix/tests/test_mrp_planned_order_matrix.py
  mrp_planned_order_matrix/wizards/__init__.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
  setup/mrp_planned_order_matrix/odoo/addons/mrp_planned_order_matrix
  setup/mrp_planned_order_matrix/setup.py
Labels: approved, bot is merging ⏳

#745 [14.0][FIX] mrp_multi_level: xmlid argument
  mrp_multi_level/models/product_template.py
Labels: bot is merging ⏳

#761 [15.0][PORT] mrp_multi_level: Get mrp_area company_id for supply method
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#759 [14.0][FIX] mrp_multi_level: Get MRParea company_id for supply method
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#762 [13.0][BACKPORT] mrp_multi_level: Get mrp_area company_id for supply method
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#753 [15.0][IMP] mrp_progress_button: modify test with time
  mrp_progress_button/tests/test_progress_button.py
Labels: approved, bot is merging ⏳

#763 [14.0][FIX] mrp_workorder_sequence: Call method changed on v14
  mrp_workorder_sequence/models/mrp_production.py
Labels: approved, bot is merging ⏳

#755 [15.0][MIG] mrp_multi_level_estimate
  mrp_multi_level_estimate/README.rst
  mrp_multi_level_estimate/__init__.py
  mrp_multi_level_estimate/__manifest__.py
  mrp_multi_level_estimate/i18n/mrp_multi_level_estimate.pot
  mrp_multi_level_estimate/models/__init__.py
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/readme/CONFIGURE.rst
  mrp_multi_level_estimate/readme/CONTRIBUTORS.rst
  mrp_multi_level_estimate/readme/DESCRIPTION.rst
  mrp_multi_level_estimate/static/description/icon.png
  mrp_multi_level_estimate/static/description/index.html
  mrp_multi_level_estimate/tests/__init__.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/views/product_mrp_area_views.xml
  mrp_multi_level_estimate/wizards/__init__.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
  setup/mrp_multi_level_estimate/odoo/addons/mrp_multi_level_estimate
  setup/mrp_multi_level_estimate/setup.py
Labels: bot is merging ⏳
