Repository OCA/manufacture, pull requests merged in 2022-08, with the labels that each got.

#821 [14.0][FIX] mrp_subcontracting_partner
  mrp_subcontracting_partner_management/__manifest__.py
  mrp_subcontracting_partner_management/models/__init__.py
  mrp_subcontracting_partner_management/models/res_partner.py
  mrp_subcontracting_partner_management/models/stock_picking_type.py
  mrp_subcontracting_partner_management/readme/HISTORY.rst
  mrp_subcontracting_partner_management/tests/test_create_sybcontractor_partner_location.py
  mrp_subcontracting_partner_management/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳

#810 [14.0][ADD] mrp_bom_attribute_match
  mrp_bom_attribute_match/README.rst
  mrp_bom_attribute_match/__init__.py
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/i18n/it.po
  mrp_bom_attribute_match/i18n/mrp_bom_attribute_match.pot
  mrp_bom_attribute_match/models/__init__.py
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/models/mrp_production.py
  mrp_bom_attribute_match/models/product.py
  mrp_bom_attribute_match/readme/CONTRIBUTORS.rst
  mrp_bom_attribute_match/readme/DESCRIPTION.rst
  mrp_bom_attribute_match/readme/USAGE.rst
  mrp_bom_attribute_match/tests/__init__.py
  mrp_bom_attribute_match/tests/common.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match.py
  mrp_bom_attribute_match/views/mrp_bom_views.xml
  setup/mrp_bom_attribute_match/odoo/addons/mrp_bom_attribute_match
  setup/mrp_bom_attribute_match/setup.py
Labels: approved, bot is merging ⏳

#836 [14.0][FIX] mrp_subcontracting_partner_management: Fix view in contacts
  mrp_subcontracting_partner_management/views/res_partner.xml
Labels: approved, bot is merging ⏳

#834 [14.0][ADD] mrp_subcontracting_bom_dual_use: New addon.
  mrp_subcontracting_bom_dual_use/README.rst
  mrp_subcontracting_bom_dual_use/__init__.py
  mrp_subcontracting_bom_dual_use/__manifest__.py
  mrp_subcontracting_bom_dual_use/i18n/es.po
  mrp_subcontracting_bom_dual_use/i18n/mrp_subcontracting_bom_dual_use.pot
  mrp_subcontracting_bom_dual_use/models/__init__.py
  mrp_subcontracting_bom_dual_use/models/mrp_bom.py
  mrp_subcontracting_bom_dual_use/models/mrp_production.py
  mrp_subcontracting_bom_dual_use/readme/CONTRIBUTORS.rst
  mrp_subcontracting_bom_dual_use/readme/DESCRIPTION.rst
  mrp_subcontracting_bom_dual_use/readme/USAGE.rst
  mrp_subcontracting_bom_dual_use/static/description/icon.png
  mrp_subcontracting_bom_dual_use/static/description/index.html
  mrp_subcontracting_bom_dual_use/tests/__init__.py
  mrp_subcontracting_bom_dual_use/tests/test_mrp_subcontracting_bom_dual_use.py
  mrp_subcontracting_bom_dual_use/views/mrp_bom_view.xml
  setup/mrp_subcontracting_bom_dual_use/odoo/addons/mrp_subcontracting_bom_dual_use
  setup/mrp_subcontracting_bom_dual_use/setup.py
Labels: approved, bot is merging ⏳

#839 [14.0][IMP] mrp_subcontracting_bom_dual_use: Allow operations in subcontracting BoMs.
  mrp_subcontracting_bom_dual_use/models/mrp_bom.py
  mrp_subcontracting_bom_dual_use/tests/test_mrp_subcontracting_bom_dual_use.py
  mrp_subcontracting_bom_dual_use/views/mrp_bom_view.xml
Labels: approved, bot is merging ⏳

#837 [14.0][ADD] mrp_subcontracting_resupply_link: New module.
  mrp_subcontracting_resupply_link/README.rst
  mrp_subcontracting_resupply_link/__init__.py
  mrp_subcontracting_resupply_link/__manifest__.py
  mrp_subcontracting_resupply_link/i18n/es.po
  mrp_subcontracting_resupply_link/i18n/mrp_subcontracting_resupply_link.pot
  mrp_subcontracting_resupply_link/models/__init__.py
  mrp_subcontracting_resupply_link/models/purchase_order.py
  mrp_subcontracting_resupply_link/models/stock_picking.py
  mrp_subcontracting_resupply_link/readme/CONTRIBUTORS.rst
  mrp_subcontracting_resupply_link/readme/DESCRIPTION.rst
  mrp_subcontracting_resupply_link/readme/USAGE.rst
  mrp_subcontracting_resupply_link/static/description/icon.png
  mrp_subcontracting_resupply_link/static/description/index.html
  mrp_subcontracting_resupply_link/tests/__init__.py
  mrp_subcontracting_resupply_link/tests/test_mrp_subcontracting_resupply_link.py
  mrp_subcontracting_resupply_link/views/purchase_order_view.xml
  mrp_subcontracting_resupply_link/views/stock_picking_view.xml
  setup/mrp_subcontracting_resupply_link/odoo/addons/mrp_subcontracting_resupply_link
  setup/mrp_subcontracting_resupply_link/setup.py
Labels: approved, bot is merging ⏳

#838 [14.0][ADD] mrp_subcontracting_inhibit: New module
  mrp_subcontracting_inhibit/README.rst
  mrp_subcontracting_inhibit/__init__.py
  mrp_subcontracting_inhibit/__manifest__.py
  mrp_subcontracting_inhibit/i18n/es.po
  mrp_subcontracting_inhibit/i18n/mrp_subcontracting_inhibit.pot
  mrp_subcontracting_inhibit/models/__init__.py
  mrp_subcontracting_inhibit/models/product_product.py
  mrp_subcontracting_inhibit/models/product_supplierinfo.py
  mrp_subcontracting_inhibit/models/purchase_order.py
  mrp_subcontracting_inhibit/models/stock_location_route.py
  mrp_subcontracting_inhibit/models/stock_move.py
  mrp_subcontracting_inhibit/readme/CONFIGURE.rst
  mrp_subcontracting_inhibit/readme/CONTRIBUTORS.rst
  mrp_subcontracting_inhibit/readme/DESCRIPTION.rst
  mrp_subcontracting_inhibit/readme/USAGE.rst
  mrp_subcontracting_inhibit/static/description/icon.png
  mrp_subcontracting_inhibit/static/description/index.html
  mrp_subcontracting_inhibit/tests/__init__.py
  mrp_subcontracting_inhibit/tests/test_mrp_subcontracting_inhibit.py
  mrp_subcontracting_inhibit/views/product_supplierinfo_view.xml
  mrp_subcontracting_inhibit/views/stock_location_route_view.xml
  setup/mrp_subcontracting_inhibit/odoo/addons/mrp_subcontracting_inhibit
  setup/mrp_subcontracting_inhibit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#737 [14.0][MIG] quality_control_mrp_oca: Migration to 14.0
  quality_control_mrp_oca/README.rst
  quality_control_mrp_oca/__init__.py
  quality_control_mrp_oca/__manifest__.py
  quality_control_mrp_oca/data/quality_control_mrp_data.xml
  quality_control_mrp_oca/i18n/ca.po
  quality_control_mrp_oca/i18n/de.po
  quality_control_mrp_oca/i18n/el_GR.po
  quality_control_mrp_oca/i18n/es.po
  quality_control_mrp_oca/i18n/es_ES.po
  quality_control_mrp_oca/i18n/es_MX.po
  quality_control_mrp_oca/i18n/eu.po
  quality_control_mrp_oca/i18n/fi.po
  quality_control_mrp_oca/i18n/fr.po
  quality_control_mrp_oca/i18n/fr_CH.po
  quality_control_mrp_oca/i18n/fr_FR.po
  quality_control_mrp_oca/i18n/gl.po
  quality_control_mrp_oca/i18n/hr.po
  quality_control_mrp_oca/i18n/hr_HR.po
  quality_control_mrp_oca/i18n/it.po
  quality_control_mrp_oca/i18n/nl.po
  quality_control_mrp_oca/i18n/nl_NL.po
  quality_control_mrp_oca/i18n/pt.po
  quality_control_mrp_oca/i18n/pt_BR.po
  quality_control_mrp_oca/i18n/quality_control_mrp_oca.pot
  quality_control_mrp_oca/i18n/ro.po
  quality_control_mrp_oca/i18n/ru.po
  quality_control_mrp_oca/i18n/sk.po
  quality_control_mrp_oca/i18n/sl.po
  quality_control_mrp_oca/i18n/tr.po
  quality_control_mrp_oca/i18n/tr_TR.po
  quality_control_mrp_oca/i18n/vi_VN.po
  quality_control_mrp_oca/i18n/zh_CN.po
  quality_control_mrp_oca/models/__init__.py
  quality_control_mrp_oca/models/mrp_production.py
  quality_control_mrp_oca/models/qc_inspection.py
  quality_control_mrp_oca/readme/CONTRIBUTORS.rst
  quality_control_mrp_oca/readme/DESCRIPTION.rst
  quality_control_mrp_oca/static/description/icon.png
  quality_control_mrp_oca/static/description/index.html
  quality_control_mrp_oca/tests/__init__.py
  quality_control_mrp_oca/tests/test_quality_control_mrp.py
  quality_control_mrp_oca/views/mrp_production_view.xml
  quality_control_mrp_oca/views/qc_inspection_view.xml
  setup/quality_control_mrp_oca/odoo/addons/quality_control_mrp_oca
  setup/quality_control_mrp_oca/setup.py
Labels: bot is merging ⏳, stale
