Repository OCA/manufacture, pull requests merged in 2022-09, with the labels that each got.

#785 [13.0][IMP] quality_control_oca: add chatter to quality tests
  quality_control_oca/models/qc_test.py
  quality_control_oca/readme/CONTRIBUTORS.rst
  quality_control_oca/views/qc_test_view.xml
Labels: bot is merging ⏳, stale

#842 [12.0][FIX] mrp_multi_level: Manage Kits in MRP Multi Level
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#841 [14.0][FIX] bom_attribute_match: BOM unit of measure should match uom…
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/views/mrp_bom_views.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#846 [13.0][FIX] mrp_multi_level: Recompute main supplier in MRP Parameter
  mrp_multi_level/models/product_mrp_area.py
Labels: approved, ready to merge, bot is merging ⏳

#849 [MIG] mrp_production_grouped_by_product: Migration to 15.0
  mrp_production_grouped_by_product/README.rst
  mrp_production_grouped_by_product/__init__.py
  mrp_production_grouped_by_product/__manifest__.py
  mrp_production_grouped_by_product/i18n/de.po
  mrp_production_grouped_by_product/i18n/es.po
  mrp_production_grouped_by_product/i18n/mrp_production_grouped_by_product.pot
  mrp_production_grouped_by_product/models/__init__.py
  mrp_production_grouped_by_product/models/mrp_production.py
  mrp_production_grouped_by_product/models/stock_move.py
  mrp_production_grouped_by_product/models/stock_picking_type.py
  mrp_production_grouped_by_product/models/stock_rule.py
  mrp_production_grouped_by_product/readme/CONFIGURE.rst
  mrp_production_grouped_by_product/readme/CONTRIBUTORS.rst
  mrp_production_grouped_by_product/readme/DESCRIPTION.rst
  mrp_production_grouped_by_product/readme/HISTORY.rst
  mrp_production_grouped_by_product/readme/ROADMAP.rst
  mrp_production_grouped_by_product/static/description/icon.png
  mrp_production_grouped_by_product/static/description/index.html
  mrp_production_grouped_by_product/tests/__init__.py
  mrp_production_grouped_by_product/tests/test_mrp_production_grouped_by_product.py
  mrp_production_grouped_by_product/views/stock_picking_type_views.xml
  setup/mrp_production_grouped_by_product/odoo/addons/mrp_production_grouped_by_product
  setup/mrp_production_grouped_by_product/setup.py
Labels: approved, bot is merging ⏳

#853 [13.0][FIX] mrp_multi_level: do not include supplies on origin.
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#855 [14.0][FW-PORT] mrp_multi_level: Recompute main supplier in MRP Parameter and Do not include supplies on origin
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#856 [15.0][FW-PORT] mrp_multi_level: Recompute main supplier in MRP Parameter and Do not include supplies on origin
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#738 [14.0][MIG] stock_whole_kit_constraint: Migration to V14
  setup/stock_whole_kit_constraint/odoo/addons/stock_whole_kit_constraint
  setup/stock_whole_kit_constraint/setup.py
  stock_whole_kit_constraint/README.rst
  stock_whole_kit_constraint/__init__.py
  stock_whole_kit_constraint/__manifest__.py
  stock_whole_kit_constraint/i18n/es.po
  stock_whole_kit_constraint/i18n/stock_whole_kit_constraint.pot
  stock_whole_kit_constraint/models/__init__.py
  stock_whole_kit_constraint/models/product_template.py
  stock_whole_kit_constraint/models/stock_move.py
  stock_whole_kit_constraint/models/stock_picking.py
  stock_whole_kit_constraint/readme/CONFIGURE.rst
  stock_whole_kit_constraint/readme/CONTRIBUTORS.rst
  stock_whole_kit_constraint/readme/DESCRIPTION.rst
  stock_whole_kit_constraint/readme/USAGE.rst
  stock_whole_kit_constraint/static/description/icon.png
  stock_whole_kit_constraint/static/description/index.html
  stock_whole_kit_constraint/tests/__init__.py
  stock_whole_kit_constraint/tests/test_stock_whole_kit_constraint.py
  stock_whole_kit_constraint/views/product_template_views.xml
Labels: bot is merging ⏳, stale

#848 [13.0][FW-PORT] mrp_multi_level: Manage Kits in MRP Multi Level
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#830 [14.0][FIX] repair_type: remove destination location for finished product
  repair_type/models/repair_type.py
  repair_type/tests/test_repair_type.py
  repair_type/views/repair_type.xml
Labels: approved, bot is merging ⏳

#851 [15.0][FW-PORT] mrp_multi_level: Manage Kits in MRP Multi Level
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#850 [14.0][FW-PORT] mrp_multi_level: Manage Kits in MRP Multi Level
  mrp_multi_level/demo/mrp_bom_demo.xml
  mrp_multi_level/demo/product_mrp_area_demo.xml
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/demo/product_supplierinfo_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#858 [13.0][FIX] quality_control_oca: Protect product category view with group
  quality_control_oca/views/product_category_view.xml
Labels: approved, bot is merging ⏳

#860 [14.0][FIX] quality_control_oca: Protect product category view with group
  quality_control_oca/views/product_category_view.xml
Labels: bot is merging ⏳

#857 [13.0][FIX] mrp_multi_level: Descriptive order number in MRP Moves
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#864 [15.0][FIX] mrp_multi_level: Descriptive order number in MRP Moves
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#863 [14.0][FIX] mrp_multi_level: Descriptive order number in MRP Moves
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳
