Repository OCA/manufacture, pull requests merged in 2022-06, with the labels that each got.

#757 [13.0][FIX] mrp_multi_level: Use running on hand quantity in mrp.inventory
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, ready to merge, bot is merging ⏳

#793 [14.0][ADD] Subcontractor Partner Management
  mrp_subcontracting_partner_management/README.rst
  mrp_subcontracting_partner_management/__init__.py
  mrp_subcontracting_partner_management/__manifest__.py
  mrp_subcontracting_partner_management/models/__init__.py
  mrp_subcontracting_partner_management/models/res_partner.py
  mrp_subcontracting_partner_management/readme/CONFIGURE.rst
  mrp_subcontracting_partner_management/readme/CONTRIBUTORS.rst
  mrp_subcontracting_partner_management/readme/DESCRIPTION.rst
  mrp_subcontracting_partner_management/readme/HISTORY.rst
  mrp_subcontracting_partner_management/readme/USAGE.rst
  mrp_subcontracting_partner_management/static/description/icon.png
  mrp_subcontracting_partner_management/tests/__init__.py
  mrp_subcontracting_partner_management/tests/test_create_sybcontractor_partner_location.py
  mrp_subcontracting_partner_management/views/res_partner.xml
  setup/mrp_subcontracting_partner_management/odoo/addons/mrp_subcontracting_partner_management
  setup/mrp_subcontracting_partner_management/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#806 [14.0][IMP] mrp_multi_level: improve traceability
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_move.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#813 [15.0][IMP] mrp_multi_level: add utf8 encoding to xml files
  mrp_bom_tracking/models/mrp_bom.py
  mrp_multi_level/security/mrp_multi_level_security.xml
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_menuitem.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/views/product_product_views.xml
  mrp_multi_level/views/product_template_views.xml
  mrp_multi_level/views/stock_location_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure_views.xml
  mrp_multi_level/wizards/mrp_multi_level_views.xml
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
  mrp_workorder_sequence/tests/test_mrp_workorder_sequence.py
Labels: approved, bot is merging ⏳

#812 [13.0][FIX] mrp_multi_level: add view in manifest
  mrp_multi_level/__manifest__.py
  mrp_multi_level/security/mrp_multi_level_security.xml
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_menuitem.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/views/product_product_views.xml
  mrp_multi_level/views/product_template_views.xml
  mrp_multi_level/views/stock_location_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure_views.xml
  mrp_multi_level/wizards/mrp_multi_level_views.xml
Labels: bot is merging ⏳

#811 [14.0][FIX] mrp_multi_level: add view in manifest
  mrp_bom_tracking/models/mrp_bom.py
  mrp_multi_level/__manifest__.py
  mrp_multi_level/security/mrp_multi_level_security.xml
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_menuitem.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/views/product_product_views.xml
  mrp_multi_level/views/product_template_views.xml
  mrp_multi_level/views/stock_location_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure_views.xml
  mrp_multi_level/wizards/mrp_multi_level_views.xml
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
Labels: bot is merging ⏳

#809 [14.0][ADD] mrp_bom_hierarchy
  mrp_bom_hierarchy/README.rst
  mrp_bom_hierarchy/__init__.py
  mrp_bom_hierarchy/__manifest__.py
  mrp_bom_hierarchy/model/__init__.py
  mrp_bom_hierarchy/model/mrp_bom.py
  mrp_bom_hierarchy/readme/CONTRIBUTORS.rst
  mrp_bom_hierarchy/readme/DESCRIPTION.rst
  mrp_bom_hierarchy/readme/USAGE.rst
  mrp_bom_hierarchy/static/description/icon.png
  mrp_bom_hierarchy/static/description/index.html
  mrp_bom_hierarchy/view/mrp.xml
  setup/mrp_bom_hierarchy/odoo/addons/mrp_bom_hierarchy
  setup/mrp_bom_hierarchy/setup.py
Labels: approved, bot is merging ⏳

#799 [ADD][15.0] Add module of mrp_finished_backorder_product
  mrp_finished_backorder_product/README.rst
  mrp_finished_backorder_product/__init__.py
  mrp_finished_backorder_product/__manifest__.py
  mrp_finished_backorder_product/models/__init__.py
  mrp_finished_backorder_product/models/mrp_production.py
  mrp_finished_backorder_product/readme/CONTRIBUTORS.rst
  mrp_finished_backorder_product/readme/DESCRIPTION.rst
  mrp_finished_backorder_product/views/mrp_production_views.xml
  setup/mrp_finished_backorder_product/odoo/addons/mrp_finished_backorder_product
  setup/mrp_finished_backorder_product/setup.py
Labels: bot is merging ⏳

#776 [14.0][ADD] account_move_line_mrp_info
  account_move_line_mrp_info/README.rst
  account_move_line_mrp_info/__init__.py
  account_move_line_mrp_info/__manifest__.py
  account_move_line_mrp_info/hooks.py
  account_move_line_mrp_info/models/__init__.py
  account_move_line_mrp_info/models/account_move_line.py
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/readme/CONTRIBUTORS.rst
  account_move_line_mrp_info/readme/DESCRIPTION.rst
  account_move_line_mrp_info/readme/USAGE.rst
  account_move_line_mrp_info/security/ir.model.access.csv
  account_move_line_mrp_info/static/description/icon.png
  account_move_line_mrp_info/static/description/index.html
  account_move_line_mrp_info/views/account_move_line_view.xml
  account_move_line_mrp_info/views/mrp_production_view.xml
  setup/account_move_line_mrp_info/odoo/addons/account_move_line_mrp_info
  setup/account_move_line_mrp_info/setup.py
Labels: approved, bot is merging ⏳

#797 [14.0][MIG + IMP]repair_discount
  repair_discount/README.rst
  repair_discount/__init__.py
  repair_discount/__manifest__.py
  repair_discount/i18n/de.po
  repair_discount/i18n/es.po
  repair_discount/i18n/fr.po
  repair_discount/i18n/hr.po
  repair_discount/i18n/hr_HR.po
  repair_discount/i18n/it.po
  repair_discount/i18n/lt.po
  repair_discount/i18n/mrp_repair_discount.pot
  repair_discount/i18n/nl_NL.po
  repair_discount/i18n/pt_BR.po
  repair_discount/i18n/repair_discount.pot
  repair_discount/models/__init__.py
  repair_discount/models/mrp_repair.py
  repair_discount/readme/CONTRIBUTORS.rst
  repair_discount/readme/DESCRIPTION.rst
  repair_discount/report/repair_templates_repair_order.xml
  repair_discount/static/description/icon.png
  repair_discount/static/description/index.html
  repair_discount/tests/__init__.py
  repair_discount/tests/test_mrp_repair_discount.py
  repair_discount/views/mrp_repair_view.xml
  setup/repair_discount/odoo/addons/repair_discount
  setup/repair_discount/setup.py
Labels: approved, bot is merging ⏳

#820 [15.0][FIX] mrp_multi_level: avoid mixing str with boolean (forward port)
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#818 [15.0][MIG] mrp_bom_hierarchy: Migration to 15.0
  mrp_bom_hierarchy/README.rst
  mrp_bom_hierarchy/__init__.py
  mrp_bom_hierarchy/__manifest__.py
  mrp_bom_hierarchy/i18n/mrp_bom_hierarchy.pot
  mrp_bom_hierarchy/model/__init__.py
  mrp_bom_hierarchy/model/mrp_bom.py
  mrp_bom_hierarchy/readme/CONTRIBUTORS.rst
  mrp_bom_hierarchy/readme/DESCRIPTION.rst
  mrp_bom_hierarchy/readme/USAGE.rst
  mrp_bom_hierarchy/static/description/icon.png
  mrp_bom_hierarchy/static/description/index.html
  mrp_bom_hierarchy/view/mrp.xml
  setup/mrp_bom_hierarchy/odoo/addons/mrp_bom_hierarchy
  setup/mrp_bom_hierarchy/setup.py
Labels: approved, bot is merging ⏳
