Repository OCA/manufacture, pull requests merged in 2023-06, with the labels that each got.

#995 [15.0][MIG]mrp_production_serial_matrix:Migration to 15.0
  mrp_production_serial_matrix/README.rst
  mrp_production_serial_matrix/__init__.py
  mrp_production_serial_matrix/__manifest__.py
  mrp_production_serial_matrix/i18n/it.po
  mrp_production_serial_matrix/i18n/mrp_production_serial_matrix.pot
  mrp_production_serial_matrix/models/__init__.py
  mrp_production_serial_matrix/models/mrp_production.py
  mrp_production_serial_matrix/readme/CONTRIBUTORS.rst
  mrp_production_serial_matrix/readme/DESCRIPTION.rst
  mrp_production_serial_matrix/readme/ROADMAP.rst
  mrp_production_serial_matrix/readme/USAGE.rst
  mrp_production_serial_matrix/security/ir.model.access.csv
  mrp_production_serial_matrix/static/description/icon.png
  mrp_production_serial_matrix/static/description/index.html
  mrp_production_serial_matrix/tests/__init__.py
  mrp_production_serial_matrix/tests/test_mrp_production_serial_matrix.py
  mrp_production_serial_matrix/views/mrp_production_views.xml
  mrp_production_serial_matrix/wizards/__init__.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_line.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_view.xml
  setup/mrp_production_serial_matrix/odoo/addons/mrp_production_serial_matrix
  setup/mrp_production_serial_matrix/setup.py
Labels: bot is merging ⏳

#993 [15.0][MIG]stock_picking_product_kit_helper:Migration to 15.0
  setup/stock_picking_product_kit_helper/odoo/addons/stock_picking_product_kit_helper
  setup/stock_picking_product_kit_helper/setup.py
  stock_picking_product_kit_helper/README.rst
  stock_picking_product_kit_helper/__init__.py
  stock_picking_product_kit_helper/__manifest__.py
  stock_picking_product_kit_helper/i18n/it.po
  stock_picking_product_kit_helper/i18n/stock_picking_product_kit_helper.pot
  stock_picking_product_kit_helper/models/__init__.py
  stock_picking_product_kit_helper/models/stock_picking.py
  stock_picking_product_kit_helper/readme/CONTRIBUTORS.rst
  stock_picking_product_kit_helper/readme/DESCRIPTION.rst
  stock_picking_product_kit_helper/readme/HISTORY.rst
  stock_picking_product_kit_helper/readme/USAGE.rst
  stock_picking_product_kit_helper/security/ir.model.access.csv
  stock_picking_product_kit_helper/static/description/icon.png
  stock_picking_product_kit_helper/static/description/icon.svg
  stock_picking_product_kit_helper/static/description/index.html
  stock_picking_product_kit_helper/tests/__init__.py
  stock_picking_product_kit_helper/tests/test_stock_picking_product_kit_helper.py
  stock_picking_product_kit_helper/views/stock_view.xml
Labels: bot is merging ⏳

#925 [15.0][MIG]mrp_account_analytic: Migration to 15.0
  mrp_account_analytic/README.rst
  mrp_account_analytic/__init__.py
  mrp_account_analytic/__manifest__.py
  mrp_account_analytic/i18n/hr.po
  mrp_account_analytic/i18n/it.po
  mrp_account_analytic/i18n/mrp_account_analytic.pot
  mrp_account_analytic/models/__init__.py
  mrp_account_analytic/models/account_analytic_line.py
  mrp_account_analytic/models/mrp_workorder.py
  mrp_account_analytic/models/stock_move.py
  mrp_account_analytic/readme/CONTRIBUTORS.rst
  mrp_account_analytic/readme/DESCRIPTION.rst
  mrp_account_analytic/readme/USAGE.rst
  mrp_account_analytic/static/description/icon.png
  mrp_account_analytic/static/description/index.html
  mrp_account_analytic/tests/__init__.py
  mrp_account_analytic/tests/test_mrp_analytic.py
  mrp_account_analytic/views/account_analytic_line_view.xml
  setup/mrp_account_analytic/odoo/addons/mrp_account_analytic
  setup/mrp_account_analytic/setup.py
Labels: bot is merging ⏳

#936 [16.0][MIG] mrp_bom_location
  mrp_bom_location/README.rst
  mrp_bom_location/__init__.py
  mrp_bom_location/__manifest__.py
  mrp_bom_location/i18n/de.po
  mrp_bom_location/i18n/it.po
  mrp_bom_location/i18n/mrp_bom_location.pot
  mrp_bom_location/models/__init__.py
  mrp_bom_location/models/mrp_bom.py
  mrp_bom_location/readme/CONTRIBUTORS.rst
  mrp_bom_location/readme/DESCRIPTION.rst
  mrp_bom_location/readme/USAGE.rst
  mrp_bom_location/report/__init__.py
  mrp_bom_location/report/bom_structure.py
  mrp_bom_location/static/description/icon.png
  mrp_bom_location/static/description/index.html
  mrp_bom_location/views/mrp_view.xml
  mrp_bom_location/views/report_mrpbomstructure.xml
  setup/mrp_bom_location/odoo/addons/mrp_bom_location
  setup/mrp_bom_location/setup.py
Labels: approved, bot is merging ⏳, stale

#1035 [14.0][BCK][MIG] repair_refurbish_repair_stock_move from 15.0
  repair_refurbish/views/repair_view.xml
  repair_refurbish_repair_stock_move/README.rst
  repair_refurbish_repair_stock_move/__init__.py
  repair_refurbish_repair_stock_move/__manifest__.py
  repair_refurbish_repair_stock_move/models/__init__.py
  repair_refurbish_repair_stock_move/models/repair_order.py
  repair_refurbish_repair_stock_move/readme/CONTRIBUTORS.rst
  repair_refurbish_repair_stock_move/readme/DESCRIPTION.rst
  repair_refurbish_repair_stock_move/static/description/index.html
  repair_stock_move/models/repair_order.py
  setup/repair_refurbish_repair_stock_move/odoo/addons/repair_refurbish_repair_stock_move
  setup/repair_refurbish_repair_stock_move/setup.py
Labels: approved, bot is merging ⏳

#890 [16.0][MIG] mrp_production_quant_manual_assign
  mrp_production_quant_manual_assign/README.rst
  mrp_production_quant_manual_assign/__init__.py
  mrp_production_quant_manual_assign/__manifest__.py
  mrp_production_quant_manual_assign/i18n/mrp_production_quant_manual_assign.pot
  mrp_production_quant_manual_assign/i18n/pt_BR.po
  mrp_production_quant_manual_assign/models/__init__.py
  mrp_production_quant_manual_assign/models/stock_move.py
  mrp_production_quant_manual_assign/readme/CONTRIBUTORS.rst
  mrp_production_quant_manual_assign/readme/DESCRIPTION.rst
  mrp_production_quant_manual_assign/readme/USAGE.rst
  mrp_production_quant_manual_assign/static/description/icon.png
  mrp_production_quant_manual_assign/static/description/index.html
  mrp_production_quant_manual_assign/views/mrp_production_views.xml
  mrp_production_quant_manual_assign/wizards/__init__.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants_view.xml
  setup/mrp_production_quant_manual_assign/odoo/addons/mrp_production_quant_manual_assign
  setup/mrp_production_quant_manual_assign/setup.py
Labels: approved, bot is merging ⏳

#1045 [14.0][FIX] mrp_bom_attribute_match: avoid recursion in BOM.
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#904 [16][MIG] mrp_restrict_lot
  mrp_restrict_lot/README.rst
  mrp_restrict_lot/__init__.py
  mrp_restrict_lot/__manifest__.py
  mrp_restrict_lot/i18n/mrp_restrict_lot.pot
  mrp_restrict_lot/models/__init__.py
  mrp_restrict_lot/models/stock_rule.py
  mrp_restrict_lot/readme/CONTRIBUTORS.rst
  mrp_restrict_lot/readme/DESCRIPTION.rst
  mrp_restrict_lot/readme/USAGE.rst
  mrp_restrict_lot/static/description/icon.png
  mrp_restrict_lot/static/description/index.html
  mrp_restrict_lot/tests/__init__.py
  mrp_restrict_lot/tests/test_manufaturing_lot.py
  setup/mrp_restrict_lot/odoo/addons/mrp_restrict_lot
  setup/mrp_restrict_lot/setup.py
Labels: approved, bot is merging ⏳
