Repository OCA/manufacture, pull requests merged in 2023-02, with the labels that each got.

#956 [14.0][IMP] mrp_multi_level: Add MRP Planner
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#854 [14.0][IMP] mrp_subcontracting_inhibit: Add tests to check the behaviour of subcontracting_inhibit
  mrp_subcontracting_inhibit/tests/test_mrp_subcontracting_inhibit.py
Labels: approved, bot is merging ⏳, stale

#963 [16.0][IMP] mrp_multi_level: Add MRP Planner
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
Labels: bot is merging ⏳

#962 [15.0][IMP] mrp_multi_level: Add MRP Planner
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
Labels: approved, bot is merging ⏳

#954 [15.0][IMP] mrp_multi_level: better group operators
  mrp_multi_level/models/mrp_inventory.py
Labels: bot is merging ⏳

#971 [14.0][IMP] mrp_multi_level: better group operators
  mrp_multi_level/models/mrp_inventory.py
Labels: bot is merging ⏳

#970 [13.0][IMP] mrp_multi_level: Add MRP Planner
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
Labels: bot is merging ⏳

#973 [13.0][IMP] mrp_multi_level: better group operators
  mrp_multi_level/models/mrp_inventory.py
Labels: bot is merging ⏳

#958 [15.0] [FIX] `mrp_bom_attribute_match`: structure and cost report
  mrp_account_bom_attribute_match/README.rst
  mrp_account_bom_attribute_match/__init__.py
  mrp_account_bom_attribute_match/__manifest__.py
  mrp_account_bom_attribute_match/models/__init__.py
  mrp_account_bom_attribute_match/models/product_product.py
  mrp_account_bom_attribute_match/tests/__init__.py
  mrp_account_bom_attribute_match/tests/test_mrp_account_bom_attribute_match.py
  mrp_bom_attribute_match/__init__.py
  mrp_bom_attribute_match/reports/__init__.py
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
  mrp_bom_attribute_match/tests/common.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match.py
  setup/mrp_account_bom_attribute_match/odoo/addons/mrp_account_bom_attribute_match
  setup/mrp_account_bom_attribute_match/setup.py
Labels: approved, bot is merging ⏳

#950 [14.0][IMP] mrp_bom_component_menu: import, create, delete, edit MRP BOM lines
  mrp_bom_component_menu/views/mrp_bom_component_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#817 [14.0][PORT] mrp_bom_responsible: 675 from 12.0
  mrp_bom_responsible/README.rst
  mrp_bom_responsible/__init__.py
  mrp_bom_responsible/__manifest__.py
  mrp_bom_responsible/models/__init__.py
  mrp_bom_responsible/models/mrp_bom.py
  mrp_bom_responsible/models/mrp_production.py
  mrp_bom_responsible/readme/CONTRIBUTORS.rst
  mrp_bom_responsible/readme/DESCRIPTION.rst
  mrp_bom_responsible/static/description/icon.png
  mrp_bom_responsible/static/description/index.html
  mrp_bom_responsible/views/mrp_bom_views.xml
  setup/mrp_bom_responsible/odoo/addons/mrp_bom_responsible
  setup/mrp_bom_responsible/setup.py
Labels: approved, bot is merging ⏳, stale

#983 [15.0] [FIX] mrp_account_bom_attribute_match: missing readme
  mrp_account_bom_attribute_match/README.rst
  mrp_account_bom_attribute_match/readme/CONTRIBUTORS.rst
  mrp_account_bom_attribute_match/readme/DESCRIPTION.rst
  mrp_account_bom_attribute_match/static/description/index.html
Labels: bot is merging ⏳

#833 [ADD] repair_picking_after_done : Transfer repaired move to another location directly from repair order
  repair_picking_after_done/README.rst
  repair_picking_after_done/__init__.py
  repair_picking_after_done/__manifest__.py
  repair_picking_after_done/models/__init__.py
  repair_picking_after_done/models/repair.py
  repair_picking_after_done/readme/CONFIGURE.rst
  repair_picking_after_done/readme/CONTRIBUTORS.rst
  repair_picking_after_done/readme/DESCRIPTION.rst
  repair_picking_after_done/readme/ROADMAP.rst
  repair_picking_after_done/readme/USAGE.rst
  repair_picking_after_done/security/ir.model.access.csv
  repair_picking_after_done/static/description/icon.png
  repair_picking_after_done/static/description/index.html
  repair_picking_after_done/tests/__init__.py
  repair_picking_after_done/tests/test_repair_transfers.py
  repair_picking_after_done/views/repair.xml
  repair_picking_after_done/wizards/__init__.py
  repair_picking_after_done/wizards/repair_move_transfer.py
  repair_picking_after_done/wizards/repair_move_transfer_views.xml
  setup/repair_picking_after_done/odoo/addons/repair_picking_after_done
  setup/repair_picking_after_done/setup.py
Labels: approved, bot is merging ⏳, stale

#927 [14.0][ADD] mrp_component_operation_scrap_reason
  mrp_component_operation_scrap_reason/README.rst
  mrp_component_operation_scrap_reason/__init__.py
  mrp_component_operation_scrap_reason/__manifest__.py
  mrp_component_operation_scrap_reason/readme/CONTRIBUTORS.rst
  mrp_component_operation_scrap_reason/readme/DESCRIPTION.rst
  mrp_component_operation_scrap_reason/wizards/__init__.py
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate.py
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate_wizard.xml
  setup/mrp_component_operation_scrap_reason/odoo/addons/mrp_component_operation_scrap_reason
  setup/mrp_component_operation_scrap_reason/setup.py
Labels: approved, bot is merging ⏳

#984 [14.0][FIX] mrp_component_operation: fix test and small issues
  mrp_component_operation/tests/test_component_operate.py
  mrp_component_operation/wizards/mrp_component_operate.py
Labels: approved, bot is merging ⏳

#968 [14.0][FIX] repair_stock_move: fix state in repair lines
  repair_stock_move/models/repair_order.py
  repair_stock_move/tests/test_repair_stock_move.py
Labels: approved, bot is merging ⏳

#967 [14.0][IMP] mrp_multi_level: Supply method computation for MRP Parameters
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: approved, ready to merge, bot is merging ⏳

#987 [REF] pre-commit: copier update, fix pre-commit
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: needs review

#990 [13.0][IMP] mrp_multi_level: Supply method computation for MRP Parameters
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳
