Repository OCA/manufacture, pull requests merged in 2023-03, with the labels that each got.

#985 [14.0][FIX] mrp_subcontracting_purchase_link: link to PO line, not PO
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/migrations/14.0.2.0.0/post-migration.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#949 [15.0] [ADD] `mrp_production_split`
  mrp_production_split/README.rst
  mrp_production_split/__init__.py
  mrp_production_split/__manifest__.py
  mrp_production_split/models/__init__.py
  mrp_production_split/models/mrp_production.py
  mrp_production_split/readme/CONTRIBUTORS.rst
  mrp_production_split/readme/DESCRIPTION.rst
  mrp_production_split/readme/USAGE.rst
  mrp_production_split/security/ir.model.access.csv
  mrp_production_split/templates/messages.xml
  mrp_production_split/tests/__init__.py
  mrp_production_split/tests/common.py
  mrp_production_split/tests/test_mrp_production_split.py
  mrp_production_split/views/mrp_production.xml
  mrp_production_split/wizards/__init__.py
  mrp_production_split/wizards/mrp_production_split_wizard.py
  mrp_production_split/wizards/mrp_production_split_wizard.xml
  setup/mrp_production_split/odoo/addons/mrp_production_split
  setup/mrp_production_split/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#989 [16.0][IMP] mrp_multi_level: Supply method computation for MRP Parameters
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#988 [15.0][IMP] mrp_multi_level: Supply method computation for MRP Parameters
  mrp_multi_level/demo/product_product_demo.xml
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#1004 [15.0] mrp_lot_number_propagation: Add hook to get propagating component
  mrp_lot_number_propagation/models/mrp_production.py
Labels: bot is merging ⏳

#931 [15.0][IMP] mrp_lot_number_propagation: Propagate from multiple lines
  mrp_lot_number_propagation/models/mrp_bom_line.py
  mrp_lot_number_propagation/models/mrp_production.py
  mrp_lot_number_propagation/tests/common.py
  mrp_lot_number_propagation/tests/test_mrp_bom.py
  mrp_lot_number_propagation/tests/test_mrp_production.py
Labels: approved, bot is merging ⏳

#915 [16][MIG] mrp_bom_component_menu
  mrp_bom_component_menu/README.rst
  mrp_bom_component_menu/__init__.py
  mrp_bom_component_menu/__manifest__.py
  mrp_bom_component_menu/i18n/de.po
  mrp_bom_component_menu/i18n/mrp_bom_component_menu.pot
  mrp_bom_component_menu/i18n/zh_CN.po
  mrp_bom_component_menu/readme/CONTRIBUTORS.rst
  mrp_bom_component_menu/readme/DESCRIPTION.rst
  mrp_bom_component_menu/readme/USAGE.rst
  mrp_bom_component_menu/static/description/icon.png
  mrp_bom_component_menu/static/description/index.html
  mrp_bom_component_menu/views/mrp_bom_component_view.xml
  setup/mrp_bom_component_menu/odoo/addons/mrp_bom_component_menu
  setup/mrp_bom_component_menu/setup.py
Labels: approved, bot is merging ⏳

#1007 [14.0][REF+IMP] mrp_attachment_mgmt: Cleanup + button in production orders
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/models/__init__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/models/mrp_production.py
  mrp_attachment_mgmt/models/mrp_workorder.py
  mrp_attachment_mgmt/models/product.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
  mrp_attachment_mgmt/views/mrp_production_views.xml
Labels: approved, bot is merging ⏳
