Repository OCA/manufacture, pull requests merged in 2023-05, with the labels that each got.

#1023 [14.0][IMP] mrp_multi_level: Add mrp_move tree view
  mrp_multi_level/views/mrp_move_views.xml
Labels: bot is merging ⏳, Pending to fw/back port

#1031 [14.0][UPD] repair_stock_move: update status
  repair_stock_move/__manifest__.py
Labels: approved, bot is merging ⏳

#1034 [16.0][IMP] mrp_multi_level: Add mrp_move tree view
  mrp_multi_level/views/mrp_move_views.xml
Labels: bot is merging ⏳

#1033 [15.0][IMP] mrp_multi_level: Add mrp_move tree view
  mrp_multi_level/views/mrp_move_views.xml
Labels: bot is merging ⏳

#1032 [13.0][IMP] mrp_multi_level: Add mrp_move tree view
  mrp_multi_level/views/mrp_move_views.xml
Labels: bot is merging ⏳

#1036 [14.0][FIX] mrp_attachment_mgmt: Change to the correct inherit view
  mrp_attachment_mgmt/views/product_views.xml
Labels: bot is merging ⏳

#722 [14.0][ADD] mrp_routing
  mrp_routing/README.rst
  mrp_routing/__init__.py
  mrp_routing/__manifest__.py
  mrp_routing/data/sequence_data.xml
  mrp_routing/demo/routing_data.xml
  mrp_routing/i18n/mrp_routing.pot
  mrp_routing/models/__init__.py
  mrp_routing/models/mrp_bom.py
  mrp_routing/models/mrp_routing.py
  mrp_routing/models/mrp_routing_workcenter.py
  mrp_routing/models/mrp_routing_workcenter_template.py
  mrp_routing/readme/CONTRIBUTORS.rst
  mrp_routing/readme/DESCRIPTION.rst
  mrp_routing/readme/USAGE.rst
  mrp_routing/security/ir.model.access.csv
  mrp_routing/static/description/icon.png
  mrp_routing/static/description/index.html
  mrp_routing/tests/__init__.py
  mrp_routing/tests/test_manufacturing_routing.py
  mrp_routing/views/mrp_bom_view.xml
  mrp_routing/views/mrp_routing_view.xml
  mrp_routing/views/mrp_routing_workcenter_template_view.xml
  mrp_routing/views/mrp_routing_workcenter_view.xml
  setup/mrp_routing/odoo/addons/mrp_routing
  setup/mrp_routing/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1039 [14.0][FIX] mrp_component_operation_scrap_reason: incorrect key in manifest
  mrp_component_operation_scrap_reason/__manifest__.py
Labels: bot is merging ⏳

#1041 [16][mrp_sale_info] Allow new fields to be shown or hidden by user
  mrp_sale_info/views/mrp_production.xml
Labels: approved, bot is merging ⏳

#1008 [14.0][ADD] mrp_production_picking_type_from_route
  mrp_production_picking_type_from_route/README.rst
  mrp_production_picking_type_from_route/__init__.py
  mrp_production_picking_type_from_route/__manifest__.py
  mrp_production_picking_type_from_route/models/__init__.py
  mrp_production_picking_type_from_route/models/mrp_production.py
  mrp_production_picking_type_from_route/readme/CONTRIBUTORS.rst
  mrp_production_picking_type_from_route/readme/DESCRIPTION.rst
  mrp_production_picking_type_from_route/readme/USAGE.rst
  mrp_production_picking_type_from_route/static/description/index.html
  mrp_production_picking_type_from_route/tests/__init__.py
  mrp_production_picking_type_from_route/tests/test_mrp_production_picking_type_from_route.py
  setup/mrp_production_picking_type_from_route/odoo/addons/mrp_production_picking_type_from_route
  setup/mrp_production_picking_type_from_route/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1040 [14.0][IMP] mrp_component_operation_scrap_reason: filter allowed scrap reason codes
  mrp_component_operation_scrap_reason/readme/CONTRIBUTORS.rst
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate.py
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate_wizard.xml
Labels: approved, bot is merging ⏳

#1043 [14.0][IMP] mrp_component_operation: enhance extensibility of scrap vals
  mrp_component_operation/readme/CONTRIBUTORS.rst
  mrp_component_operation/wizards/mrp_component_operate.py
Labels: bot is merging ⏳
