Repository OCA/manufacture, pull requests merged in 2023-11, with the labels that each got.

#1116 [14.0][ADD] mrp_subcontracting_purchase_partner_management
  mrp_subcontracting_purchase_partner_management/README.rst
  mrp_subcontracting_purchase_partner_management/__init__.py
  mrp_subcontracting_purchase_partner_management/__manifest__.py
  mrp_subcontracting_purchase_partner_management/models/__init__.py
  mrp_subcontracting_purchase_partner_management/models/res_partner.py
  mrp_subcontracting_purchase_partner_management/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_partner_management/readme/USAGE.rst
  mrp_subcontracting_purchase_partner_management/tests/__init__.py
  mrp_subcontracting_purchase_partner_management/tests/test_create_subcontractor_partner_location.py
  setup/mrp_subcontracting_purchase_partner_management/odoo/addons/mrp_subcontracting_purchase_partner_management
  setup/mrp_subcontracting_purchase_partner_management/setup.py
Labels: approved, bot is merging ⏳

#1128 [15.0] mrp_account_analytic: Fix processing workorder without analytic
  mrp_account_analytic/models/mrp_workorder.py
  mrp_account_analytic/models/stock_move.py
  mrp_account_analytic/tests/test_mrp_analytic.py
Labels: approved, bot is merging ⏳

#922 [15.0][ADD] Create module mrp_production_operation_injection
  mrp_production_operation_injection/README.rst
  mrp_production_operation_injection/__init__.py
  mrp_production_operation_injection/__manifest__.py
  mrp_production_operation_injection/models/__init__.py
  mrp_production_operation_injection/models/mrp_production.py
  mrp_production_operation_injection/models/mrp_workorder.py
  mrp_production_operation_injection/readme/CONTRIBUTORS.rst
  mrp_production_operation_injection/readme/DESCRIPTION.rst
  mrp_production_operation_injection/security/ir.model.access.csv
  mrp_production_operation_injection/tests/__init__.py
  mrp_production_operation_injection/tests/test_mrp_production_inject_operation.py
  mrp_production_operation_injection/views/mrp_production.xml
  mrp_production_operation_injection/views/mrp_workorder.xml
  mrp_production_operation_injection/wizard/__init__.py
  mrp_production_operation_injection/wizard/mrp_workorder_injector.py
  mrp_production_operation_injection/wizard/mrp_workorder_injector.xml
  setup/mrp_production_operation_injection/odoo/addons/mrp_production_operation_injection
  setup/mrp_production_operation_injection/setup.py
Labels: approved, bot is merging ⏳, no stale

#966 [15.0] Create module mrp_workorder_lock_planning
  mrp_workorder_lock_planning/README.rst
  mrp_workorder_lock_planning/__init__.py
  mrp_workorder_lock_planning/__manifest__.py
  mrp_workorder_lock_planning/models/__init__.py
  mrp_workorder_lock_planning/models/mrp_workorder.py
  mrp_workorder_lock_planning/readme/CONTRIBUTORS.rst
  mrp_workorder_lock_planning/readme/DESCRIPTION.rst
  mrp_workorder_lock_planning/tests/__init__.py
  mrp_workorder_lock_planning/tests/test_mrp_workorder_lock_date_planned.py
  mrp_workorder_lock_planning/views/mrp_workorder.xml
  setup/mrp_workorder_lock_planning/odoo/addons/mrp_workorder_lock_planning
  setup/mrp_workorder_lock_planning/setup.py
Labels: approved, bot is merging ⏳, no stale

#1097 [16.0][MIG] mrp_subcontracting_inhibit: Migration to 16.0
  mrp_subcontracting_inhibit/README.rst
  mrp_subcontracting_inhibit/__init__.py
  mrp_subcontracting_inhibit/__manifest__.py
  mrp_subcontracting_inhibit/i18n/es.po
  mrp_subcontracting_inhibit/i18n/it.po
  mrp_subcontracting_inhibit/i18n/mrp_subcontracting_inhibit.pot
  mrp_subcontracting_inhibit/models/__init__.py
  mrp_subcontracting_inhibit/models/product_product.py
  mrp_subcontracting_inhibit/models/product_supplierinfo.py
  mrp_subcontracting_inhibit/models/purchase_order.py
  mrp_subcontracting_inhibit/models/stock_location_route.py
  mrp_subcontracting_inhibit/models/stock_move.py
  mrp_subcontracting_inhibit/readme/CONFIGURE.rst
  mrp_subcontracting_inhibit/readme/CONTRIBUTORS.rst
  mrp_subcontracting_inhibit/readme/DESCRIPTION.rst
  mrp_subcontracting_inhibit/readme/USAGE.rst
  mrp_subcontracting_inhibit/static/description/icon.png
  mrp_subcontracting_inhibit/static/description/index.html
  mrp_subcontracting_inhibit/tests/__init__.py
  mrp_subcontracting_inhibit/tests/test_mrp_subcontracting_inhibit.py
  mrp_subcontracting_inhibit/views/product_supplierinfo_view.xml
  mrp_subcontracting_inhibit/views/purchase_order_view.xml
  mrp_subcontracting_inhibit/views/stock_location_route_view.xml
  setup/mrp_subcontracting_inhibit/odoo/addons/mrp_subcontracting_inhibit
  setup/mrp_subcontracting_inhibit/setup.py
Labels: bot is merging ⏳

#898 [16.0][MIG] mrp_planned_order_matrix
  mrp_planned_order_matrix/README.rst
  mrp_planned_order_matrix/__init__.py
  mrp_planned_order_matrix/__manifest__.py
  mrp_planned_order_matrix/i18n/mrp_planned_order_matrix.pot
  mrp_planned_order_matrix/readme/CONTRIBUTORS.rst
  mrp_planned_order_matrix/readme/DESCRIPTION.rst
  mrp_planned_order_matrix/readme/INSTALL.rst
  mrp_planned_order_matrix/readme/USAGE.rst
  mrp_planned_order_matrix/security/ir.model.access.csv
  mrp_planned_order_matrix/static/description/icon.png
  mrp_planned_order_matrix/static/description/index.html
  mrp_planned_order_matrix/tests/__init__.py
  mrp_planned_order_matrix/tests/test_mrp_planned_order_matrix.py
  mrp_planned_order_matrix/wizards/__init__.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
  setup/mrp_planned_order_matrix/odoo/addons/mrp_planned_order_matrix
  setup/mrp_planned_order_matrix/setup.py
Labels: bot is merging ⏳, stale

#920 [REF] Fix broken website links
  mrp_production_filter_lot/__manifest__.py
  quality_control_mrp/__manifest__.py
  quality_control_stock/__manifest__.py
Labels: bot is merging ⏳

#957 [15.0] [ADD] `mrp_workcenter_category`
  mrp_workcenter_category/README.rst
  mrp_workcenter_category/__init__.py
  mrp_workcenter_category/__manifest__.py
  mrp_workcenter_category/demo/mrp_workcenter_category.xml
  mrp_workcenter_category/models/__init__.py
  mrp_workcenter_category/models/mrp_workcenter.py
  mrp_workcenter_category/models/mrp_workcenter_category.py
  mrp_workcenter_category/readme/CONTRIBUTORS.rst
  mrp_workcenter_category/readme/DESCRIPTION.rst
  mrp_workcenter_category/security/ir.model.access.csv
  mrp_workcenter_category/tests/__init__.py
  mrp_workcenter_category/tests/test_mrp_workcenter_category.py
  mrp_workcenter_category/views/mrp_workcenter.xml
  mrp_workcenter_category/views/mrp_workcenter_category.xml
  setup/mrp_workcenter_category/odoo/addons/mrp_workcenter_category
  setup/mrp_workcenter_category/setup.py
Labels: approved, bot is merging ⏳, no stale

#798 [12.0][ADD] Sections and Notes on BoM
  mrp_bom_widget_section_and_note_one2many/README.rst
  mrp_bom_widget_section_and_note_one2many/__init__.py
  mrp_bom_widget_section_and_note_one2many/__manifest__.py
  mrp_bom_widget_section_and_note_one2many/i18n/fr.po
  mrp_bom_widget_section_and_note_one2many/models/__init__.py
  mrp_bom_widget_section_and_note_one2many/models/mrp_bom.py
  mrp_bom_widget_section_and_note_one2many/models/mrp_bom_line.py
  mrp_bom_widget_section_and_note_one2many/readme/CONTRIBUTORS.rst
  mrp_bom_widget_section_and_note_one2many/readme/CREDITS.rst
  mrp_bom_widget_section_and_note_one2many/readme/DESCRIPTION.rst
  mrp_bom_widget_section_and_note_one2many/readme/ROADMAP.rst
  mrp_bom_widget_section_and_note_one2many/readme/USAGE.rst
  mrp_bom_widget_section_and_note_one2many/static/description/index.html
  mrp_bom_widget_section_and_note_one2many/static/description/mrp_bom_widget_add_section_and_note.gif
  mrp_bom_widget_section_and_note_one2many/views/view_mrp_bom.xml
  setup/mrp_bom_widget_section_and_note_one2many/odoo/addons/mrp_bom_widget_section_and_note_one2many
  setup/mrp_bom_widget_section_and_note_one2many/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1001 [16.0][MIG] mrp_subcontracting_purchase_link: Migration to 16.0
  mrp_subcontracting_purchase_link/README.rst
  mrp_subcontracting_purchase_link/__init__.py
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/hooks.py
  mrp_subcontracting_purchase_link/i18n/it.po
  mrp_subcontracting_purchase_link/i18n/ja.po
  mrp_subcontracting_purchase_link/i18n/mrp_subcontracting_purchase_link.pot
  mrp_subcontracting_purchase_link/migrations/14.0.2.0.0/post-migration.py
  mrp_subcontracting_purchase_link/models/__init__.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/readme/CONTRIBUTORS.rst
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_link/static/description/icon.png
  mrp_subcontracting_purchase_link/static/description/index.html
  mrp_subcontracting_purchase_link/tests/__init__.py
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
  mrp_subcontracting_purchase_link/views/purchase_order_views.xml
  setup/mrp_subcontracting_purchase_link/odoo/addons/mrp_subcontracting_purchase_link
  setup/mrp_subcontracting_purchase_link/setup.py
Labels: approved, bot is merging ⏳

#1009 [14.0][FIX] mrp_sale_info add link between sale order line and mrp production
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/sale_order_line.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/tests/test_mrp_sale_info.py
Labels: approved, bot is merging ⏳

#1025 [16.0][ADD] mrp_subcontracting_skip_no_negative
  mrp_subcontracting_skip_no_negative/README.rst
  mrp_subcontracting_skip_no_negative/__init__.py
  mrp_subcontracting_skip_no_negative/__manifest__.py
  mrp_subcontracting_skip_no_negative/models/__init__.py
  mrp_subcontracting_skip_no_negative/models/stock_move.py
  mrp_subcontracting_skip_no_negative/models/stock_picking.py
  mrp_subcontracting_skip_no_negative/readme/CONTRIBUTORS.rst
  mrp_subcontracting_skip_no_negative/readme/DESCRIPTION.rst
  mrp_subcontracting_skip_no_negative/static/description/icon.png
  mrp_subcontracting_skip_no_negative/static/description/index.html
  mrp_subcontracting_skip_no_negative/tests/__init__.py
  mrp_subcontracting_skip_no_negative/tests/test_mrp_subcontracting_skip_no_negative.py
  setup/mrp_subcontracting_skip_no_negative/odoo/addons/mrp_subcontracting_skip_no_negative
  setup/mrp_subcontracting_skip_no_negative/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1042 [14.0][IMP] mrp_multi_level_estimate: Stock moves from MO should always be considered
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1129 [14.0][IMP] mrp_subcontracting_purchase_partner_management: add description
  mrp_subcontracting_purchase_partner_management/README.rst
  mrp_subcontracting_purchase_partner_management/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_partner_management/readme/USAGE.rst
  mrp_subcontracting_purchase_partner_management/static/description/index.html
Labels: bot is merging ⏳

#951 [14.0][ADD] mrp_production_byproduct_cost_share
  mrp_production_byproduct_cost_share/__init__.py
  mrp_production_byproduct_cost_share/__manifest__.py
  mrp_production_byproduct_cost_share/models/__init__.py
  mrp_production_byproduct_cost_share/models/mrp_bom.py
  mrp_production_byproduct_cost_share/models/mrp_production.py
  mrp_production_byproduct_cost_share/models/product.py
  mrp_production_byproduct_cost_share/models/stock_move.py
  mrp_production_byproduct_cost_share/readme/CONFIGURE.rst
  mrp_production_byproduct_cost_share/readme/CONTRIBUTORS.rst
  mrp_production_byproduct_cost_share/readme/DESCRIPTION.rst
  mrp_production_byproduct_cost_share/readme/HISTORY.rst
  mrp_production_byproduct_cost_share/readme/ROADMAP.rst
  mrp_production_byproduct_cost_share/report/__init__.py
  mrp_production_byproduct_cost_share/report/mrp_report_bom_structure.py
  mrp_production_byproduct_cost_share/report/mrp_report_bom_structure.xml
  mrp_production_byproduct_cost_share/static/description/icon.png
  mrp_production_byproduct_cost_share/static/description/index.html
  mrp_production_byproduct_cost_share/static/src/js/mrp_bom_report.js
  mrp_production_byproduct_cost_share/tests/__init__.py
  mrp_production_byproduct_cost_share/tests/test_mrp_production_byproduct_cost_share.py
  mrp_production_byproduct_cost_share/views/mrp_bom_views.xml
  mrp_production_byproduct_cost_share/views/mrp_production_views.xml
  mrp_production_byproduct_cost_share/views/mrp_template.xml
  setup/mrp_production_byproduct_cost_share/odoo/addons/mrp_production_byproduct_cost_share
  setup/mrp_production_byproduct_cost_share/setup.py
Labels: approved, bot is merging ⏳

#1130 [15.0][IMP] mrp_multi_level: access action
  mrp_multi_level/models/product_product.py
  mrp_multi_level/models/product_template.py
Labels: approved, bot is merging ⏳

#1133 [16.0][IMP] mrp_multi_level: access action
  mrp_multi_level/models/product_product.py
  mrp_multi_level/models/product_template.py
Labels: bot is merging ⏳

#1061 [16.0][MIG] account_move_line_mrp_info
  account_move_line_mrp_info/README.rst
  account_move_line_mrp_info/__init__.py
  account_move_line_mrp_info/__manifest__.py
  account_move_line_mrp_info/hooks.py
  account_move_line_mrp_info/i18n/account_move_line_mrp_info.pot
  account_move_line_mrp_info/i18n/it.po
  account_move_line_mrp_info/models/__init__.py
  account_move_line_mrp_info/models/account_move_line.py
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/readme/CONTRIBUTORS.rst
  account_move_line_mrp_info/readme/DESCRIPTION.rst
  account_move_line_mrp_info/readme/USAGE.rst
  account_move_line_mrp_info/security/ir.model.access.csv
  account_move_line_mrp_info/static/description/icon.png
  account_move_line_mrp_info/static/description/index.html
  account_move_line_mrp_info/tests/__init__.py
  account_move_line_mrp_info/tests/test_mrp_journal_items.py
  account_move_line_mrp_info/views/account_move_line_view.xml
  account_move_line_mrp_info/views/mrp_production_view.xml
  setup/account_move_line_mrp_info/odoo/addons/account_move_line_mrp_info
  setup/account_move_line_mrp_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1010 [14.0][FIX] mrp_restrict_lot avoid duplicate mo name in case of cancellation qty changes ...
  mrp_restrict_lot/models/stock_rule.py
  mrp_restrict_lot/tests/test_manufaturing_lot.py
Labels: approved, bot is merging ⏳, stale

#934 [14.0][ADD] mrp_lot_production_date
  mrp_lot_production_date/README.rst
  mrp_lot_production_date/__init__.py
  mrp_lot_production_date/__manifest__.py
  mrp_lot_production_date/models/__init__.py
  mrp_lot_production_date/models/mrp_production.py
  mrp_lot_production_date/readme/CONTRIBUTORS.rst
  mrp_lot_production_date/readme/CREDITS.rst
  mrp_lot_production_date/readme/DESCRIPTION.rst
  mrp_lot_production_date/readme/USAGE.rst
  mrp_lot_production_date/static/description/index.html
  mrp_lot_production_date/tests/__init__.py
  mrp_lot_production_date/tests/test_production_date.py
  setup/mrp_lot_production_date/odoo/addons/mrp_lot_production_date
  setup/mrp_lot_production_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1132 [14.0][FIX] quality_control_oca - call super with correct vals
  quality_control_oca/models/qc_inspection.py
Labels: approved, ready to merge, bot is merging ⏳

#1073 [16.0][MIG] mrp_unbuild_move_link: Migration to 16.0
  mrp_unbuild_move_link/README.rst
  mrp_unbuild_move_link/__init__.py
  mrp_unbuild_move_link/__manifest__.py
  mrp_unbuild_move_link/i18n/it.po
  mrp_unbuild_move_link/i18n/mrp_unbuild_move_link.pot
  mrp_unbuild_move_link/models/__init__.py
  mrp_unbuild_move_link/models/mrp_unbuild.py
  mrp_unbuild_move_link/models/stock_move.py
  mrp_unbuild_move_link/readme/CONTRIBUTORS.rst
  mrp_unbuild_move_link/readme/DESCRIPTION.rst
  mrp_unbuild_move_link/static/description/icon.png
  mrp_unbuild_move_link/static/description/index.html
  mrp_unbuild_move_link/tests/__init__.py
  mrp_unbuild_move_link/tests/test_mrp_unbuild_move_link.py
  mrp_unbuild_move_link/views/stock_move_views.xml
  setup/mrp_unbuild_move_link/odoo/addons/mrp_unbuild_move_link
  setup/mrp_unbuild_move_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#974 [MIG][16.0] mrp_lot_production_date
  mrp_lot_production_date/README.rst
  mrp_lot_production_date/__init__.py
  mrp_lot_production_date/__manifest__.py
  mrp_lot_production_date/models/__init__.py
  mrp_lot_production_date/models/mrp_production.py
  mrp_lot_production_date/readme/CONTRIBUTORS.rst
  mrp_lot_production_date/readme/CREDITS.rst
  mrp_lot_production_date/readme/DESCRIPTION.rst
  mrp_lot_production_date/readme/USAGE.rst
  mrp_lot_production_date/static/description/index.html
  mrp_lot_production_date/tests/__init__.py
  mrp_lot_production_date/tests/test_production_date.py
  setup/mrp_lot_production_date/odoo/addons/mrp_lot_production_date
  setup/mrp_lot_production_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1072 [14.0][ADD] mrp_bom_attribute_match_semifinished_product
  mrp_bom_attribute_match_semifinished_product/README.rst
  mrp_bom_attribute_match_semifinished_product/__init__.py
  mrp_bom_attribute_match_semifinished_product/__manifest__.py
  mrp_bom_attribute_match_semifinished_product/models/__init__.py
  mrp_bom_attribute_match_semifinished_product/models/product_template.py
  mrp_bom_attribute_match_semifinished_product/models/semi_finished_product_template_line.py
  mrp_bom_attribute_match_semifinished_product/readme/CONFIGURE.rst
  mrp_bom_attribute_match_semifinished_product/readme/CONTEXT.rst
  mrp_bom_attribute_match_semifinished_product/readme/DESCRIPTION.rst
  mrp_bom_attribute_match_semifinished_product/readme/USAGE.rst
  mrp_bom_attribute_match_semifinished_product/readme/newsfragments/.gitkeep
  mrp_bom_attribute_match_semifinished_product/security/ir.model.access.csv
  mrp_bom_attribute_match_semifinished_product/security/semifinished_product_security.xml
  mrp_bom_attribute_match_semifinished_product/static/description/index.html
  mrp_bom_attribute_match_semifinished_product/tests/__init__.py
  mrp_bom_attribute_match_semifinished_product/tests/test_finished_product_common.py
  mrp_bom_attribute_match_semifinished_product/tests/test_finished_product_structure.py
  mrp_bom_attribute_match_semifinished_product/tests/test_product_template.py
  mrp_bom_attribute_match_semifinished_product/views/product_template_views.xml
  mrp_bom_attribute_match_semifinished_product/views/semi_finished_product_template_line_views.xml
  mrp_bom_attribute_match_semifinished_product/wizard/__init__.py
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_line.py
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.py
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.xml
  setup/mrp_bom_attribute_match_semifinished_product/odoo/addons/mrp_bom_attribute_match_semifinished_product
  setup/mrp_bom_attribute_match_semifinished_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1111 [13.0][BACKPORT] improve speed by creating mrp.move,mrp.invento…
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1143 [13.0][FIX] mrp_multi_level: Correct main supplier when changing sequence in Vendor Pricelist
  mrp_multi_level/models/product_mrp_area.py
Labels: approved, bot is merging ⏳

#1147 [16.0][PORT] mrp_multi_level: Correct main supplier when changing sequence in Vendor Pricelist
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1146 [15.0][PORT] mrp_multi_level: Correct main supplier when changing sequence in Vendor Pricelist
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1145 [14.0][PORT] mrp_multi_level: Correct main supplier when changing sequence in Vendor Pricelist
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳
