Repository OCA/manufacture, pull requests merged in 2023-12, with the labels that each got.

#1151 [IMP] mrp_multi_level: reduce some logging
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#1157 [16.0][REF] mrp_multi_level: location management
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1159 [16.0][IMP] mrp_multi_level: reduce some logging
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1158 [14.0][REF] mrp_multi_level: location management
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1161 [14.0][IMP] mrp_multi_level: reduce some logging
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1160 [13.0][REF] mrp_multi_level: location management
  mrp_multi_level/models/mrp_area.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1164 [15.0][IMP] mrp_multi_level_estimate: Stock moves from MO should always be considered
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1163 [13.0][IMP] mrp_multi_level_estimate: Stock moves from MO should always be considered
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1165 [16.0][IMP] mrp_multi_level_estimate: Stock moves from MO should always be considered
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1153 [14.0][ADD] mrp_bom_attribute_match_duplicate_kit
  mrp_bom_attribute_match_duplicate_kit/README.rst
  mrp_bom_attribute_match_duplicate_kit/__init__.py
  mrp_bom_attribute_match_duplicate_kit/__manifest__.py
  mrp_bom_attribute_match_duplicate_kit/models/__init__.py
  mrp_bom_attribute_match_duplicate_kit/models/product_template.py
  mrp_bom_attribute_match_duplicate_kit/readme/CONTEXT.rst
  mrp_bom_attribute_match_duplicate_kit/readme/CONTRIBUTORS.rst
  mrp_bom_attribute_match_duplicate_kit/readme/DESCRIPTION.rst
  mrp_bom_attribute_match_duplicate_kit/readme/HISTORY.rst
  mrp_bom_attribute_match_duplicate_kit/readme/USAGE.rst
  mrp_bom_attribute_match_duplicate_kit/security/ir.model.access.csv
  mrp_bom_attribute_match_duplicate_kit/static/description/index.html
  mrp_bom_attribute_match_duplicate_kit/tests/__init__.py
  mrp_bom_attribute_match_duplicate_kit/tests/common.py
  mrp_bom_attribute_match_duplicate_kit/tests/test_product_template.py
  mrp_bom_attribute_match_duplicate_kit/tests/test_product_template_kit_wizard.py
  mrp_bom_attribute_match_duplicate_kit/views/product_template_views.xml
  mrp_bom_attribute_match_duplicate_kit/wizard/__init__.py
  mrp_bom_attribute_match_duplicate_kit/wizard/product_template_kit_wizard.py
  mrp_bom_attribute_match_duplicate_kit/wizard/product_template_kit_wizard.xml
  setup/mrp_bom_attribute_match_duplicate_kit/odoo/addons/mrp_bom_attribute_match_duplicate_kit
  setup/mrp_bom_attribute_match_duplicate_kit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1168 [16.0][FIX] quality_control_oca: XML-ID must be fully qualified
  quality_control_oca/views/product_category_view.xml
Labels: bot is merging ⏳

#1172 [14.0] [FIX] mrp_bom_attribute_match: display proper BoM structure
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
Labels: approved, bot is merging ⏳

#1104 [15.0][FIX] Fix edge case date bug in addon `mrp_production_grouped_by_product`
  mrp_production_grouped_by_product/models/mrp_production.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1166 [MIG] mrp_workorder_lot_display: Backport to 15.0
  mrp_subcontracting_lot_number_propagation/models/mrp_production.py
  mrp_workorder_lot_display/README.rst
  mrp_workorder_lot_display/__init__.py
  mrp_workorder_lot_display/__manifest__.py
  mrp_workorder_lot_display/i18n/it.po
  mrp_workorder_lot_display/i18n/mrp_workorder_lot_display.pot
  mrp_workorder_lot_display/readme/CONTRIBUTORS.md
  mrp_workorder_lot_display/readme/DESCRIPTION.md
  mrp_workorder_lot_display/static/description/icon.png
  mrp_workorder_lot_display/static/description/index.html
  mrp_workorder_lot_display/views/mrp_workorder.xml
  setup/mrp_workorder_lot_display/odoo/addons/mrp_workorder_lot_display
  setup/mrp_workorder_lot_display/setup.py
Labels: approved, ready to merge, bot is merging ⏳
