Repository OCA/manufacture, pull requests merged in 2023-09, with the labels that each got.

#1090 [15.0][FIX] mrp_bom_attribute_match: cyclic references in bom
  mrp_bom_attribute_match/tests/common.py
Labels: bot is merging ⏳

#905 [14.0][ADD] mrp_production_auto_validate
  mrp_production_auto_validate/README.rst
  mrp_production_auto_validate/__init__.py
  mrp_production_auto_validate/__manifest__.py
  mrp_production_auto_validate/models/__init__.py
  mrp_production_auto_validate/models/mrp_bom.py
  mrp_production_auto_validate/models/mrp_production.py
  mrp_production_auto_validate/models/stock_picking.py
  mrp_production_auto_validate/models/stock_rule.py
  mrp_production_auto_validate/readme/CONFIGURE.rst
  mrp_production_auto_validate/readme/CONTRIBUTORS.rst
  mrp_production_auto_validate/readme/DESCRIPTION.rst
  mrp_production_auto_validate/readme/ROADMAP.rst
  mrp_production_auto_validate/static/description/index.html
  mrp_production_auto_validate/tests/__init__.py
  mrp_production_auto_validate/tests/test_auto_validate.py
  mrp_production_auto_validate/views/mrp_bom.xml
  mrp_production_auto_validate/views/mrp_production.xml
  mrp_production_auto_validate/wizards/__init__.py
  mrp_production_auto_validate/wizards/mrp_production_backorder.py
  setup/mrp_production_auto_validate/odoo/addons/mrp_production_auto_validate
  setup/mrp_production_auto_validate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1094 [16.0][MIG] mrp_production_note: Migration to 16.0
  mrp_production_note/README.rst
  mrp_production_note/__init__.py
  mrp_production_note/__manifest__.py
  mrp_production_note/i18n/de.po
  mrp_production_note/i18n/es.po
  mrp_production_note/i18n/es_MX.po
  mrp_production_note/i18n/fi.po
  mrp_production_note/i18n/fr.po
  mrp_production_note/i18n/gl.po
  mrp_production_note/i18n/hr.po
  mrp_production_note/i18n/hr_HR.po
  mrp_production_note/i18n/it.po
  mrp_production_note/i18n/lt.po
  mrp_production_note/i18n/mrp_production_note.pot
  mrp_production_note/i18n/nl_NL.po
  mrp_production_note/i18n/pt_BR.po
  mrp_production_note/i18n/ro.po
  mrp_production_note/i18n/sl.po
  mrp_production_note/i18n/tr.po
  mrp_production_note/i18n/tr_TR.po
  mrp_production_note/i18n/vi_VN.po
  mrp_production_note/i18n/zh_CN.po
  mrp_production_note/models/__init__.py
  mrp_production_note/models/mrp_production.py
  mrp_production_note/readme/CONTRIBUTORS.rst
  mrp_production_note/readme/DESCRIPTION.rst
  mrp_production_note/readme/USAGE.rst
  mrp_production_note/static/description/icon.png
  mrp_production_note/static/description/index.html
  mrp_production_note/views/mrp_production_view.xml
  setup/mrp_production_note/odoo/addons/mrp_production_note
  setup/mrp_production_note/setup.py
Labels: approved, bot is merging ⏳

#735 [14.0][ADD] repair_sale_order
  repair_sale_order/README.rst
  repair_sale_order/__init__.py
  repair_sale_order/__manifest__.py
  repair_sale_order/models/__init__.py
  repair_sale_order/models/repair_order.py
  repair_sale_order/models/repair_type.py
  repair_sale_order/models/sale_order.py
  repair_sale_order/readme/CONTRIBUTORS.rst
  repair_sale_order/readme/DESCRIPTION.rst
  repair_sale_order/readme/ROADMAP.rst
  repair_sale_order/readme/USAGE.rst
  repair_sale_order/static/description/index.html
  repair_sale_order/tests/__init__.py
  repair_sale_order/tests/test_repair_sale_order.py
  repair_sale_order/views/repair_order_view.xml
  repair_sale_order/views/repair_type_view.xml
  repair_sale_order/views/sale_order_view.xml
  setup/repair_sale_order/odoo/addons/repair_sale_order
  setup/repair_sale_order/setup.py
Labels: approved, bot is merging ⏳

#1098 [16.0][IMP] mrp_bom_location: logic operator warning
  mrp_bom_location/report/bom_structure.py
Labels: bot is merging ⏳
