Repository OCA/manufacture, pull requests merged in 2023-10, with the labels that each got.

#969 [14.0][ADD] mrp_package_propagation
  mrp_package_propagation/README.rst
  mrp_package_propagation/__init__.py
  mrp_package_propagation/__manifest__.py
  mrp_package_propagation/models/__init__.py
  mrp_package_propagation/models/mrp_bom.py
  mrp_package_propagation/models/mrp_bom_line.py
  mrp_package_propagation/models/mrp_production.py
  mrp_package_propagation/models/stock_move.py
  mrp_package_propagation/readme/CONTRIBUTORS.rst
  mrp_package_propagation/readme/DESCRIPTION.rst
  mrp_package_propagation/readme/USAGE.rst
  mrp_package_propagation/static/description/index.html
  mrp_package_propagation/tests/__init__.py
  mrp_package_propagation/tests/common.py
  mrp_package_propagation/tests/test_mrp_bom.py
  mrp_package_propagation/tests/test_mrp_production.py
  mrp_package_propagation/views/mrp_bom.xml
  mrp_package_propagation/views/mrp_production.xml
  setup/mrp_package_propagation/odoo/addons/mrp_package_propagation
  setup/mrp_package_propagation/setup.py
Labels: approved, ready to merge, merged 🎉

#1101 [13.0][IMP] quality_control_stock_oca: sudo the process of creating the test and calculated fields, so no permissions have to be assigned to the sotck user
  quality_control_stock_oca/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1082 [14.0][ADD] mrp_subcontracting_purchase
  mrp_subcontracting_purchase/README.rst
  mrp_subcontracting_purchase/__init__.py
  mrp_subcontracting_purchase/__manifest__.py
  mrp_subcontracting_purchase/data/mrp_subcontracting_dropshipping_data.xml
  mrp_subcontracting_purchase/demo/bom_subcontract_demo.xml
  mrp_subcontracting_purchase/demo/partner_subcontract_demo.xml
  mrp_subcontracting_purchase/demo/product_category_demo.xml
  mrp_subcontracting_purchase/demo/product_product_demo.xml
  mrp_subcontracting_purchase/demo/product_supplierinfo_demo.xml
  mrp_subcontracting_purchase/demo/stock_location_demo.xml
  mrp_subcontracting_purchase/demo/stock_rules_demo.xml
  mrp_subcontracting_purchase/i18n/it.po
  mrp_subcontracting_purchase/models/__init__.py
  mrp_subcontracting_purchase/models/mrp_production.py
  mrp_subcontracting_purchase/models/purchase_order.py
  mrp_subcontracting_purchase/models/purchase_order_line.py
  mrp_subcontracting_purchase/models/res_company.py
  mrp_subcontracting_purchase/models/stock_move.py
  mrp_subcontracting_purchase/models/stock_picking.py
  mrp_subcontracting_purchase/models/stock_rule.py
  mrp_subcontracting_purchase/models/stock_warehouse.py
  mrp_subcontracting_purchase/readme/CONFIGURATION.md
  mrp_subcontracting_purchase/readme/CONTRIBUTORS.md
  mrp_subcontracting_purchase/readme/DESCRIPTION.md
  mrp_subcontracting_purchase/readme/HISTORY.md
  mrp_subcontracting_purchase/static/description/icon.png
  mrp_subcontracting_purchase/tests/__init__.py
  mrp_subcontracting_purchase/tests/test_mrp_production.py
  mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  mrp_subcontracting_purchase/tests/test_purchase_order.py
  mrp_subcontracting_purchase/tests/test_res_company.py
  mrp_subcontracting_purchase/tests/test_stock_move.py
  mrp_subcontracting_purchase/views/purchase_order_views.xml
  mrp_subcontracting_purchase/views/stock_picking_views.xml
  setup/mrp_subcontracting_purchase/odoo/addons/mrp_subcontracting_purchase
  setup/mrp_subcontracting_purchase/setup.py
Labels: bot is merging ⏳

#1108 [14.0][FIX] mrp_subcontracting_purchase: rename file
  mrp_subcontracting_purchase/readme/CONFIGURE.md
Labels: bot is merging ⏳

#1114 [MIG] mrp_bom_hierarchy: Migration to 16.0
  mrp_bom_hierarchy/README.rst
  mrp_bom_hierarchy/__init__.py
  mrp_bom_hierarchy/__manifest__.py
  mrp_bom_hierarchy/i18n/it.po
  mrp_bom_hierarchy/i18n/mrp_bom_hierarchy.pot
  mrp_bom_hierarchy/model/__init__.py
  mrp_bom_hierarchy/model/mrp_bom.py
  mrp_bom_hierarchy/readme/CONTRIBUTORS.rst
  mrp_bom_hierarchy/readme/DESCRIPTION.rst
  mrp_bom_hierarchy/readme/USAGE.rst
  mrp_bom_hierarchy/static/description/icon.png
  mrp_bom_hierarchy/static/description/index.html
  mrp_bom_hierarchy/view/mrp.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/mrp_bom_component_menu/setup.py
  setup/mrp_bom_hierarchy/odoo/addons/mrp_bom_hierarchy
  setup/mrp_bom_hierarchy/setup.py
  setup/mrp_bom_location/setup.py
  setup/mrp_bom_tracking/setup.py
  setup/mrp_multi_level/setup.py
  setup/mrp_multi_level_estimate/setup.py
  setup/mrp_production_note/setup.py
  setup/mrp_production_quant_manual_assign/setup.py
  setup/mrp_restrict_lot/setup.py
  setup/mrp_sale_info/setup.py
  setup/mrp_warehouse_calendar/setup.py
  setup/quality_control_oca/setup.py
Labels: approved, bot is merging ⏳

#1083 [13.0][ADD] mrp_workorder_update_component
  mrp_workorder_update_component/README.rst
  mrp_workorder_update_component/__init__.py
  mrp_workorder_update_component/__manifest__.py
  mrp_workorder_update_component/models/__init__.py
  mrp_workorder_update_component/models/mrp_workorder.py
  mrp_workorder_update_component/readme/CONTRIBUTORS.rst
  mrp_workorder_update_component/readme/DESCRIPTION.rst
  mrp_workorder_update_component/static/description/icon.png
  mrp_workorder_update_component/tests/__init__.py
  mrp_workorder_update_component/tests/test_mrp_workorder.py
  mrp_workorder_update_component/views/mrp_workorder_view.xml
  mrp_workorder_update_component/wizards/__init__.py
  mrp_workorder_update_component/wizards/mrp_workorder_new_line.py
  mrp_workorder_update_component/wizards/mrp_workorder_new_line_view.xml
  setup/mrp_workorder_update_component/odoo/addons/mrp_workorder_update_component
  setup/mrp_workorder_update_component/setup.py
Labels: approved, bot is merging ⏳

#1100 [14.0][FIX] mrp_bom_attribute_match
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/demo/product_product_demo.xml
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
  mrp_bom_attribute_match/tests/__init__.py
  mrp_bom_attribute_match/tests/common.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match_nested.py
Labels: approved, bot is merging ⏳

#1120 [14.0][IMP] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mrp_bom_component_menu/views/mrp_bom_component_view.xml
  mrp_multi_level/views/mrp_area_views.xml
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/views/mrp_move_views.xml
  mrp_multi_level/views/product_mrp_area_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure_views.xml
  mrp_routing/data/sequence_data.xml
  mrp_routing/demo/routing_data.xml
  mrp_routing/views/mrp_bom_view.xml
  mrp_routing/views/mrp_routing_view.xml
  mrp_routing/views/mrp_routing_workcenter_template_view.xml
  mrp_routing/views/mrp_routing_workcenter_view.xml
  mrp_subcontracting_purchase/data/mrp_subcontracting_dropshipping_data.xml
  mrp_tag/views/mrp_tag_view.xml
  quality_control_oca/data/quality_control_data.xml
  quality_control_oca/demo/quality_control_demo.xml
  quality_control_oca/i18n/quality_control_oca.pot
  quality_control_oca/views/product_category_view.xml
  quality_control_oca/views/product_template_view.xml
  quality_control_oca/views/qc_inspection_view.xml
  quality_control_oca/views/qc_test_category_view.xml
  quality_control_oca/views/qc_test_view.xml
  quality_control_oca/views/qc_trigger_view.xml
  repair_sale_order/views/repair_order_view.xml
  repair_sale_order/views/repair_type_view.xml
  repair_sale_order/views/sale_order_view.xml
Labels: bot is merging ⏳
