Repository OCA/manufacture, pull requests merged in 2024-06, with the labels that each got.

#1272 [17.0][MIG] quality_control_stock_oca: Migration to 17.0
  quality_control_stock_oca/README.rst
  quality_control_stock_oca/__init__.py
  quality_control_stock_oca/__manifest__.py
  quality_control_stock_oca/i18n/ca.po
  quality_control_stock_oca/i18n/de.po
  quality_control_stock_oca/i18n/el_GR.po
  quality_control_stock_oca/i18n/es.po
  quality_control_stock_oca/i18n/es_AR.po
  quality_control_stock_oca/i18n/es_ES.po
  quality_control_stock_oca/i18n/es_MX.po
  quality_control_stock_oca/i18n/eu.po
  quality_control_stock_oca/i18n/fi.po
  quality_control_stock_oca/i18n/fr.po
  quality_control_stock_oca/i18n/fr_CH.po
  quality_control_stock_oca/i18n/fr_FR.po
  quality_control_stock_oca/i18n/gl.po
  quality_control_stock_oca/i18n/hr.po
  quality_control_stock_oca/i18n/hr_HR.po
  quality_control_stock_oca/i18n/it.po
  quality_control_stock_oca/i18n/nl.po
  quality_control_stock_oca/i18n/nl_NL.po
  quality_control_stock_oca/i18n/pt.po
  quality_control_stock_oca/i18n/pt_BR.po
  quality_control_stock_oca/i18n/quality_control_stock_oca.pot
  quality_control_stock_oca/i18n/ro.po
  quality_control_stock_oca/i18n/ru.po
  quality_control_stock_oca/i18n/sk.po
  quality_control_stock_oca/i18n/sl.po
  quality_control_stock_oca/i18n/tr.po
  quality_control_stock_oca/i18n/tr_TR.po
  quality_control_stock_oca/i18n/vi_VN.po
  quality_control_stock_oca/i18n/zh_CN.po
  quality_control_stock_oca/models/__init__.py
  quality_control_stock_oca/models/qc_inspection.py
  quality_control_stock_oca/models/qc_trigger.py
  quality_control_stock_oca/models/stock_picking.py
  quality_control_stock_oca/models/stock_picking_type.py
  quality_control_stock_oca/models/stock_production_lot.py
  quality_control_stock_oca/pyproject.toml
  quality_control_stock_oca/readme/CONTRIBUTORS.md
  quality_control_stock_oca/readme/DESCRIPTION.md
  quality_control_stock_oca/readme/ROADMAP.md
  quality_control_stock_oca/static/description/icon.png
  quality_control_stock_oca/static/description/index.html
  quality_control_stock_oca/tests/__init__.py
  quality_control_stock_oca/tests/test_quality_control_stock.py
  quality_control_stock_oca/views/qc_inspection_view.xml
  quality_control_stock_oca/views/qc_trigger_view.xml
  quality_control_stock_oca/views/stock_picking_view.xml
  quality_control_stock_oca/views/stock_production_lot_view.xml
Labels: approved, bot is merging ⏳

#1131 Draft:[14.0][FIX] #10130 mrp_sale_info
  mrp_sale_info/__manifest__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
Labels: approved, bot is merging ⏳

#1264 [17.0][MIG] mrp_workorder_sequence: Migration to 17.0
  mrp_workorder_sequence/README.rst
  mrp_workorder_sequence/__init__.py
  mrp_workorder_sequence/__manifest__.py
  mrp_workorder_sequence/hooks.py
  mrp_workorder_sequence/i18n/it.po
  mrp_workorder_sequence/i18n/mrp_workorder_sequence.pot
  mrp_workorder_sequence/models/__init__.py
  mrp_workorder_sequence/models/mrp_production.py
  mrp_workorder_sequence/models/mrp_workorder.py
  mrp_workorder_sequence/pyproject.toml
  mrp_workorder_sequence/readme/CONTRIBUTORS.md
  mrp_workorder_sequence/readme/DESCRIPTION.md
  mrp_workorder_sequence/readme/USAGE.md
  mrp_workorder_sequence/static/description/icon.png
  mrp_workorder_sequence/static/description/index.html
  mrp_workorder_sequence/tests/__init__.py
  mrp_workorder_sequence/tests/test_mrp_workorder_sequence.py
  mrp_workorder_sequence/views/mrp_workorder_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1117 [16.0][MIG] mrp_unbuild_valuation_layer_link
  mrp_unbuild_valuation_layer_link/README.rst
  mrp_unbuild_valuation_layer_link/__init__.py
  mrp_unbuild_valuation_layer_link/__manifest__.py
  mrp_unbuild_valuation_layer_link/i18n/it.po
  mrp_unbuild_valuation_layer_link/i18n/mrp_unbuild_valuation_layer_link.pot
  mrp_unbuild_valuation_layer_link/models/__init__.py
  mrp_unbuild_valuation_layer_link/models/mrp_unbuild.py
  mrp_unbuild_valuation_layer_link/readme/CONTRIBUTORS.rst
  mrp_unbuild_valuation_layer_link/readme/DESCRIPTION.rst
  mrp_unbuild_valuation_layer_link/readme/USAGE.rst
  mrp_unbuild_valuation_layer_link/static/description/icon.png
  mrp_unbuild_valuation_layer_link/static/description/index.html
  mrp_unbuild_valuation_layer_link/tests/__init__.py
  mrp_unbuild_valuation_layer_link/tests/test_mrp__unbuild_valuation_layer_link.py
  mrp_unbuild_valuation_layer_link/views/mrp_unbuild_views.xml
  setup/mrp_unbuild_valuation_layer_link/odoo/addons/mrp_unbuild_valuation_layer_link
  setup/mrp_unbuild_valuation_layer_link/setup.py
Labels: approved, bot is merging ⏳, stale

#1203 [REF] mrp_bom_hierarchy with OCA guidelines
  mrp_bom_hierarchy/README.rst
  mrp_bom_hierarchy/__manifest__.py
  mrp_bom_hierarchy/model/__init__.py
  mrp_bom_hierarchy/model/mrp_bom.py
  mrp_bom_hierarchy/model/mrp_bom_line.py
  mrp_bom_hierarchy/readme/CONTRIBUTORS.rst
  mrp_bom_hierarchy/view/mrp_bom.xml
Labels: approved, bot is merging ⏳

#1205 [IMP] mrp_bom_hierarchy Remove field out of scope
  mrp_bom_hierarchy/model/mrp_bom.py
Labels: approved, bot is merging ⏳

#1285 [14.0][FIX] mrp_bom_attribute_match: fix unfolded print
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
Labels: approved

#1288 [14.0][FIX] mrp_bom_attribute_match: fix unfolded print
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match_nested.py
Labels: approved, bot is merging ⏳

#1287 [14.0][ADD] repair_picking
  repair_picking/README.rst
  repair_picking/__init__.py
  repair_picking/__manifest__.py
  repair_picking/models/__init__.py
  repair_picking/models/repair.py
  repair_picking/models/stock_rule.py
  repair_picking/models/stock_warehouse.py
  repair_picking/readme/CONFIGURE.rst
  repair_picking/readme/CONTRIBUTORS.rst
  repair_picking/readme/DESCRIPTION.rst
  repair_picking/readme/USAGE.rst
  repair_picking/static/description/index.html
  repair_picking/tests/__init__.py
  repair_picking/tests/test_stock_repair_order.py
  repair_picking/tests/test_stock_repair_warehouse.py
  repair_picking/views/repair_order_view.xml
  repair_picking/views/stock_warehouse_views.xml
  setup/repair_picking/odoo/addons/repair_picking
  setup/repair_picking/setup.py
Labels: approved, bot is merging ⏳

#1295 16.0 mig mrp bom note
  mrp_bom_note/README.rst
  mrp_bom_note/__init__.py
  mrp_bom_note/__manifest__.py
  mrp_bom_note/i18n/de.po
  mrp_bom_note/i18n/es.po
  mrp_bom_note/i18n/fi.po
  mrp_bom_note/i18n/fr.po
  mrp_bom_note/i18n/gl.po
  mrp_bom_note/i18n/hr.po
  mrp_bom_note/i18n/hr_HR.po
  mrp_bom_note/i18n/it.po
  mrp_bom_note/i18n/lt.po
  mrp_bom_note/i18n/mrp_bom_note.pot
  mrp_bom_note/i18n/nl_NL.po
  mrp_bom_note/i18n/pt_BR.po
  mrp_bom_note/i18n/ro.po
  mrp_bom_note/i18n/sl.po
  mrp_bom_note/i18n/tr.po
  mrp_bom_note/i18n/tr_TR.po
  mrp_bom_note/i18n/zh_CN.po
  mrp_bom_note/models/__init__.py
  mrp_bom_note/models/mrp_bom.py
  mrp_bom_note/readme/CONTRIBUTORS.rst
  mrp_bom_note/readme/DESCRIPTION.rst
  mrp_bom_note/readme/USAGE.rst
  mrp_bom_note/static/description/icon.png
  mrp_bom_note/static/description/index.html
  mrp_bom_note/views/mrp_bom_view.xml
  setup/mrp_bom_note/odoo/addons/mrp_bom_note
  setup/mrp_bom_note/setup.py
Labels: approved
