Repository OCA/manufacture, pull requests merged in 2024-08, with the labels that each got.

#1325 [16.0] [MIG] product mrp info: Migration to 16.0
  product_mrp_info/README.rst
  product_mrp_info/__init__.py
  product_mrp_info/__manifest__.py
  product_mrp_info/i18n/es.po
  product_mrp_info/i18n/it.po
  product_mrp_info/i18n/product_mrp_info.pot
  product_mrp_info/models/__init__.py
  product_mrp_info/models/product.py
  product_mrp_info/readme/CONTRIBUTORS.rst
  product_mrp_info/readme/DESCRIPTION.rst
  product_mrp_info/readme/USAGE.rst
  product_mrp_info/static/description/icon.png
  product_mrp_info/static/description/index.html
  product_mrp_info/tests/__init__.py
  product_mrp_info/tests/test_product_mrp_info.py
  product_mrp_info/views/product_views.xml
  setup/product_mrp_info/odoo/addons/product_mrp_info
  setup/product_mrp_info/setup.py
Labels: approved, ready to merge

#1262 [15.0][MIG] mrp_subcontracting_purchase_link: Migration to 15.0
  mrp_subcontracting_purchase_link/README.rst
  mrp_subcontracting_purchase_link/__init__.py
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/hooks.py
  mrp_subcontracting_purchase_link/i18n/es.po
  mrp_subcontracting_purchase_link/i18n/it.po
  mrp_subcontracting_purchase_link/i18n/ja.po
  mrp_subcontracting_purchase_link/i18n/mrp_subcontracting_purchase_link.pot
  mrp_subcontracting_purchase_link/models/__init__.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/readme/CONTRIBUTORS.rst
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.rst
  mrp_subcontracting_purchase_link/static/description/icon.png
  mrp_subcontracting_purchase_link/static/description/index.html
  mrp_subcontracting_purchase_link/tests/__init__.py
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
  mrp_subcontracting_purchase_link/views/purchase_order_views.xml
  setup/mrp_subcontracting_purchase_link/odoo/addons/mrp_subcontracting_purchase_link
  setup/mrp_subcontracting_purchase_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1314 [16.0][FIX] quality_control_oca: In product category form view, fix quality…
  quality_control_oca/views/product_category_view.xml
Labels: approved, bot is merging ⏳

#1334 [15.0][MIG] mrp_production_picking_type_from_route
  mrp_production_picking_type_from_route/README.rst
  mrp_production_picking_type_from_route/__init__.py
  mrp_production_picking_type_from_route/__manifest__.py
  mrp_production_picking_type_from_route/i18n/it.po
  mrp_production_picking_type_from_route/i18n/mrp_production_picking_type_from_route.pot
  mrp_production_picking_type_from_route/models/__init__.py
  mrp_production_picking_type_from_route/models/mrp_production.py
  mrp_production_picking_type_from_route/readme/CONTRIBUTORS.rst
  mrp_production_picking_type_from_route/readme/DESCRIPTION.rst
  mrp_production_picking_type_from_route/readme/USAGE.rst
  mrp_production_picking_type_from_route/static/description/icon.png
  mrp_production_picking_type_from_route/static/description/index.html
  mrp_production_picking_type_from_route/tests/__init__.py
  mrp_production_picking_type_from_route/tests/test_mrp_production_picking_type_from_route.py
  setup/mrp_production_picking_type_from_route/odoo/addons/mrp_production_picking_type_from_route
  setup/mrp_production_picking_type_from_route/setup.py
Labels: approved, bot is merging ⏳

#1337 [15.0][FIX] mrp_sale_info: add measure to avoid infinite recursion error
  mrp_sale_info/models/stock_move.py
Labels: approved, bot is merging ⏳

#1339 [15.0][IMP] account_move_line_mrp_info: filter journal item list by MO/UO
  account_move_line_mrp_info/views/account_move_line_view.xml
Labels: approved, bot is merging ⏳

#1336 [16.0][IMP] mrp_multi_level: better logs during calculation
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, ready to merge, bot is merging ⏳, Pending to fw/back port

#1344 [17.0][IMP] mrp_multi_level: better logs during calculation
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1342 [14.0][IMP-FIX] mrp_subcontracting_partner_management: Define the correct picking_type (out) in the subcontracting_resupply rule
  mrp_subcontracting_partner_management/models/res_partner.py
  mrp_subcontracting_partner_management/tests/test_create_subcontractor_partner_location.py
  mrp_subcontracting_partner_management/views/res_partner_views.xml
  mrp_subcontracting_purchase_partner_management/tests/test_create_subcontractor_partner_location.py
Labels: approved, bot is merging ⏳
