Repository OCA/manufacture, pull requests merged in 2024-05, with the labels that each got.

#1268 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: help wanted, needs review, bot is merging ⏳

#1198 [17.0][MIG] mrp_sale_info: Migration to 17.0
  mrp_sale_info/README.rst
  mrp_sale_info/__init__.py
  mrp_sale_info/__manifest__.py
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/it.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/pyproject.toml
  mrp_sale_info/readme/CONTRIBUTORS.md
  mrp_sale_info/readme/DESCRIPTION.md
  mrp_sale_info/readme/USAGE.md
  mrp_sale_info/static/description/icon.png
  mrp_sale_info/static/description/index.html
  mrp_sale_info/tests/__init__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
Labels: bot is merging ⏳

#1269 [15.0][ADD] stock_replenishment_mrp_bom_selection: New module
  setup/stock_replenishment_mrp_bom_selection/odoo/addons/stock_replenishment_mrp_bom_selection
  setup/stock_replenishment_mrp_bom_selection/setup.py
  stock_replenishment_mrp_bom_selection/README.rst
  stock_replenishment_mrp_bom_selection/__init__.py
  stock_replenishment_mrp_bom_selection/__manifest__.py
  stock_replenishment_mrp_bom_selection/i18n/es.po
  stock_replenishment_mrp_bom_selection/i18n/stock_replenishment_mrp_bom_selection.pot
  stock_replenishment_mrp_bom_selection/models/__init__.py
  stock_replenishment_mrp_bom_selection/models/stock_warehouse_orderpoint.py
  stock_replenishment_mrp_bom_selection/readme/CONTEXT.rst
  stock_replenishment_mrp_bom_selection/readme/CONTRIBUTORS.rst
  stock_replenishment_mrp_bom_selection/readme/DESCRIPTION.rst
  stock_replenishment_mrp_bom_selection/readme/USAGE.rst
  stock_replenishment_mrp_bom_selection/security/ir.model.access.csv
  stock_replenishment_mrp_bom_selection/static/description/index.html
  stock_replenishment_mrp_bom_selection/tests/__init__.py
  stock_replenishment_mrp_bom_selection/tests/test_stock_replenishment_mrp_bom_selection.py
  stock_replenishment_mrp_bom_selection/wizard/__init__.py
  stock_replenishment_mrp_bom_selection/wizard/material_availability_wizard.py
  stock_replenishment_mrp_bom_selection/wizard/material_availability_wizard_views.xml
  stock_replenishment_mrp_bom_selection/wizard/stock_warehouse_orderpoint_replenish_wizard.py
  stock_replenishment_mrp_bom_selection/wizard/stock_warehouse_orderpoint_replenish_wizard_views.xml
Labels: approved, bot is merging ⏳

#1266 [14.0][FIX] mrp_unbuild_subcontracting, action_validate expect to be singleton
  mrp_unbuild_subcontracting/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1273 [17.0][MIG] mrp_multi_level_estimate
  mrp_multi_level_estimate/README.rst
  mrp_multi_level_estimate/__init__.py
  mrp_multi_level_estimate/__manifest__.py
  mrp_multi_level_estimate/i18n/es.po
  mrp_multi_level_estimate/i18n/it.po
  mrp_multi_level_estimate/i18n/mrp_multi_level_estimate.pot
  mrp_multi_level_estimate/models/__init__.py
  mrp_multi_level_estimate/models/mrp_area.py
  mrp_multi_level_estimate/models/product_mrp_area.py
  mrp_multi_level_estimate/pyproject.toml
  mrp_multi_level_estimate/readme/CONFIGURE.md
  mrp_multi_level_estimate/readme/CONTRIBUTORS.md
  mrp_multi_level_estimate/readme/DESCRIPTION.md
  mrp_multi_level_estimate/static/description/icon.png
  mrp_multi_level_estimate/static/description/index.html
  mrp_multi_level_estimate/tests/__init__.py
  mrp_multi_level_estimate/tests/test_mrp_multi_level_estimate.py
  mrp_multi_level_estimate/views/mrp_area_views.xml
  mrp_multi_level_estimate/views/product_mrp_area_views.xml
  mrp_multi_level_estimate/wizards/__init__.py
  mrp_multi_level_estimate/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1275 [14.0][MIG] mrp_auto_assign
  mrp_auto_assign/README.rst
  mrp_auto_assign/__init__.py
  mrp_auto_assign/__manifest__.py
  mrp_auto_assign/i18n/de.po
  mrp_auto_assign/i18n/es.po
  mrp_auto_assign/i18n/es_MX.po
  mrp_auto_assign/i18n/fr.po
  mrp_auto_assign/i18n/gl.po
  mrp_auto_assign/i18n/hr.po
  mrp_auto_assign/i18n/hr_HR.po
  mrp_auto_assign/i18n/it.po
  mrp_auto_assign/i18n/lt.po
  mrp_auto_assign/i18n/mrp_auto_assign.pot
  mrp_auto_assign/i18n/nl_NL.po
  mrp_auto_assign/i18n/pt_BR.po
  mrp_auto_assign/i18n/ro.po
  mrp_auto_assign/i18n/sl.po
  mrp_auto_assign/i18n/tr.po
  mrp_auto_assign/i18n/vi_VN.po
  mrp_auto_assign/i18n/zh_CN.po
  mrp_auto_assign/models/__init__.py
  mrp_auto_assign/models/mrp_production.py
  mrp_auto_assign/readme/CONTRIBUTORS.rst
  mrp_auto_assign/readme/DESCRIPTION.rst
  mrp_auto_assign/readme/ROADMAP.rst
  mrp_auto_assign/readme/USAGE.rst
  mrp_auto_assign/static/description/icon.png
  mrp_auto_assign/static/description/index.html
  mrp_auto_assign/tests/__init__.py
  mrp_auto_assign/tests/test_auto_assign.py
  setup/mrp_auto_assign/odoo/addons/mrp_auto_assign
  setup/mrp_auto_assign/setup.py
Labels: approved, bot is merging ⏳

#1265 [14.0] mrp_package_propagation: propagate from consumable components
  mrp_package_propagation/models/mrp_production.py
  mrp_package_propagation/tests/test_mrp_production.py
Labels: approved, ready to merge, bot is merging ⏳

#1276 [FIX] account_move_line_mrp_info: add migration script
  account_move_line_mrp_info/migrations/14.0.1.0.0/pre-migration.py
Labels: approved
