Repository OCA/manufacture, pull requests merged in 2024-12, with the labels that each got.

#1400 [FIX] mrp_packaging_default: multiply packagings per products manufactured
  mrp_packaging_default/models/__init__.py
  mrp_packaging_default/models/mrp_production.py
  mrp_packaging_default/models/stock_move.py
  mrp_packaging_default/tests/test_mrp_packaging_default.py
Labels: approved, ready to merge, bot is merging ⏳

#1239 [16.0][ADD] mrp_bom_select_product_variant
  mrp_bom_select_product_variant/README.rst
  mrp_bom_select_product_variant/__init__.py
  mrp_bom_select_product_variant/__manifest__.py
  mrp_bom_select_product_variant/i18n/fr.po
  mrp_bom_select_product_variant/model/__init__.py
  mrp_bom_select_product_variant/model/mrp_bom.py
  mrp_bom_select_product_variant/readme/CONTRIBUTORS.rst
  mrp_bom_select_product_variant/readme/DESCRIPTION.rst
  mrp_bom_select_product_variant/static/description/index.html
  mrp_bom_select_product_variant/static/description/mrp_bom_select_product_variant.gif
  mrp_bom_select_product_variant/tests/__init__.py
  mrp_bom_select_product_variant/tests/test_bom_product_variant.py
  mrp_bom_select_product_variant/view/mrp_bom.xml
  setup/mrp_bom_select_product_variant/odoo/addons/mrp_bom_select_product_variant
  setup/mrp_bom_select_product_variant/setup.py
Labels: approved, bot is merging ⏳, stale

#1404 [16.0][FIX] mrp_multi_level: delete params on cascade when deleting product.
  mrp_multi_level/models/product_mrp_area.py
Labels: approved, ready to merge, bot is merging ⏳

#1408 [FIX] mrp_bom_image: use new syntax to filter elements by their classes
  mrp_bom_image/views/view_mrp_bom.xml
Labels: bot is merging ⏳

#1409 [15.0][FIX] mrp_multi_level: delete params on cascade when deleting product.
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1410 [17.0][FIX] mrp_multi_level: delete params on cascade when deleting product.
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/static/description/index.html
Labels: bot is merging ⏳

#1241 [16.0][ADD] mrp_bom_produce_delay
  mrp_bom_produce_delay/README.rst
  mrp_bom_produce_delay/__init__.py
  mrp_bom_produce_delay/__manifest__.py
  mrp_bom_produce_delay/i18n/fr.po
  mrp_bom_produce_delay/model/__init__.py
  mrp_bom_produce_delay/model/mrp_bom.py
  mrp_bom_produce_delay/readme/CONTRIBUTORS.rst
  mrp_bom_produce_delay/readme/DESCRIPTION.rst
  mrp_bom_produce_delay/static/description/index.html
  mrp_bom_produce_delay/static/description/mrp_bom_produce_delay.png
  mrp_bom_produce_delay/tests/__init__.py
  mrp_bom_produce_delay/tests/test_bom_produce_delay.py
  mrp_bom_produce_delay/view/mrp_bom.xml
  setup/mrp_bom_produce_delay/odoo/addons/mrp_bom_produce_delay
  setup/mrp_bom_produce_delay/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1348 [16.0][ADD] notes from bom on report_mrporder
  mrp_bom_note/README.rst
  mrp_bom_note/__manifest__.py
  mrp_bom_note/readme/CONTRIBUTORS.rst
  mrp_bom_note/static/description/index.html
  mrp_bom_note/views/mrp_production_templates.xml
Labels: approved, bot is merging ⏳

#1245 [17.0][MIG] account_move_line_mrp_info
  account_move_line_mrp_info/README.rst
  account_move_line_mrp_info/__init__.py
  account_move_line_mrp_info/__manifest__.py
  account_move_line_mrp_info/hooks.py
  account_move_line_mrp_info/i18n/account_move_line_mrp_info.pot
  account_move_line_mrp_info/i18n/it.po
  account_move_line_mrp_info/models/__init__.py
  account_move_line_mrp_info/models/account_move_line.py
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/pyproject.toml
  account_move_line_mrp_info/readme/CONTRIBUTORS.md
  account_move_line_mrp_info/readme/DESCRIPTION.md
  account_move_line_mrp_info/readme/USAGE.md
  account_move_line_mrp_info/security/ir.model.access.csv
  account_move_line_mrp_info/static/description/icon.png
  account_move_line_mrp_info/static/description/index.html
  account_move_line_mrp_info/tests/__init__.py
  account_move_line_mrp_info/tests/test_mrp_journal_items.py
  account_move_line_mrp_info/views/account_move_line_view.xml
  account_move_line_mrp_info/views/mrp_production_view.xml
Labels: approved, bot is merging ⏳

#1422 [17.0] [MIG] mrp_production_back_to_draft
  mrp_production_back_to_draft/README.rst
  mrp_production_back_to_draft/__init__.py
  mrp_production_back_to_draft/__manifest__.py
  mrp_production_back_to_draft/i18n/it.po
  mrp_production_back_to_draft/i18n/mrp_production_back_to_draft.pot
  mrp_production_back_to_draft/models/__init__.py
  mrp_production_back_to_draft/models/mrp_production.py
  mrp_production_back_to_draft/pyproject.toml
  mrp_production_back_to_draft/readme/CONTRIBUTORS.md
  mrp_production_back_to_draft/readme/DESCRIPTION.md
  mrp_production_back_to_draft/static/description/icon.png
  mrp_production_back_to_draft/static/description/index.html
  mrp_production_back_to_draft/tests/__init__.py
  mrp_production_back_to_draft/tests/test_mrp_return_to_draft.py
  mrp_production_back_to_draft/views/mrp_production_views.xml
Labels: approved, bot is merging ⏳

#1423 mrp_sale_info: fix duplicating SO.
  mrp_sale_info/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1274 [17.0][MIG] mrp_planned_order_matrix
  mrp_planned_order_matrix/README.rst
  mrp_planned_order_matrix/__init__.py
  mrp_planned_order_matrix/__manifest__.py
  mrp_planned_order_matrix/i18n/es.po
  mrp_planned_order_matrix/i18n/it.po
  mrp_planned_order_matrix/i18n/mrp_planned_order_matrix.pot
  mrp_planned_order_matrix/pyproject.toml
  mrp_planned_order_matrix/readme/CONTRIBUTORS.md
  mrp_planned_order_matrix/readme/DESCRIPTION.md
  mrp_planned_order_matrix/readme/INSTALL.md
  mrp_planned_order_matrix/readme/USAGE.md
  mrp_planned_order_matrix/security/ir.model.access.csv
  mrp_planned_order_matrix/static/description/icon.png
  mrp_planned_order_matrix/static/description/index.html
  mrp_planned_order_matrix/tests/__init__.py
  mrp_planned_order_matrix/tests/test_mrp_planned_order_matrix.py
  mrp_planned_order_matrix/wizards/__init__.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard.py
  mrp_planned_order_matrix/wizards/mrp_planned_order_wizard_view.xml
Labels: bot is merging ⏳

#1429 [17.0] [IMP] mrp_production_back_to_draft: Workorders back to draft
  mrp_production_back_to_draft/README.rst
  mrp_production_back_to_draft/models/mrp_production.py
  mrp_production_back_to_draft/readme/CONTRIBUTORS.md
  mrp_production_back_to_draft/static/description/index.html
  mrp_production_back_to_draft/tests/test_mrp_return_to_draft.py
Labels: approved, ready to merge, bot is merging ⏳
