Repository OCA/manufacture, pull requests merged in 2024-11, with the labels that each got.

#1367 [16.0][FIX] mrp_multi_level: fix kit/phantom planning
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#1384 [17.0][FIX] mrp_multi_level: fix kit/phantom planning
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1383 [15.0][FIX] mrp_multi_level: fix kit/phantom planning
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/models/mrp_planned_order.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_planned_order_views.xml
  mrp_multi_level/wizards/mrp_inventory_procure.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1369 [16.0][FIX] mrp_multi_level: check for variant bom
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1387 [17.0][FIX] mrp_multi_level: check for variant bom
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1386 [15.0][FIX] mrp_multi_level: check for variant bom
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1390 [14.0][FIX] mrp_bom_attribute_match: Do not empty bom line uom when creating
  mrp_bom_attribute_match/models/mrp_bom.py
Labels: approved, bot is merging ⏳

#1391 [16.0][FIX] mrp_multi_level: readd extensibility hook
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1393 [17.0][FIX] mrp_multi_level: readd extensibility hook
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1392 [15.0][FIX] mrp_multi_level: readd extensibility hook
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1091 [16.0][MIG] mrp_unbuild_subcontracting: Migration to 16.0
  mrp_unbuild_subcontracting/README.rst
  mrp_unbuild_subcontracting/__init__.py
  mrp_unbuild_subcontracting/__manifest__.py
  mrp_unbuild_subcontracting/i18n/it.po
  mrp_unbuild_subcontracting/i18n/mrp_unbuild_subcontracting.pot
  mrp_unbuild_subcontracting/models/__init__.py
  mrp_unbuild_subcontracting/models/mrp_unbuild.py
  mrp_unbuild_subcontracting/models/stock_move.py
  mrp_unbuild_subcontracting/models/stock_picking.py
  mrp_unbuild_subcontracting/readme/CONTRIBUTORS.rst
  mrp_unbuild_subcontracting/readme/DESCRIPTION.rst
  mrp_unbuild_subcontracting/static/description/icon.png
  mrp_unbuild_subcontracting/static/description/index.html
  mrp_unbuild_subcontracting/tests/__init__.py
  mrp_unbuild_subcontracting/tests/test_mrp_unbuild_subcontracting.py
  mrp_unbuild_subcontracting/views/mrp_unbuild_views.xml
  setup/mrp_unbuild_subcontracting/odoo/addons/mrp_unbuild_subcontracting
  setup/mrp_unbuild_subcontracting/setup.py
Labels: work in progress, approved, ready to merge, bot is merging ⏳, stale

#1197 [16.0] [MIG] mrp_bom_widget_section_and_note_one2many
  mrp_bom_widget_section_and_note_one2many/README.rst
  mrp_bom_widget_section_and_note_one2many/__init__.py
  mrp_bom_widget_section_and_note_one2many/__manifest__.py
  mrp_bom_widget_section_and_note_one2many/i18n/fr.po
  mrp_bom_widget_section_and_note_one2many/i18n/it.po
  mrp_bom_widget_section_and_note_one2many/i18n/mrp_bom_widget_section_and_note_one2many.pot
  mrp_bom_widget_section_and_note_one2many/models/__init__.py
  mrp_bom_widget_section_and_note_one2many/models/mrp_bom.py
  mrp_bom_widget_section_and_note_one2many/models/mrp_bom_line.py
  mrp_bom_widget_section_and_note_one2many/readme/CONTRIBUTORS.rst
  mrp_bom_widget_section_and_note_one2many/readme/CREDITS.rst
  mrp_bom_widget_section_and_note_one2many/readme/DESCRIPTION.rst
  mrp_bom_widget_section_and_note_one2many/readme/ROADMAP.rst
  mrp_bom_widget_section_and_note_one2many/readme/USAGE.rst
  mrp_bom_widget_section_and_note_one2many/static/description/icon.png
  mrp_bom_widget_section_and_note_one2many/static/description/index.html
  mrp_bom_widget_section_and_note_one2many/static/description/mrp_bom_widget_add_section_and_note.gif
  mrp_bom_widget_section_and_note_one2many/views/view_mrp_bom.xml
  setup/mrp_bom_widget_section_and_note_one2many/odoo/addons/mrp_bom_widget_section_and_note_one2many
  setup/mrp_bom_widget_section_and_note_one2many/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1398 [15.0][ADD] mrp_production_date_planned_finished_calendar (fixes Mondays CI runs)
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_production_date_planned_finished/models/mrp_production.py
  mrp_production_date_planned_finished_calendar/README.rst
  mrp_production_date_planned_finished_calendar/__init__.py
  mrp_production_date_planned_finished_calendar/__manifest__.py
  mrp_production_date_planned_finished_calendar/models/__init__.py
  mrp_production_date_planned_finished_calendar/models/mrp_production.py
  mrp_production_date_planned_finished_calendar/readme/CONTRIBUTORS.rst
  mrp_production_date_planned_finished_calendar/readme/DESCRIPTION.rst
  mrp_production_date_planned_finished_calendar/static/description/icon.png
  mrp_production_date_planned_finished_calendar/static/description/index.html
  mrp_production_date_planned_finished_calendar/tests/__init__.py
  mrp_production_date_planned_finished_calendar/tests/test_date_planned_finished_calendar.py
  setup/mrp_production_date_planned_finished_calendar/odoo/addons/mrp_production_date_planned_finished_calendar
  setup/mrp_production_date_planned_finished_calendar/setup.py
Labels: bot is merging ⏳

#1401 [16.0][FIX] mrp_multi_level: when a product is a kit do not check rule
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: needs review, approved, bot is merging ⏳

#1395 [18.0][MIG] mrp_warehouse_calendar: Migration to 18.0
  mrp_warehouse_calendar/README.rst
  mrp_warehouse_calendar/__init__.py
  mrp_warehouse_calendar/__manifest__.py
  mrp_warehouse_calendar/i18n/de.po
  mrp_warehouse_calendar/i18n/es.po
  mrp_warehouse_calendar/i18n/it.po
  mrp_warehouse_calendar/i18n/mrp_warehouse_calendar.pot
  mrp_warehouse_calendar/models/__init__.py
  mrp_warehouse_calendar/models/mrp_production.py
  mrp_warehouse_calendar/models/stock_rule.py
  mrp_warehouse_calendar/pyproject.toml
  mrp_warehouse_calendar/readme/CONFIGURE.md
  mrp_warehouse_calendar/readme/CONTRIBUTORS.md
  mrp_warehouse_calendar/readme/DESCRIPTION.md
  mrp_warehouse_calendar/readme/USAGE.md
  mrp_warehouse_calendar/static/description/change_day.gif
  mrp_warehouse_calendar/static/description/developer_mode.gif
  mrp_warehouse_calendar/static/description/icon.png
  mrp_warehouse_calendar/static/description/index.html
  mrp_warehouse_calendar/static/description/manufacturing_order.png
  mrp_warehouse_calendar/static/description/replenish.png
  mrp_warehouse_calendar/static/description/warehouse_management.gif
  mrp_warehouse_calendar/static/description/working_schedules.gif
  mrp_warehouse_calendar/tests/__init__.py
  mrp_warehouse_calendar/tests/test_mrp_warehouse_calendar.py
Labels: bot is merging ⏳

#1402 [15.0][FIX] mrp_multi_level: when a product is a kit do not check rule
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#1403 [17.0][FIX] mrp_multi_level: when a product is a kit do not check rule
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳
