Repository OCA/manufacture, pull requests merged in 2024-03, with the labels that each got.

#1219 [16.0][MIG] quality_control_stock_oca: Migration to 16.0
  quality_control_oca/data/quality_control_data.xml
  quality_control_oca/tests/test_quality_control.py
  quality_control_oca/views/qc_menus.xml
  quality_control_stock_oca/README.rst
  quality_control_stock_oca/__init__.py
  quality_control_stock_oca/__manifest__.py
  quality_control_stock_oca/i18n/ca.po
  quality_control_stock_oca/i18n/de.po
  quality_control_stock_oca/i18n/el_GR.po
  quality_control_stock_oca/i18n/es.po
  quality_control_stock_oca/i18n/es_AR.po
  quality_control_stock_oca/i18n/es_ES.po
  quality_control_stock_oca/i18n/es_MX.po
  quality_control_stock_oca/i18n/eu.po
  quality_control_stock_oca/i18n/fi.po
  quality_control_stock_oca/i18n/fr.po
  quality_control_stock_oca/i18n/fr_CH.po
  quality_control_stock_oca/i18n/fr_FR.po
  quality_control_stock_oca/i18n/gl.po
  quality_control_stock_oca/i18n/hr.po
  quality_control_stock_oca/i18n/hr_HR.po
  quality_control_stock_oca/i18n/it.po
  quality_control_stock_oca/i18n/nl.po
  quality_control_stock_oca/i18n/nl_NL.po
  quality_control_stock_oca/i18n/pt.po
  quality_control_stock_oca/i18n/pt_BR.po
  quality_control_stock_oca/i18n/quality_control_stock_oca.pot
  quality_control_stock_oca/i18n/ro.po
  quality_control_stock_oca/i18n/ru.po
  quality_control_stock_oca/i18n/sk.po
  quality_control_stock_oca/i18n/sl.po
  quality_control_stock_oca/i18n/tr.po
  quality_control_stock_oca/i18n/tr_TR.po
  quality_control_stock_oca/i18n/vi_VN.po
  quality_control_stock_oca/i18n/zh_CN.po
  quality_control_stock_oca/models/__init__.py
  quality_control_stock_oca/models/qc_inspection.py
  quality_control_stock_oca/models/qc_trigger.py
  quality_control_stock_oca/models/stock_picking.py
  quality_control_stock_oca/models/stock_picking_type.py
  quality_control_stock_oca/models/stock_production_lot.py
  quality_control_stock_oca/readme/CONTRIBUTORS.rst
  quality_control_stock_oca/readme/DESCRIPTION.rst
  quality_control_stock_oca/readme/ROADMAP.rst
  quality_control_stock_oca/static/description/icon.png
  quality_control_stock_oca/static/description/index.html
  quality_control_stock_oca/tests/__init__.py
  quality_control_stock_oca/tests/test_quality_control_stock.py
  quality_control_stock_oca/views/qc_inspection_view.xml
  quality_control_stock_oca/views/qc_trigger_view.xml
  quality_control_stock_oca/views/stock_picking_view.xml
  quality_control_stock_oca/views/stock_production_lot_view.xml
  setup/quality_control_stock_oca/odoo/addons/quality_control_stock_oca
  setup/quality_control_stock_oca/setup.py
Labels: approved, bot is merging ⏳

#1179 [16.0][FIX] mrp_subcontracting_skip_no_negative: consider move with multiple productions
  mrp_subcontracting_skip_no_negative/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1038 [16.0][ADD] mrp_workcenter_cost
  mrp_workcenter_cost/README.rst
  mrp_workcenter_cost/__init__.py
  mrp_workcenter_cost/__manifest__.py
  mrp_workcenter_cost/models/__init__.py
  mrp_workcenter_cost/models/mrp_production.py
  mrp_workcenter_cost/models/product_template.py
  mrp_workcenter_cost/readme/CONTRIBUTORS.rst
  mrp_workcenter_cost/readme/DESCRIPTION.rst
  mrp_workcenter_cost/readme/USAGE.rst
  mrp_workcenter_cost/static/description/icon.png
  mrp_workcenter_cost/static/description/index.html
  mrp_workcenter_cost/tests/__init__.py
  mrp_workcenter_cost/tests/test_mrp_workcenter_cost.py
  mrp_workcenter_cost/views/product_template.xml
  setup/mrp_workcenter_cost/odoo/addons/mrp_workcenter_cost
  setup/mrp_workcenter_cost/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1093 [16.0][MIG] mrp_default_workorder_time: Migration to 16.0
  mrp_default_workorder_time/README.rst
  mrp_default_workorder_time/__init__.py
  mrp_default_workorder_time/__manifest__.py
  mrp_default_workorder_time/models/__init__.py
  mrp_default_workorder_time/models/company.py
  mrp_default_workorder_time/models/res_config_settings.py
  mrp_default_workorder_time/models/workorder.py
  mrp_default_workorder_time/readme/CONTRIBUTORS.rst
  mrp_default_workorder_time/readme/DESCRIPTION.rst
  mrp_default_workorder_time/readme/USAGE.rst
  mrp_default_workorder_time/static/description/index.html
  mrp_default_workorder_time/tests/__init__.py
  mrp_default_workorder_time/tests/test_workorder_times.py
  mrp_default_workorder_time/views/res_config_settings_view.xml
  setup/mrp_default_workorder_time/odoo/addons/mrp_default_workorder_time
  setup/mrp_default_workorder_time/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1217 [14.0][MIG] quality_control_team_oca: Migration to 14.0
  quality_control_team_oca/README.rst
  quality_control_team_oca/__init__.py
  quality_control_team_oca/__manifest__.py
  quality_control_team_oca/data/quality_control_team_data.xml
  quality_control_team_oca/i18n/de.po
  quality_control_team_oca/i18n/it.po
  quality_control_team_oca/i18n/pt.po
  quality_control_team_oca/i18n/pt_BR.po
  quality_control_team_oca/i18n/quality_control_team.pot
  quality_control_team_oca/i18n/quality_control_team_oca.pot
  quality_control_team_oca/models/__init__.py
  quality_control_team_oca/models/qc_team.py
  quality_control_team_oca/models/res_partner.py
  quality_control_team_oca/models/res_user.py
  quality_control_team_oca/readme/CONFIGURE.rst
  quality_control_team_oca/readme/CONTRIBUTORS.rst
  quality_control_team_oca/readme/DESCRIPTION.rst
  quality_control_team_oca/security/ir.model.access.csv
  quality_control_team_oca/static/description/icon.png
  quality_control_team_oca/static/description/icon.svg
  quality_control_team_oca/static/description/index.html
  quality_control_team_oca/tests/__init__.py
  quality_control_team_oca/tests/test_quality_control_team.py
  quality_control_team_oca/views/qc_team_dashboard.xml
  quality_control_team_oca/views/qc_team_view.xml
  setup/quality_control_team_oca/odoo/addons/quality_control_team_oca
  setup/quality_control_team_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1222 [14.0] [FIX] mrp_bom_attribute_match_duplicate_kit: use correct uom
  mrp_bom_attribute_match_duplicate_kit/tests/test_product_template_kit_wizard.py
  mrp_bom_attribute_match_duplicate_kit/wizard/product_template_kit_wizard.py
Labels: approved, bot is merging ⏳

#1223 [16.0][FIX] mrp_packaging_default: Propagate packaging in stock move
  mrp_packaging_default/models/stock_move.py
Labels: bot is merging ⏳

#1232 [15.0][MIG] account_move_line_mrp_info
  account_move_line_mrp_info/README.rst
  account_move_line_mrp_info/__init__.py
  account_move_line_mrp_info/__manifest__.py
  account_move_line_mrp_info/hooks.py
  account_move_line_mrp_info/i18n/account_move_line_mrp_info.pot
  account_move_line_mrp_info/i18n/ca.po
  account_move_line_mrp_info/i18n/es.po
  account_move_line_mrp_info/i18n/it.po
  account_move_line_mrp_info/models/__init__.py
  account_move_line_mrp_info/models/account_move_line.py
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/readme/CONTRIBUTORS.rst
  account_move_line_mrp_info/readme/DESCRIPTION.rst
  account_move_line_mrp_info/readme/USAGE.rst
  account_move_line_mrp_info/security/ir.model.access.csv
  account_move_line_mrp_info/static/description/icon.png
  account_move_line_mrp_info/static/description/index.html
  account_move_line_mrp_info/tests/__init__.py
  account_move_line_mrp_info/tests/test_mrp_journal_items.py
  account_move_line_mrp_info/views/account_move_line_view.xml
  account_move_line_mrp_info/views/mrp_production_view.xml
  setup/account_move_line_mrp_info/odoo/addons/account_move_line_mrp_info
  setup/account_move_line_mrp_info/setup.py
Labels: approved, bot is merging ⏳

#1236 [14.0] [FIX] mrp_bom_attribute_match: modify permission error
  mrp_bom_attribute_match/models/mrp_bom.py
Labels: approved, bot is merging ⏳

#1238 [14.0] [FIX] mrp_bom_attribute_match_semifinished_product: access error
  mrp_bom_attribute_match_semifinished_product/models/product_template.py
Labels: bot is merging ⏳

#1228 [17.0][MIG] mrp_warehouse_calendar
  mrp_warehouse_calendar/README.rst
  mrp_warehouse_calendar/__init__.py
  mrp_warehouse_calendar/__manifest__.py
  mrp_warehouse_calendar/i18n/de.po
  mrp_warehouse_calendar/i18n/es.po
  mrp_warehouse_calendar/i18n/it.po
  mrp_warehouse_calendar/i18n/mrp_warehouse_calendar.pot
  mrp_warehouse_calendar/models/__init__.py
  mrp_warehouse_calendar/models/mrp_production.py
  mrp_warehouse_calendar/models/stock_rule.py
  mrp_warehouse_calendar/pyproject.toml
  mrp_warehouse_calendar/readme/CONFIGURE.md
  mrp_warehouse_calendar/readme/CONTRIBUTORS.md
  mrp_warehouse_calendar/readme/DESCRIPTION.md
  mrp_warehouse_calendar/readme/USAGE.md
  mrp_warehouse_calendar/static/description/icon.png
  mrp_warehouse_calendar/static/description/index.html
  mrp_warehouse_calendar/tests/__init__.py
  mrp_warehouse_calendar/tests/test_mrp_warehouse_calendar.py
Labels: approved, ready to merge, bot is merging ⏳

#1226 [17.0][MIG] mrp_bom_tracking: Migration to 17.0
  mrp_bom_tracking/README.rst
  mrp_bom_tracking/__init__.py
  mrp_bom_tracking/__manifest__.py
  mrp_bom_tracking/i18n/de.po
  mrp_bom_tracking/i18n/es.po
  mrp_bom_tracking/i18n/it.po
  mrp_bom_tracking/i18n/mrp_bom_tracking.pot
  mrp_bom_tracking/models/__init__.py
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/pyproject.toml
  mrp_bom_tracking/readme/CONTRIBUTORS.md
  mrp_bom_tracking/readme/DESCRIPTION.md
  mrp_bom_tracking/static/description/icon.png
  mrp_bom_tracking/static/description/index.html
  mrp_bom_tracking/tests/__init__.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
  mrp_bom_tracking/views/bom_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1185 [ADD] mrp_bom_line_formula_quantity
  mrp_bom_line_formula_quantity/README.rst
  mrp_bom_line_formula_quantity/__init__.py
  mrp_bom_line_formula_quantity/__manifest__.py
  mrp_bom_line_formula_quantity/i18n/it.po
  mrp_bom_line_formula_quantity/models/__init__.py
  mrp_bom_line_formula_quantity/models/mrp_bom_line.py
  mrp_bom_line_formula_quantity/models/mrp_production.py
  mrp_bom_line_formula_quantity/readme/CONFIGURE.rst
  mrp_bom_line_formula_quantity/readme/DESCRIPTION.rst
  mrp_bom_line_formula_quantity/readme/USAGE.rst
  mrp_bom_line_formula_quantity/static/description/images/bom.png
  mrp_bom_line_formula_quantity/static/description/images/product_attribute.png
  mrp_bom_line_formula_quantity/static/description/images/product_tab_attributes.png
  mrp_bom_line_formula_quantity/static/description/images/production_order.png
  mrp_bom_line_formula_quantity/static/description/images/sale_order.png
  mrp_bom_line_formula_quantity/static/description/images/website_sale_product.png
  mrp_bom_line_formula_quantity/static/description/index.html
  mrp_bom_line_formula_quantity/tests/__init__.py
  mrp_bom_line_formula_quantity/tests/test_mrp_bom_line.py
  mrp_bom_line_formula_quantity/tests/test_mrp_production.py
  mrp_bom_line_formula_quantity/views/mrp_bom_line_views.xml
  mrp_bom_line_formula_quantity/views/mrp_bom_views.xml
  setup/mrp_bom_line_formula_quantity/odoo/addons/mrp_bom_line_formula_quantity
  setup/mrp_bom_line_formula_quantity/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1209 [16.0][MIG] mrp_subcontracting_bom_dual_use: Migration to 16.0
  mrp_subcontracting_bom_dual_use/README.rst
  mrp_subcontracting_bom_dual_use/__init__.py
  mrp_subcontracting_bom_dual_use/__manifest__.py
  mrp_subcontracting_bom_dual_use/i18n/es.po
  mrp_subcontracting_bom_dual_use/i18n/it.po
  mrp_subcontracting_bom_dual_use/i18n/mrp_subcontracting_bom_dual_use.pot
  mrp_subcontracting_bom_dual_use/models/__init__.py
  mrp_subcontracting_bom_dual_use/models/mrp_bom.py
  mrp_subcontracting_bom_dual_use/models/mrp_production.py
  mrp_subcontracting_bom_dual_use/readme/CONTRIBUTORS.rst
  mrp_subcontracting_bom_dual_use/readme/DESCRIPTION.rst
  mrp_subcontracting_bom_dual_use/readme/USAGE.rst
  mrp_subcontracting_bom_dual_use/static/description/icon.png
  mrp_subcontracting_bom_dual_use/static/description/index.html
  mrp_subcontracting_bom_dual_use/tests/__init__.py
  mrp_subcontracting_bom_dual_use/tests/test_mrp_subcontracting_bom_dual_use.py
  mrp_subcontracting_bom_dual_use/views/mrp_bom_view.xml
  setup/mrp_subcontracting_bom_dual_use/odoo/addons/mrp_subcontracting_bom_dual_use
  setup/mrp_subcontracting_bom_dual_use/setup.py
Labels: approved, ready to merge, bot is merging ⏳
