Repository OCA/manufacture, pull requests merged in 2024-01, with the labels that each got.

#1060 [16.0][MIG] mrp_lot_number_propagation
  mrp_lot_number_propagation/README.rst
  mrp_lot_number_propagation/__init__.py
  mrp_lot_number_propagation/__manifest__.py
  mrp_lot_number_propagation/i18n/it.po
  mrp_lot_number_propagation/i18n/mrp_lot_number_propagation.pot
  mrp_lot_number_propagation/models/__init__.py
  mrp_lot_number_propagation/models/mrp_bom.py
  mrp_lot_number_propagation/models/mrp_bom_line.py
  mrp_lot_number_propagation/models/mrp_production.py
  mrp_lot_number_propagation/models/product_product.py
  mrp_lot_number_propagation/models/product_template.py
  mrp_lot_number_propagation/models/stock_move.py
  mrp_lot_number_propagation/readme/CONTRIBUTORS.rst
  mrp_lot_number_propagation/readme/DESCRIPTION.rst
  mrp_lot_number_propagation/readme/ROADMAP.rst
  mrp_lot_number_propagation/static/description/icon.png
  mrp_lot_number_propagation/static/description/index.html
  mrp_lot_number_propagation/tests/__init__.py
  mrp_lot_number_propagation/tests/common.py
  mrp_lot_number_propagation/tests/test_mrp_bom.py
  mrp_lot_number_propagation/tests/test_mrp_production.py
  mrp_lot_number_propagation/views/mrp_bom.xml
  mrp_lot_number_propagation/views/mrp_production.xml
  setup/mrp_lot_number_propagation/odoo/addons/mrp_lot_number_propagation
  setup/mrp_lot_number_propagation/setup.py
Labels: approved, bot is merging ⏳

#1176 [14.0] [FIX] mrp_bom_attribute_match_duplicate_kit: wrong UOM
  mrp_bom_attribute_match_duplicate_kit/README.rst
  mrp_bom_attribute_match_duplicate_kit/__manifest__.py
  mrp_bom_attribute_match_duplicate_kit/demo/res_users_demo.xml
  mrp_bom_attribute_match_duplicate_kit/readme/USAGE.rst
  mrp_bom_attribute_match_duplicate_kit/security/ir.model.access.csv
  mrp_bom_attribute_match_duplicate_kit/security/security.xml
  mrp_bom_attribute_match_duplicate_kit/static/description/index.html
  mrp_bom_attribute_match_duplicate_kit/views/product_template_views.xml
  mrp_bom_attribute_match_duplicate_kit/wizard/product_template_kit_wizard.py
Labels: approved, bot is merging ⏳

#1170 [ADD] mrp_packaging_default: product packaging data in MRP
  mrp_packaging_default/README.rst
  mrp_packaging_default/__init__.py
  mrp_packaging_default/__manifest__.py
  mrp_packaging_default/i18n/.empty
  mrp_packaging_default/models/__init__.py
  mrp_packaging_default/models/mrp_bom_line.py
  mrp_packaging_default/models/stock_move.py
  mrp_packaging_default/readme/CONFIGURE.md
  mrp_packaging_default/readme/CONTEXT.md
  mrp_packaging_default/readme/CONTRIBUTORS.md
  mrp_packaging_default/readme/DESCRIPTION.md
  mrp_packaging_default/readme/USAGE.md
  mrp_packaging_default/static/description/icon.png
  mrp_packaging_default/static/description/index.html
  mrp_packaging_default/tests/__init__.py
  mrp_packaging_default/tests/test_mrp_packaging_default.py
  mrp_packaging_default/views/mrp_bom_view.xml
  mrp_packaging_default/views/mrp_production_view.xml
  setup/mrp_packaging_default/odoo/addons/mrp_packaging_default
  setup/mrp_packaging_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1180 [14.0] Add module mrp_repair_reuse_component
  mrp_repair_reuse_component/README.rst
  mrp_repair_reuse_component/__init__.py
  mrp_repair_reuse_component/__manifest__.py
  mrp_repair_reuse_component/models/__init__.py
  mrp_repair_reuse_component/models/product.py
  mrp_repair_reuse_component/readme/CONTRIBUTORS.md
  mrp_repair_reuse_component/readme/DESCRIPTION.md
  mrp_repair_reuse_component/static/description/index.html
  mrp_repair_reuse_component/tests/__init__.py
  mrp_repair_reuse_component/tests/test_mrp_repair_reuse_component.py
  setup/mrp_repair_reuse_component/odoo/addons/mrp_repair_reuse_component
  setup/mrp_repair_reuse_component/setup.py
Labels: approved, bot is merging ⏳

#1123 [15.0][IMP] mrp_multi_level: safety stock
  mrp_multi_level/README.rst
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/readme/CONFIGURE.rst
  mrp_multi_level/readme/CONTRIBUTORS.rst
  mrp_multi_level/static/description/index.html
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: needs review, approved, bot is merging ⏳

#1183 [15.0][FIX] mrp_multi_level: starting qty on hand wrong when using lots
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1186 [16.0][IMP] mrp_multi_level: safety stock
  mrp_multi_level/README.rst
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/readme/CONTRIBUTORS.rst
  mrp_multi_level/static/description/index.html
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1184 [16.0][FIX] mrp_multi_level: starting qty on hand wrong when using lots
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: needs review, bot is merging ⏳

#1187 [15.0][IMP] mrp_multi_level: add date to default grouping filters
  mrp_multi_level/views/mrp_inventory_views.xml
Labels: bot is merging ⏳

#1188 [16.0][IMP] mrp_multi_level: add date to default grouping filters
  mrp_multi_level/views/mrp_inventory_views.xml
Labels: bot is merging ⏳

#1191 [15.0][FIX] mrp_multi_level: variable 'move' referenced before assignment
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1196 [16.0][FIX] mrp_multi_level: ariable 'move' referenced before assignment
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳
