Repository OCA/manufacture, pull requests merged in 2024-07, with the labels that each got.

#1296 [14.0][ADD] mrp_production_back_to_draft
  mrp_production_back_to_draft/README.rst
  mrp_production_back_to_draft/__init__.py
  mrp_production_back_to_draft/__manifest__.py
  mrp_production_back_to_draft/models/__init__.py
  mrp_production_back_to_draft/models/mrp_production.py
  mrp_production_back_to_draft/readme/CONTRIBUTORS.rst
  mrp_production_back_to_draft/readme/DESCRIPTION.rst
  mrp_production_back_to_draft/static/description/icon.png
  mrp_production_back_to_draft/static/description/index.html
  mrp_production_back_to_draft/tests/__init__.py
  mrp_production_back_to_draft/tests/test_mrp_return_to_draft.py
  mrp_production_back_to_draft/views/mrp_production_views.xml
  setup/mrp_production_back_to_draft/odoo/addons/mrp_production_back_to_draft
  setup/mrp_production_back_to_draft/setup.py
Labels: approved, bot is merging ⏳

#1246 [16.0][ADD] mrp_bom_image
  mrp_bom_image/README.rst
  mrp_bom_image/__init__.py
  mrp_bom_image/__manifest__.py
  mrp_bom_image/models/__init__.py
  mrp_bom_image/models/mrp_bom.py
  mrp_bom_image/readme/DESCRIPTION.rst
  mrp_bom_image/static/description/index.html
  mrp_bom_image/static/description/mrp_bom_image.png
  mrp_bom_image/static/description/mrp_bom_image_kanban.png
  mrp_bom_image/views/view_mrp_bom.xml
  setup/mrp_bom_image/odoo/addons/mrp_bom_image
  setup/mrp_bom_image/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1306 [16.0][IMP] mrp_multi_level: add MRP Area smart button on stock locations
  mrp_multi_level/models/stock_location.py
  mrp_multi_level/views/stock_location_views.xml
Labels: approved, bot is merging ⏳

#1308 [17.0][FW][IMP] mrp_multi_level: add MRP Area smart button on stock locations
  mrp_multi_level/models/stock_location.py
  mrp_multi_level/views/stock_location_views.xml
Labels: bot is merging ⏳

#1298 [15.0] mrp_sale_info: Materialize link between sale order lines and created MOs
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/sale_order_line.py
  mrp_sale_info/models/stock_move.py
  mrp_sale_info/tests/test_mrp_sale_info.py
Labels: approved, ready to merge, bot is merging ⏳

#1309 [16.0][IMP] mrp_multi_level: use area from component in the explosion vals
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#1316 [17.0][FW][IMP] mrp_multi_level: use area from component in the explosion vals
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1315 [15.0][BKP][IMP] mrp_multi_level: use area from component in the explosion vals
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1318 [16.0][IMP] mrp_multi_level: fix typo
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: Pending to fw/back port

#1230 [16.0][ADD] mrp_bom_tag
  mrp_bom_tag/README.rst
  mrp_bom_tag/__init__.py
  mrp_bom_tag/__manifest__.py
  mrp_bom_tag/demo/mrp_bom_tag.xml
  mrp_bom_tag/i18n/fr.po
  mrp_bom_tag/models/__init__.py
  mrp_bom_tag/models/mrp_bom.py
  mrp_bom_tag/models/mrp_bom_tag.py
  mrp_bom_tag/readme/CONFIGURE.rst
  mrp_bom_tag/readme/CONTRIBUTORS.rst
  mrp_bom_tag/readme/DESCRIPTION.rst
  mrp_bom_tag/security/ir.model.access.csv
  mrp_bom_tag/security/ir_rule.xml
  mrp_bom_tag/static/description/bom_tag_configuration.png
  mrp_bom_tag/static/description/bom_with_tag.png
  mrp_bom_tag/static/description/index.html
  mrp_bom_tag/tests/__init__.py
  mrp_bom_tag/tests/test_bom_tag.py
  mrp_bom_tag/views/view_mrp_bom.xml
  mrp_bom_tag/views/view_mrp_bom_tag.xml
  setup/mrp_bom_tag/odoo/addons/mrp_bom_tag
  setup/mrp_bom_tag/setup.py
Labels: approved, bot is merging ⏳, stale

#1321 [17.0][MIG] mrp_production_note: Migration to 17.0
  mrp_production_note/README.rst
  mrp_production_note/__init__.py
  mrp_production_note/__manifest__.py
  mrp_production_note/i18n/de.po
  mrp_production_note/i18n/es.po
  mrp_production_note/i18n/es_MX.po
  mrp_production_note/i18n/fi.po
  mrp_production_note/i18n/fr.po
  mrp_production_note/i18n/gl.po
  mrp_production_note/i18n/hr.po
  mrp_production_note/i18n/hr_HR.po
  mrp_production_note/i18n/it.po
  mrp_production_note/i18n/lt.po
  mrp_production_note/i18n/mrp_production_note.pot
  mrp_production_note/i18n/nl_NL.po
  mrp_production_note/i18n/pt_BR.po
  mrp_production_note/i18n/ro.po
  mrp_production_note/i18n/sl.po
  mrp_production_note/i18n/tr.po
  mrp_production_note/i18n/tr_TR.po
  mrp_production_note/i18n/vi_VN.po
  mrp_production_note/i18n/zh_CN.po
  mrp_production_note/models/__init__.py
  mrp_production_note/models/mrp_production.py
  mrp_production_note/pyproject.toml
  mrp_production_note/readme/CONTRIBUTORS.md
  mrp_production_note/readme/DESCRIPTION.md
  mrp_production_note/readme/USAGE.md
  mrp_production_note/static/description/icon.png
  mrp_production_note/static/description/index.html
  mrp_production_note/views/mrp_production_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1326 [16.0][IMP] mrp_multi_level: add hooks to improve extensibility
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳, Pending to fw/back port

#1323 [16.0][MIG] quality_control_mrp_oca: Migration to 16.0
  quality_control_mrp_oca/README.rst
  quality_control_mrp_oca/__init__.py
  quality_control_mrp_oca/__manifest__.py
  quality_control_mrp_oca/data/quality_control_mrp_data.xml
  quality_control_mrp_oca/i18n/ca.po
  quality_control_mrp_oca/i18n/de.po
  quality_control_mrp_oca/i18n/el_GR.po
  quality_control_mrp_oca/i18n/es.po
  quality_control_mrp_oca/i18n/es_ES.po
  quality_control_mrp_oca/i18n/es_MX.po
  quality_control_mrp_oca/i18n/eu.po
  quality_control_mrp_oca/i18n/fi.po
  quality_control_mrp_oca/i18n/fr.po
  quality_control_mrp_oca/i18n/fr_CH.po
  quality_control_mrp_oca/i18n/fr_FR.po
  quality_control_mrp_oca/i18n/gl.po
  quality_control_mrp_oca/i18n/hr.po
  quality_control_mrp_oca/i18n/hr_HR.po
  quality_control_mrp_oca/i18n/it.po
  quality_control_mrp_oca/i18n/nl.po
  quality_control_mrp_oca/i18n/nl_NL.po
  quality_control_mrp_oca/i18n/pt.po
  quality_control_mrp_oca/i18n/pt_BR.po
  quality_control_mrp_oca/i18n/quality_control_mrp_oca.pot
  quality_control_mrp_oca/i18n/ro.po
  quality_control_mrp_oca/i18n/ru.po
  quality_control_mrp_oca/i18n/sk.po
  quality_control_mrp_oca/i18n/sl.po
  quality_control_mrp_oca/i18n/tr.po
  quality_control_mrp_oca/i18n/tr_TR.po
  quality_control_mrp_oca/i18n/vi_VN.po
  quality_control_mrp_oca/i18n/zh_CN.po
  quality_control_mrp_oca/models/__init__.py
  quality_control_mrp_oca/models/mrp_production.py
  quality_control_mrp_oca/models/qc_inspection.py
  quality_control_mrp_oca/readme/CONTRIBUTORS.rst
  quality_control_mrp_oca/readme/DESCRIPTION.rst
  quality_control_mrp_oca/static/description/icon.png
  quality_control_mrp_oca/static/description/index.html
  quality_control_mrp_oca/tests/__init__.py
  quality_control_mrp_oca/tests/test_quality_control_mrp.py
  quality_control_mrp_oca/views/mrp_production_view.xml
  quality_control_mrp_oca/views/qc_inspection_view.xml
  setup/quality_control_mrp_oca/odoo/addons/quality_control_mrp_oca
  setup/quality_control_mrp_oca/setup.py
Labels: approved, bot is merging ⏳

#1328 [17.0][IMP] mrp_multi_level: add hooks to improve extensibility
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1329 [15.0][IMP] mrp_multi_level: add hooks to improve extensibility
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1330 [16.0][IMP] mrp_multi_level: hook for method to get rule
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1332 [17.0][IMP] mrp_multi_level: hook for method to get rule
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1331 [15.0][IMP] mrp_multi_level: hook for method to get rule
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳
