Repository OCA/manufacture, pull requests merged in 2024-10, with the labels that each got.

#1363 [17.0][ADD] quality_control_oca_timesheet: New module quality_control_oca_timesheet
  quality_control_oca_timesheet/README.rst
  quality_control_oca_timesheet/__init__.py
  quality_control_oca_timesheet/__manifest__.py
  quality_control_oca_timesheet/i18n/ca.po
  quality_control_oca_timesheet/i18n/es.po
  quality_control_oca_timesheet/models/__init__.py
  quality_control_oca_timesheet/models/hr_timesheet.py
  quality_control_oca_timesheet/models/qc_inspection.py
  quality_control_oca_timesheet/pyproject.toml
  quality_control_oca_timesheet/readme/CONTRIBUTORS.md
  quality_control_oca_timesheet/readme/DESCRIPTION.md
  quality_control_oca_timesheet/readme/USAGE.md
  quality_control_oca_timesheet/static/description/icon.png
  quality_control_oca_timesheet/static/description/icon.svg
  quality_control_oca_timesheet/static/description/index.html
  quality_control_oca_timesheet/tests/__init__.py
  quality_control_oca_timesheet/tests/test_quality_control_oca_timesheet.py
  quality_control_oca_timesheet/views/qc_inspection_view.xml
Labels: approved, bot is merging ⏳

#1351 [16.0][FIX] quality_control_mrp_oca: mrp.production Inspections smart button error
  quality_control_mrp_oca/views/mrp_production_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1346 [17.0][ADD] mrp_repair_order: New module mrp_repair_order
  mrp_repair_order/README.rst
  mrp_repair_order/__init__.py
  mrp_repair_order/__manifest__.py
  mrp_repair_order/i18n/ca_ES.po
  mrp_repair_order/i18n/es.po
  mrp_repair_order/models/__init__.py
  mrp_repair_order/models/mrp.py
  mrp_repair_order/models/repair.py
  mrp_repair_order/pyproject.toml
  mrp_repair_order/readme/CONTRIBUTORS.md
  mrp_repair_order/readme/DESCRIPTION.md
  mrp_repair_order/readme/USAGE.md
  mrp_repair_order/static/description/icon.png
  mrp_repair_order/static/description/icon.svg
  mrp_repair_order/static/description/index.html
  mrp_repair_order/tests/__init__.py
  mrp_repair_order/tests/test_mrp_repair_order.py
  mrp_repair_order/views/mrp_production_views.xml
  mrp_repair_order/views/repair_views.xml
Labels: approved, bot is merging ⏳

#1349 [17.0][ADD] mrp_mass_production_order: New module mrp_mass_production_order
  mrp_mass_production_order/README.rst
  mrp_mass_production_order/__init__.py
  mrp_mass_production_order/__manifest__.py
  mrp_mass_production_order/i18n/ca_ES.po
  mrp_mass_production_order/i18n/es.po
  mrp_mass_production_order/pyproject.toml
  mrp_mass_production_order/readme/CONTRIBUTORS.md
  mrp_mass_production_order/readme/DESCRIPTION.md
  mrp_mass_production_order/readme/USAGE.md
  mrp_mass_production_order/security/ir.model.access.csv
  mrp_mass_production_order/static/description/icon.png
  mrp_mass_production_order/static/description/icon.svg
  mrp_mass_production_order/static/description/index.html
  mrp_mass_production_order/tests/__init__.py
  mrp_mass_production_order/tests/test_mrp_mass_production_order.py
  mrp_mass_production_order/wizards/__init__.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳

#1370 [16.0][IMP] mrp_multi_level: mrp cleanup performance
  mrp_multi_level/models/mrp_production.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#1379 [15.0][IMP] mrp_multi_level: mrp cleanup performance
  mrp_multi_level/models/mrp_production.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1380 [17.0][IMP] mrp_multi_level: mrp cleanup performance
  mrp_multi_level/models/mrp_production.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳
