Repository OCA/manufacture, pull requests merged in 2024-02, with the labels that each got.

#1194 [16.0][MIG] ``mrp_tag``
  mrp_tag/README.rst
  mrp_tag/__init__.py
  mrp_tag/__manifest__.py
  mrp_tag/i18n/it.po
  mrp_tag/i18n/mrp_tag.pot
  mrp_tag/models/__init__.py
  mrp_tag/models/mrp_production.py
  mrp_tag/models/mrp_tag.py
  mrp_tag/readme/CONTRIBUTORS.rst
  mrp_tag/readme/DESCRIPTION.rst
  mrp_tag/readme/USAGE.rst
  mrp_tag/security/ir.model.access.csv
  mrp_tag/static/description/icon.png
  mrp_tag/static/description/index.html
  mrp_tag/views/mrp_production_view.xml
  mrp_tag/views/mrp_tag_view.xml
  setup/mrp_tag/odoo/addons/mrp_tag
  setup/mrp_tag/setup.py
Labels: bot is merging ⏳

#1193 [15.0][IMP] ``mrp_tag``: add parent tags
  mrp_tag/models/mrp_tag.py
  mrp_tag/views/mrp_production_view.xml
  mrp_tag/views/mrp_tag_view.xml
Labels: approved, bot is merging ⏳

#1201 [16.0][FIX] mrp_multi_level: wrong safety stock intial order in grouped demand mode
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳

#1202 [13.0][BACKPORT] mrp_multi_level: safety stock
  mrp_multi_level/README.rst
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/readme/CONFIGURE.rst
  mrp_multi_level/readme/CONTRIBUTORS.rst
  mrp_multi_level/static/description/index.html
  mrp_multi_level/tests/common.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳, Pending to fw/back port

#1115 [MIG] mrp_attachment_mgmt: Migration to 16.0
  mrp_attachment_mgmt/README.rst
  mrp_attachment_mgmt/__init__.py
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/i18n/es.po
  mrp_attachment_mgmt/i18n/it.po
  mrp_attachment_mgmt/i18n/mrp_attachment_mgmt.pot
  mrp_attachment_mgmt/models/__init__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/models/mrp_production.py
  mrp_attachment_mgmt/models/mrp_workorder.py
  mrp_attachment_mgmt/models/product.py
  mrp_attachment_mgmt/readme/CONFIGURE.rst
  mrp_attachment_mgmt/readme/CONTRIBUTORS.rst
  mrp_attachment_mgmt/readme/DESCRIPTION.rst
  mrp_attachment_mgmt/readme/USAGE.rst
  mrp_attachment_mgmt/static/description/icon.png
  mrp_attachment_mgmt/static/description/index.html
  mrp_attachment_mgmt/tests/__init__.py
  mrp_attachment_mgmt/tests/common.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
  mrp_attachment_mgmt/views/mrp_bom_view.xml
  mrp_attachment_mgmt/views/mrp_production_views.xml
  mrp_attachment_mgmt/views/product_views.xml
  mrp_attachment_mgmt/views/workorder_attachments_views.xml
  setup/mrp_attachment_mgmt/odoo/addons/mrp_attachment_mgmt
  setup/mrp_attachment_mgmt/setup.py
Labels: approved, bot is merging ⏳

#1190 [IMP] mrp_bom_hierarchy: Open form view of child BoM when there is only 1 child BoM
  mrp_bom_hierarchy/model/mrp_bom.py
Labels: approved, bot is merging ⏳

#1212 [13.0][MIG] quality_control_team_oca: Migration to 13.0
  quality_control_team_oca/README.rst
  quality_control_team_oca/__init__.py
  quality_control_team_oca/__manifest__.py
  quality_control_team_oca/data/quality_control_team_data.xml
  quality_control_team_oca/i18n/de.po
  quality_control_team_oca/i18n/it.po
  quality_control_team_oca/i18n/pt.po
  quality_control_team_oca/i18n/pt_BR.po
  quality_control_team_oca/i18n/quality_control_team.pot
  quality_control_team_oca/models/__init__.py
  quality_control_team_oca/models/qc_team.py
  quality_control_team_oca/models/res_partner.py
  quality_control_team_oca/models/res_user.py
  quality_control_team_oca/readme/CONFIGURE.rst
  quality_control_team_oca/readme/CONTRIBUTORS.rst
  quality_control_team_oca/readme/DESCRIPTION.rst
  quality_control_team_oca/security/ir.model.access.csv
  quality_control_team_oca/static/description/icon.png
  quality_control_team_oca/static/description/icon.svg
  quality_control_team_oca/static/description/index.html
  quality_control_team_oca/tests/__init__.py
  quality_control_team_oca/tests/test_quality_control_team.py
  quality_control_team_oca/views/qc_team_dashboard.xml
  quality_control_team_oca/views/qc_team_view.xml
  setup/quality_control_team_oca/odoo/addons/quality_control_team_oca
  setup/quality_control_team_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1220 [16.0][FIX] mrp_restrict_lot: Change SavepointCase to TransactionCase
  mrp_restrict_lot/tests/test_manufaturing_lot.py
Labels: bot is merging ⏳
