Repository OCA/manufacture, pull requests merged in 2025-06, with the labels that each got.

#1538 [14.0][IMP][mrp_bom_attribute_match] improve missing attribute message
  mrp_bom_attribute_match/models/mrp_bom.py
Labels: approved, ready to merge, bot is merging ⏳

#1420 [18.0][MIG] mrp_tag: Migration to 18.0
  mrp_tag/README.rst
  mrp_tag/__init__.py
  mrp_tag/__manifest__.py
  mrp_tag/i18n/es.po
  mrp_tag/i18n/it.po
  mrp_tag/i18n/mrp_tag.pot
  mrp_tag/models/__init__.py
  mrp_tag/models/mrp_production.py
  mrp_tag/models/mrp_tag.py
  mrp_tag/pyproject.toml
  mrp_tag/readme/CONTRIBUTORS.md
  mrp_tag/readme/DESCRIPTION.md
  mrp_tag/readme/USAGE.md
  mrp_tag/security/ir.model.access.csv
  mrp_tag/static/description/icon.png
  mrp_tag/static/description/index.html
  mrp_tag/views/mrp_production_view.xml
  mrp_tag/views/mrp_tag_view.xml
Labels: approved, bot is merging ⏳

#1539 [18.0][MIG] mrp_mass_production_order: Migration to 18.0
  mrp_mass_production_order/README.rst
  mrp_mass_production_order/__init__.py
  mrp_mass_production_order/__manifest__.py
  mrp_mass_production_order/i18n/ca.po
  mrp_mass_production_order/i18n/es.po
  mrp_mass_production_order/i18n/it.po
  mrp_mass_production_order/i18n/mrp_mass_production_order.pot
  mrp_mass_production_order/pyproject.toml
  mrp_mass_production_order/readme/CONTRIBUTORS.md
  mrp_mass_production_order/readme/DESCRIPTION.md
  mrp_mass_production_order/readme/USAGE.md
  mrp_mass_production_order/security/ir.model.access.csv
  mrp_mass_production_order/static/description/icon.png
  mrp_mass_production_order/static/description/icon.svg
  mrp_mass_production_order/static/description/index.html
  mrp_mass_production_order/tests/__init__.py
  mrp_mass_production_order/tests/test_mrp_mass_production_order.py
  mrp_mass_production_order/wizards/__init__.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.xml
Labels: bot is merging ⏳

#960 [15.0] [ADD] mrp_workorder_ref
  mrp_workorder_ref/README.rst
  mrp_workorder_ref/__init__.py
  mrp_workorder_ref/__manifest__.py
  mrp_workorder_ref/models/__init__.py
  mrp_workorder_ref/models/mrp_production.py
  mrp_workorder_ref/models/mrp_routing_workcenter.py
  mrp_workorder_ref/models/mrp_workorder.py
  mrp_workorder_ref/readme/CONTRIBUTORS.rst
  mrp_workorder_ref/readme/DESCRIPTION.rst
  mrp_workorder_ref/tests/__init__.py
  mrp_workorder_ref/tests/test_workorder_ref.py
  mrp_workorder_ref/views/mrp_routing_workcenter.xml
  mrp_workorder_ref/views/mrp_workorder.xml
  setup/mrp_workorder_ref/odoo/addons/mrp_workorder_ref
  setup/mrp_workorder_ref/setup.py
Labels: approved, bot is merging ⏳, no stale

#1002 [14.0][FIX] mrp_unbuild_subcontracting: raise error when the subcontracting move is linked with more than one manufacturing order.
  mrp_unbuild_subcontracting/models/stock_move.py
  mrp_unbuild_subcontracting/models/stock_picking.py
  mrp_unbuild_subcontracting/tests/test_mrp_unbuild_subcontracting.py
Labels: approved, bot is merging ⏳, no stale

#1177 [16.0][ADD] mrp_mto_owner
  mrp_mto_owner/README.rst
  mrp_mto_owner/__init__.py
  mrp_mto_owner/__manifest__.py
  mrp_mto_owner/models/__init__.py
  mrp_mto_owner/models/stock_rule.py
  mrp_mto_owner/readme/DESCRIPTION.rst
  mrp_mto_owner/static/description/index.html
  mrp_mto_owner/tests/__init__.py
  mrp_mto_owner/tests/test_mrp_mto_owner.py
  setup/mrp_mto_owner/odoo/addons/mrp_mto_owner
  setup/mrp_mto_owner/setup.py
Labels: bot is merging ⏳

#1242 [16.0][ADD] mrp_product_produce_delay_in_hour
  mrp_product_produce_delay_in_hour/README.rst
  mrp_product_produce_delay_in_hour/__init__.py
  mrp_product_produce_delay_in_hour/__manifest__.py
  mrp_product_produce_delay_in_hour/data/decimal_precision.xml
  mrp_product_produce_delay_in_hour/i18n/fr.po
  mrp_product_produce_delay_in_hour/models/__init__.py
  mrp_product_produce_delay_in_hour/models/product_template.py
  mrp_product_produce_delay_in_hour/readme/CONTRIBUTORS.rst
  mrp_product_produce_delay_in_hour/readme/DESCRIPTION.rst
  mrp_product_produce_delay_in_hour/static/description/index.html
  mrp_product_produce_delay_in_hour/static/description/mrp_product_produce_delay_hour.png
  mrp_product_produce_delay_in_hour/tests/__init__.py
  mrp_product_produce_delay_in_hour/tests/test_product_produce_delay.py
  mrp_product_produce_delay_in_hour/views/product_template.xml
  setup/mrp_product_produce_delay_in_hour/odoo/addons/mrp_product_produce_delay_in_hour
  setup/mrp_product_produce_delay_in_hour/setup.py
Labels: bot is merging ⏳

#1278 [16.0][IMP] quality_control_oca, quality_control_stock_oca
  quality_control_mrp_oca/models/mrp_production.py
  quality_control_oca/models/qc_inspection.py
  quality_control_oca/models/qc_trigger_line.py
  quality_control_oca/models/qc_trigger_product_category_line.py
  quality_control_oca/models/qc_trigger_product_line.py
  quality_control_oca/models/qc_trigger_product_template_line.py
  quality_control_oca/tests/test_quality_control.py
  quality_control_oca/views/product_template_view.xml
  quality_control_oca/views/qc_inspection_view.xml
  quality_control_stock_oca/README.rst
  quality_control_stock_oca/models/__init__.py
  quality_control_stock_oca/models/qc_inspection.py
  quality_control_stock_oca/models/stock_move.py
  quality_control_stock_oca/models/stock_picking.py
  quality_control_stock_oca/readme/CONFIGURE.rst
  quality_control_stock_oca/readme/CONTRIBUTORS.rst
  quality_control_stock_oca/static/description/index.html
  quality_control_stock_oca/tests/test_quality_control_stock.py
Labels: approved, ready to merge, bot is merging ⏳

#1472 [16.0][FIX] mrp_restrict_lot: avoid duplicate mo name in case of cancellation qty changes ...
  mrp_restrict_lot/models/stock_rule.py
  mrp_restrict_lot/tests/test_manufaturing_lot.py
Labels: bot is merging ⏳

#1483 [17.0][MIG] mrp_lot_production_date: Migration to 17.0
  mrp_lot_production_date/README.rst
  mrp_lot_production_date/__init__.py
  mrp_lot_production_date/__manifest__.py
  mrp_lot_production_date/i18n/it.po
  mrp_lot_production_date/i18n/mrp_lot_production_date.pot
  mrp_lot_production_date/models/__init__.py
  mrp_lot_production_date/models/mrp_production.py
  mrp_lot_production_date/pyproject.toml
  mrp_lot_production_date/readme/CONTRIBUTORS.md
  mrp_lot_production_date/readme/CREDITS.md
  mrp_lot_production_date/readme/DESCRIPTION.md
  mrp_lot_production_date/readme/USAGE.md
  mrp_lot_production_date/static/description/icon.png
  mrp_lot_production_date/static/description/index.html
  mrp_lot_production_date/tests/__init__.py
  mrp_lot_production_date/tests/test_production_date.py
Labels: approved, merged 🎉

#1496 [16.0][ADD] mrp_production_allow_recursive
  mrp_production_allow_recursive/README.rst
  mrp_production_allow_recursive/__init__.py
  mrp_production_allow_recursive/__manifest__.py
  mrp_production_allow_recursive/models/__init__.py
  mrp_production_allow_recursive/models/mrp_production.py
  mrp_production_allow_recursive/models/res_company.py
  mrp_production_allow_recursive/models/res_config_settings.py
  mrp_production_allow_recursive/readme/CONFIGURE.md
  mrp_production_allow_recursive/readme/CONTEXT.md
  mrp_production_allow_recursive/readme/CONTRIBUTORS.md
  mrp_production_allow_recursive/readme/DESCRIPTION.md
  mrp_production_allow_recursive/static/description/index.html
  mrp_production_allow_recursive/tests/__init__.py
  mrp_production_allow_recursive/tests/test_mrp_production_allow_recursive.py
  mrp_production_allow_recursive/views/res_config_settings_views.xml
  setup/mrp_production_allow_recursive/odoo/addons/mrp_production_allow_recursive
  setup/mrp_production_allow_recursive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1503 [18.0][MIG] mrp_subcontracting_inhibit: Migration to 18.0
  mrp_subcontracting_inhibit/README.rst
  mrp_subcontracting_inhibit/__init__.py
  mrp_subcontracting_inhibit/__manifest__.py
  mrp_subcontracting_inhibit/i18n/es.po
  mrp_subcontracting_inhibit/i18n/it.po
  mrp_subcontracting_inhibit/i18n/mrp_subcontracting_inhibit.pot
  mrp_subcontracting_inhibit/models/__init__.py
  mrp_subcontracting_inhibit/models/product_product.py
  mrp_subcontracting_inhibit/models/product_supplierinfo.py
  mrp_subcontracting_inhibit/models/purchase_order.py
  mrp_subcontracting_inhibit/models/stock_location_route.py
  mrp_subcontracting_inhibit/models/stock_move.py
  mrp_subcontracting_inhibit/pyproject.toml
  mrp_subcontracting_inhibit/readme/CONFIGURE.md
  mrp_subcontracting_inhibit/readme/CONTRIBUTORS.md
  mrp_subcontracting_inhibit/readme/DESCRIPTION.md
  mrp_subcontracting_inhibit/readme/USAGE.md
  mrp_subcontracting_inhibit/static/description/icon.png
  mrp_subcontracting_inhibit/static/description/index.html
  mrp_subcontracting_inhibit/tests/__init__.py
  mrp_subcontracting_inhibit/tests/test_mrp_subcontracting_inhibit.py
  mrp_subcontracting_inhibit/views/product_supplierinfo_view.xml
  mrp_subcontracting_inhibit/views/purchase_order_view.xml
  mrp_subcontracting_inhibit/views/stock_location_route_view.xml
Labels: approved, bot is merging ⏳

#1508 [16.0][IMP] quality_control_oca: Add kanban views for qc.inspection and qc.inspection.line
  quality_control_oca/views/qc_inspection_view.xml
Labels: approved, bot is merging ⏳

#1421 [18.0][MIG] mrp_repair_order: Migration to 18.0
  mrp_repair_order/README.rst
  mrp_repair_order/__init__.py
  mrp_repair_order/__manifest__.py
  mrp_repair_order/i18n/ca_ES.po
  mrp_repair_order/i18n/es.po
  mrp_repair_order/i18n/it.po
  mrp_repair_order/i18n/mrp_repair_order.pot
  mrp_repair_order/models/__init__.py
  mrp_repair_order/models/mrp.py
  mrp_repair_order/models/repair.py
  mrp_repair_order/pyproject.toml
  mrp_repair_order/readme/CONTRIBUTORS.md
  mrp_repair_order/readme/DESCRIPTION.md
  mrp_repair_order/readme/USAGE.md
  mrp_repair_order/static/description/icon.png
  mrp_repair_order/static/description/icon.svg
  mrp_repair_order/static/description/index.html
  mrp_repair_order/tests/__init__.py
  mrp_repair_order/tests/test_mrp_repair_order.py
  mrp_repair_order/views/mrp_production_views.xml
  mrp_repair_order/views/repair_views.xml
Labels: needs review, approved, bot is merging ⏳

#1526 [18.0][MIG] mrp_unbuild_move_link: Migration to 18.0
  mrp_unbuild_move_link/README.rst
  mrp_unbuild_move_link/__init__.py
  mrp_unbuild_move_link/__manifest__.py
  mrp_unbuild_move_link/i18n/es.po
  mrp_unbuild_move_link/i18n/it.po
  mrp_unbuild_move_link/i18n/mrp_unbuild_move_link.pot
  mrp_unbuild_move_link/models/__init__.py
  mrp_unbuild_move_link/models/mrp_unbuild.py
  mrp_unbuild_move_link/models/stock_move.py
  mrp_unbuild_move_link/pyproject.toml
  mrp_unbuild_move_link/readme/CONTRIBUTORS.md
  mrp_unbuild_move_link/readme/DESCRIPTION.md
  mrp_unbuild_move_link/static/description/icon.png
  mrp_unbuild_move_link/static/description/index.html
  mrp_unbuild_move_link/tests/__init__.py
  mrp_unbuild_move_link/tests/test_mrp_unbuild_move_link.py
  mrp_unbuild_move_link/views/stock_move_views.xml
Labels: bot is merging ⏳

#1528 [16.0][ADD] mrp_workorder_last_worker
  mrp_workorder_last_worker/README.rst
  mrp_workorder_last_worker/__init__.py
  mrp_workorder_last_worker/__manifest__.py
  mrp_workorder_last_worker/models/__init__.py
  mrp_workorder_last_worker/models/mrp_workorder.py
  mrp_workorder_last_worker/readme/CONTRIBUTORS.rst
  mrp_workorder_last_worker/readme/DESCRIPTION.rst
  mrp_workorder_last_worker/static/description/index.html
  mrp_workorder_last_worker/tests/__init__.py
  mrp_workorder_last_worker/tests/test_mrp_workorder_last_worker.py
  mrp_workorder_last_worker/views/mrp_workorder_views.xml
  setup/mrp_workorder_last_worker/odoo/addons/mrp_workorder_last_worker
  setup/mrp_workorder_last_worker/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1534 [16.0][FIX] mrp_bom_tracking: catch UoM qty mrp_bom_tracking rounding errors
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
Labels: bot is merging ⏳

#1543 [18.0][FIX]: catch UoM qty mrp_bom_tracking rounding errors
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
Labels: approved, bot is merging ⏳

#1542 [17.0][FIX]: catch UoM qty mrp_bom_tracking rounding errors
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
Labels: approved, bot is merging ⏳

#1413 [17.0][FIX] mrp_multi_level: properly handle UserError in procurement.
  mrp_multi_level/wizards/mrp_inventory_procure.py
Labels: needs fixing, approved, bot is merging ⏳

#1509 [16.0][IMP] quality_control_oca: update methods signatures
  quality_control_oca/models/qc_inspection.py
  quality_control_oca/tests/test_quality_control.py
Labels: bot is merging ⏳
