Repository OCA/manufacture, pull requests merged in 2025-01, with the labels that each got.

#1437 [16.0][FIX] mrp_lot_number_propagation Keyerror stock.production.lot
  mrp_lot_number_propagation/models/mrp_production.py
  mrp_lot_number_propagation/tests/__init__.py
  mrp_lot_number_propagation/tests/common.py
  mrp_lot_number_propagation/tests/test_mrp_production.py
Labels: approved, bot is merging ⏳

#1227 [16.0][ADD] mrp_bom_product_price_margin
  mrp_bom_product_price_margin/README.rst
  mrp_bom_product_price_margin/__init__.py
  mrp_bom_product_price_margin/__manifest__.py
  mrp_bom_product_price_margin/i18n/fr.po
  mrp_bom_product_price_margin/models/__init__.py
  mrp_bom_product_price_margin/models/mrp_bom.py
  mrp_bom_product_price_margin/models/mrp_bom_line.py
  mrp_bom_product_price_margin/models/product_template.py
  mrp_bom_product_price_margin/readme/CONTRIBUTORS.rst
  mrp_bom_product_price_margin/readme/DESCRIPTION.rst
  mrp_bom_product_price_margin/readme/USAGE.rst
  mrp_bom_product_price_margin/static/description/index.html
  mrp_bom_product_price_margin/static/mrp_bom_product_price_margin_diff.jpeg
  mrp_bom_product_price_margin/static/mrp_bom_product_price_margin_no_diff.jpeg
  mrp_bom_product_price_margin/static/mrp_bom_product_price_margin_tree.png
  mrp_bom_product_price_margin/tests/__init__.py
  mrp_bom_product_price_margin/tests/test_mrp_bom_sale_margin.py
  mrp_bom_product_price_margin/views/view_mrp_bom.xml
  setup/mrp_bom_product_price_margin/odoo/addons/mrp_bom_product_price_margin
  setup/mrp_bom_product_price_margin/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1416 [18.0][MIG] mrp_production_note: Migration to 18.0
  mrp_production_note/README.rst
  mrp_production_note/__init__.py
  mrp_production_note/__manifest__.py
  mrp_production_note/i18n/de.po
  mrp_production_note/i18n/es.po
  mrp_production_note/i18n/es_MX.po
  mrp_production_note/i18n/fi.po
  mrp_production_note/i18n/fr.po
  mrp_production_note/i18n/gl.po
  mrp_production_note/i18n/hr.po
  mrp_production_note/i18n/hr_HR.po
  mrp_production_note/i18n/it.po
  mrp_production_note/i18n/lt.po
  mrp_production_note/i18n/mrp_production_note.pot
  mrp_production_note/i18n/nl_NL.po
  mrp_production_note/i18n/pt_BR.po
  mrp_production_note/i18n/ro.po
  mrp_production_note/i18n/sl.po
  mrp_production_note/i18n/tr.po
  mrp_production_note/i18n/tr_TR.po
  mrp_production_note/i18n/vi_VN.po
  mrp_production_note/i18n/zh_CN.po
  mrp_production_note/models/__init__.py
  mrp_production_note/models/mrp_production.py
  mrp_production_note/pyproject.toml
  mrp_production_note/readme/CONTRIBUTORS.md
  mrp_production_note/readme/DESCRIPTION.md
  mrp_production_note/readme/USAGE.md
  mrp_production_note/static/description/icon.png
  mrp_production_note/static/description/index.html
  mrp_production_note/views/mrp_production_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1301 [16.0][IMP] clarification for usage and description
  mrp_sale_info/README.rst
  mrp_sale_info/readme/DESCRIPTION.rst
  mrp_sale_info/readme/USAGE.rst
  mrp_sale_info/static/description/index.html
  mrp_sale_info/static/product_form_routes.png
  mrp_sale_info/static/sale_order_production_order_link.jpeg
Labels: approved, bot is merging ⏳

#1438 [16.0][FIX] mpr_bom_version typo in mrp_bom_view.xml
  mrp_bom_version/views/mrp_bom_view.xml
Labels: bot is merging ⏳

#1444 [17.0][FIX] mrp_mass_production_order: Fix tests
  mrp_mass_production_order/tests/test_mrp_mass_production_order.py
Labels: bot is merging ⏳

#1441 [17.0] [MIG] mrp_subcontracting_purchase_link
  mrp_subcontracting_purchase_link/README.rst
  mrp_subcontracting_purchase_link/__init__.py
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/hooks.py
  mrp_subcontracting_purchase_link/i18n/es.po
  mrp_subcontracting_purchase_link/i18n/fr.po
  mrp_subcontracting_purchase_link/i18n/it.po
  mrp_subcontracting_purchase_link/i18n/ja.po
  mrp_subcontracting_purchase_link/i18n/mrp_subcontracting_purchase_link.pot
  mrp_subcontracting_purchase_link/migrations/14.0.2.0.0/post-migration.py
  mrp_subcontracting_purchase_link/models/__init__.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/pyproject.toml
  mrp_subcontracting_purchase_link/readme/CONTRIBUTORS.md
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.md
  mrp_subcontracting_purchase_link/static/description/icon.png
  mrp_subcontracting_purchase_link/static/description/index.html
  mrp_subcontracting_purchase_link/tests/__init__.py
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
  mrp_subcontracting_purchase_link/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1255 [16.0][ADD] mrp_product_characterisation
  mrp_product_characterisation/README.rst
  mrp_product_characterisation/__init__.py
  mrp_product_characterisation/__manifest__.py
  mrp_product_characterisation/i18n/fr.po
  mrp_product_characterisation/models/__init__.py
  mrp_product_characterisation/models/product_product.py
  mrp_product_characterisation/models/product_template.py
  mrp_product_characterisation/readme/CONTRIBUTORS.rst
  mrp_product_characterisation/readme/DESCRIPTION.rst
  mrp_product_characterisation/static/description/index.html
  mrp_product_characterisation/static/description/intermediate_product.png
  mrp_product_characterisation/tests/__init__.py
  mrp_product_characterisation/tests/test_product.py
  mrp_product_characterisation/views/view_mrp_bom.xml
  mrp_product_characterisation/views/view_product_product.xml
  mrp_product_characterisation/views/view_product_template.xml
  setup/mrp_product_characterisation/odoo/addons/mrp_product_characterisation
  setup/mrp_product_characterisation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1424 [17.0][FIX] mrp_multi_level: avoid create warehouse and location in mrp area view
  mrp_multi_level/views/mrp_area_views.xml
Labels: approved, bot is merging ⏳, Pending to fw/back port

#1447 [18.0][FW][FIX] mrp_multi_level: avoid create warehouse in mrp area view
  mrp_multi_level/views/mrp_area_views.xml
Labels: bot is merging ⏳

#1448 [17.0][FIX] mrp_multi_level: fix main supplier computation
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳, Pending to fw/back port

#1449 [16.0][BACKPORT][FIX] mrp_multi_level: avoid create warehouse in mrp area view
  mrp_multi_level/views/mrp_area_views.xml
Labels: bot is merging ⏳

#1450 [15.0][BACKPORT][FIX] mrp_multi_level: avoid create warehouse in mrp area view
  mrp_multi_level/views/mrp_area_views.xml
Labels: bot is merging ⏳

#1452 [16.0][FIX] mrp_multi_level: fix main supplier computation
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1453 [15.0][FIX] mrp_multi_level: fix main supplier computation
  mrp_multi_level/models/product_mrp_area.py
Labels: bot is merging ⏳

#1214 [16.0][ADD] mrp_bom_line_net_qty
  mrp_bom_line_net_qty/README.rst
  mrp_bom_line_net_qty/__init__.py
  mrp_bom_line_net_qty/__manifest__.py
  mrp_bom_line_net_qty/i18n/fr.po
  mrp_bom_line_net_qty/models/__init__.py
  mrp_bom_line_net_qty/models/mrp_bom_line.py
  mrp_bom_line_net_qty/readme/CONTRIBUTORS.rst
  mrp_bom_line_net_qty/readme/DESCRIPTION.rst
  mrp_bom_line_net_qty/static/description/change_net_qty_after.png
  mrp_bom_line_net_qty/static/description/change_net_qty_before.png
  mrp_bom_line_net_qty/static/description/index.html
  mrp_bom_line_net_qty/static/description/mrp_bom_line_net_qty.gif
  mrp_bom_line_net_qty/tests/__init__.py
  mrp_bom_line_net_qty/tests/test_mrp_bom_line_net_qty.py
  mrp_bom_line_net_qty/views/view_mrp_bom.xml
  setup/mrp_bom_line_net_qty/odoo/addons/mrp_bom_line_net_qty
  setup/mrp_bom_line_net_qty/setup.py
Labels: approved, bot is merging ⏳

#1013 [16.0][ADD] mrp_stock_owner_restriction
  mrp_stock_owner_restriction/README.rst
  mrp_stock_owner_restriction/__init__.py
  mrp_stock_owner_restriction/__manifest__.py
  mrp_stock_owner_restriction/i18n/ja.po
  mrp_stock_owner_restriction/models/__init__.py
  mrp_stock_owner_restriction/models/mrp_production.py
  mrp_stock_owner_restriction/models/mrp_unbuild.py
  mrp_stock_owner_restriction/models/stock_move.py
  mrp_stock_owner_restriction/models/stock_move_line.py
  mrp_stock_owner_restriction/readme/CONTRIBUTORS.rst
  mrp_stock_owner_restriction/readme/DESCRIPTION.rst
  mrp_stock_owner_restriction/readme/ROADMAP.rst
  mrp_stock_owner_restriction/static/description/index.html
  mrp_stock_owner_restriction/tests/__init__.py
  mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
  mrp_stock_owner_restriction/views/mrp_production_views.xml
  setup/mrp_stock_owner_restriction/odoo/addons/mrp_stock_owner_restriction
  setup/mrp_stock_owner_restriction/setup.py
Labels: approved, bot is merging ⏳
