Repository OCA/manufacture, pull requests merged in 2025-04, with the labels that each got.

#1461 [18.0][MIG] account_move_line_mrp_info
  account_move_line_mrp_info/README.rst
  account_move_line_mrp_info/__init__.py
  account_move_line_mrp_info/__manifest__.py
  account_move_line_mrp_info/hooks.py
  account_move_line_mrp_info/i18n/account_move_line_mrp_info.pot
  account_move_line_mrp_info/i18n/it.po
  account_move_line_mrp_info/models/__init__.py
  account_move_line_mrp_info/models/account_move_line.py
  account_move_line_mrp_info/models/mrp_production.py
  account_move_line_mrp_info/pyproject.toml
  account_move_line_mrp_info/readme/CONTRIBUTORS.md
  account_move_line_mrp_info/readme/DESCRIPTION.md
  account_move_line_mrp_info/readme/USAGE.md
  account_move_line_mrp_info/security/ir.model.access.csv
  account_move_line_mrp_info/static/description/icon.png
  account_move_line_mrp_info/static/description/index.html
  account_move_line_mrp_info/tests/__init__.py
  account_move_line_mrp_info/tests/test_mrp_journal_items.py
  account_move_line_mrp_info/views/account_move_line_view.xml
  account_move_line_mrp_info/views/mrp_production_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1434 [18.0][MIG] mrp_bom_note: Migration to 18.0
  mrp_bom_note/README.rst
  mrp_bom_note/__init__.py
  mrp_bom_note/__manifest__.py
  mrp_bom_note/i18n/de.po
  mrp_bom_note/i18n/es.po
  mrp_bom_note/i18n/fi.po
  mrp_bom_note/i18n/fr.po
  mrp_bom_note/i18n/gl.po
  mrp_bom_note/i18n/hr.po
  mrp_bom_note/i18n/hr_HR.po
  mrp_bom_note/i18n/it.po
  mrp_bom_note/i18n/lt.po
  mrp_bom_note/i18n/mrp_bom_note.pot
  mrp_bom_note/i18n/nl_NL.po
  mrp_bom_note/i18n/pt_BR.po
  mrp_bom_note/i18n/ro.po
  mrp_bom_note/i18n/sl.po
  mrp_bom_note/i18n/tr.po
  mrp_bom_note/i18n/tr_TR.po
  mrp_bom_note/i18n/zh_CN.po
  mrp_bom_note/models/__init__.py
  mrp_bom_note/models/mrp_bom.py
  mrp_bom_note/pyproject.toml
  mrp_bom_note/readme/CONTRIBUTORS.md
  mrp_bom_note/readme/DESCRIPTION.md
  mrp_bom_note/readme/USAGE.md
  mrp_bom_note/static/description/icon.png
  mrp_bom_note/static/description/index.html
  mrp_bom_note/views/mrp_bom_view.xml
  mrp_bom_note/views/mrp_production_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1426 [17.0][MIG] mrp_subcontracting_bom_dual_use: Migration to 17.0
  mrp_mass_production_order/tests/test_mrp_mass_production_order.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.py
  mrp_subcontracting_bom_dual_use/README.rst
  mrp_subcontracting_bom_dual_use/__init__.py
  mrp_subcontracting_bom_dual_use/__manifest__.py
  mrp_subcontracting_bom_dual_use/i18n/es.po
  mrp_subcontracting_bom_dual_use/i18n/it.po
  mrp_subcontracting_bom_dual_use/i18n/mrp_subcontracting_bom_dual_use.pot
  mrp_subcontracting_bom_dual_use/models/__init__.py
  mrp_subcontracting_bom_dual_use/models/mrp_bom.py
  mrp_subcontracting_bom_dual_use/models/mrp_production.py
  mrp_subcontracting_bom_dual_use/pyproject.toml
  mrp_subcontracting_bom_dual_use/readme/CONTRIBUTORS.md
  mrp_subcontracting_bom_dual_use/readme/DESCRIPTION.md
  mrp_subcontracting_bom_dual_use/readme/USAGE.md
  mrp_subcontracting_bom_dual_use/static/description/icon.png
  mrp_subcontracting_bom_dual_use/static/description/index.html
  mrp_subcontracting_bom_dual_use/tests/__init__.py
  mrp_subcontracting_bom_dual_use/tests/test_mrp_subcontracting_bom_dual_use.py
  mrp_subcontracting_bom_dual_use/views/mrp_bom_view.xml
Labels: bot is merging ⏳

#1428 [18.0][MIG] mrp_sale_info: Migration to 18.0
  mrp_sale_info/README.rst
  mrp_sale_info/__init__.py
  mrp_sale_info/__manifest__.py
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/it.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/mrp_production.py
  mrp_sale_info/models/mrp_workorder.py
  mrp_sale_info/models/stock_rule.py
  mrp_sale_info/pyproject.toml
  mrp_sale_info/readme/CONTRIBUTORS.md
  mrp_sale_info/readme/DESCRIPTION.md
  mrp_sale_info/readme/USAGE.md
  mrp_sale_info/static/description/icon.png
  mrp_sale_info/static/description/index.html
  mrp_sale_info/tests/__init__.py
  mrp_sale_info/tests/test_mrp_sale_info.py
  mrp_sale_info/views/mrp_production.xml
  mrp_sale_info/views/mrp_workorder.xml
Labels: approved, ready to merge, bot is merging ⏳

#1514 [16.0][ADD] mrp_workorder_priority
  mrp_workorder_priority/README.rst
  mrp_workorder_priority/__init__.py
  mrp_workorder_priority/__manifest__.py
  mrp_workorder_priority/models/__init__.py
  mrp_workorder_priority/models/mrp_workorder.py
  mrp_workorder_priority/readme/CONTRIBUTORS.md
  mrp_workorder_priority/readme/DESCRIPTION.md
  mrp_workorder_priority/static/description/index.html
  mrp_workorder_priority/views/mrp_workorder_views.xml
  setup/mrp_workorder_priority/odoo/addons/mrp_workorder_priority
  setup/mrp_workorder_priority/setup.py
Labels: approved, bot is merging ⏳

#1470 [18.0][MIG] mrp_bom_location: Migration to 18.0
  mrp_bom_location/README.rst
  mrp_bom_location/__init__.py
  mrp_bom_location/__manifest__.py
  mrp_bom_location/i18n/de.po
  mrp_bom_location/i18n/es.po
  mrp_bom_location/i18n/hr.po
  mrp_bom_location/i18n/it.po
  mrp_bom_location/i18n/mrp_bom_location.pot
  mrp_bom_location/models/__init__.py
  mrp_bom_location/models/mrp_bom.py
  mrp_bom_location/pyproject.toml
  mrp_bom_location/readme/CONTRIBUTORS.md
  mrp_bom_location/readme/CREDITS.md
  mrp_bom_location/readme/DESCRIPTION.md
  mrp_bom_location/readme/USAGE.md
  mrp_bom_location/report/__init__.py
  mrp_bom_location/report/bom_structure.py
  mrp_bom_location/static/description/icon.png
  mrp_bom_location/static/description/index.html
  mrp_bom_location/static/src/xml/mrp_bom_overview_location.xml
  mrp_bom_location/tests/__init__.py
  mrp_bom_location/tests/test_mrp_bom.py
  mrp_bom_location/views/mrp_view.xml
  mrp_bom_location/views/report_mrpbomstructure.xml
Labels: approved, bot is merging ⏳

#1516 [18.0][MIG] mrp_subcontracting_purchase_link
  mrp_subcontracting_purchase_link/README.rst
  mrp_subcontracting_purchase_link/__init__.py
  mrp_subcontracting_purchase_link/__manifest__.py
  mrp_subcontracting_purchase_link/hooks.py
  mrp_subcontracting_purchase_link/i18n/es.po
  mrp_subcontracting_purchase_link/i18n/fr.po
  mrp_subcontracting_purchase_link/i18n/it.po
  mrp_subcontracting_purchase_link/i18n/ja.po
  mrp_subcontracting_purchase_link/i18n/mrp_subcontracting_purchase_link.pot
  mrp_subcontracting_purchase_link/models/__init__.py
  mrp_subcontracting_purchase_link/models/mrp_production.py
  mrp_subcontracting_purchase_link/models/purchase_order.py
  mrp_subcontracting_purchase_link/models/stock_picking.py
  mrp_subcontracting_purchase_link/pyproject.toml
  mrp_subcontracting_purchase_link/readme/CONTRIBUTORS.md
  mrp_subcontracting_purchase_link/readme/DESCRIPTION.md
  mrp_subcontracting_purchase_link/static/description/icon.png
  mrp_subcontracting_purchase_link/static/description/index.html
  mrp_subcontracting_purchase_link/tests/__init__.py
  mrp_subcontracting_purchase_link/tests/test_mrp_subcontracting_purchase_link.py
  mrp_subcontracting_purchase_link/views/mrp_production_views.xml
  mrp_subcontracting_purchase_link/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1418 [18.0][MIG] mrp_bom_tracking: Migration to 18.0
  mrp_bom_tracking/README.rst
  mrp_bom_tracking/__init__.py
  mrp_bom_tracking/__manifest__.py
  mrp_bom_tracking/i18n/de.po
  mrp_bom_tracking/i18n/es.po
  mrp_bom_tracking/i18n/it.po
  mrp_bom_tracking/i18n/mrp_bom_tracking.pot
  mrp_bom_tracking/models/__init__.py
  mrp_bom_tracking/models/mrp_bom.py
  mrp_bom_tracking/pyproject.toml
  mrp_bom_tracking/readme/CONTRIBUTORS.md
  mrp_bom_tracking/readme/DESCRIPTION.md
  mrp_bom_tracking/static/description/icon.png
  mrp_bom_tracking/static/description/index.html
  mrp_bom_tracking/tests/__init__.py
  mrp_bom_tracking/tests/test_mrp_bom_tracking.py
  mrp_bom_tracking/views/bom_template.xml
Labels: approved, bot is merging ⏳

#1493 [17.0][IMP]quality_control_stock_oca: inspection per lot/serial
  quality_control_stock_oca/README.rst
  quality_control_stock_oca/models/qc_inspection.py
  quality_control_stock_oca/models/qc_trigger.py
  quality_control_stock_oca/models/stock_picking.py
  quality_control_stock_oca/readme/CONFIGURE.md
  quality_control_stock_oca/readme/CONTRIBUTORS.md
  quality_control_stock_oca/static/description/index.html
  quality_control_stock_oca/tests/test_quality_control_stock.py
  quality_control_stock_oca/views/qc_trigger_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1521 [17.0][MIG] purchase_mrp_distribution: Migration to 17.0
  purchase_mrp_distribution/README.rst
  purchase_mrp_distribution/__init__.py
  purchase_mrp_distribution/__manifest__.py
  purchase_mrp_distribution/i18n/es.po
  purchase_mrp_distribution/i18n/purchase_mrp_distribution.pot
  purchase_mrp_distribution/models/__init__.py
  purchase_mrp_distribution/models/mrp_bom.py
  purchase_mrp_distribution/models/purchase.py
  purchase_mrp_distribution/models/stock_move.py
  purchase_mrp_distribution/pyproject.toml
  purchase_mrp_distribution/readme/CONFIGURE.md
  purchase_mrp_distribution/readme/CONTEXT.md
  purchase_mrp_distribution/readme/CONTRIBUTORS.md
  purchase_mrp_distribution/readme/DESCRIPTION.md
  purchase_mrp_distribution/readme/ROADMAP.md
  purchase_mrp_distribution/readme/USAGE.md
  purchase_mrp_distribution/security/ir.model.access.csv
  purchase_mrp_distribution/static/description/icon.png
  purchase_mrp_distribution/static/description/index.html
  purchase_mrp_distribution/tests/__init__.py
  purchase_mrp_distribution/tests/test_purchase_mrp_distribution.py
  purchase_mrp_distribution/views/mrp_bom_views.xml
  purchase_mrp_distribution/views/stock_picking_views.xml
  purchase_mrp_distribution/wizards/__init__.py
  purchase_mrp_distribution/wizards/stock_move_distribution_wiz.py
  purchase_mrp_distribution/wizards/stock_move_distribution_wiz_views.xml
Labels: approved, bot is merging ⏳

#1425 [17.0][MIG] mrp_attachment_mgmt: Migration to 17.0
  mrp_attachment_mgmt/README.rst
  mrp_attachment_mgmt/__init__.py
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/i18n/es.po
  mrp_attachment_mgmt/i18n/hr.po
  mrp_attachment_mgmt/i18n/it.po
  mrp_attachment_mgmt/i18n/mrp_attachment_mgmt.pot
  mrp_attachment_mgmt/models/__init__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/models/mrp_production.py
  mrp_attachment_mgmt/models/mrp_workorder.py
  mrp_attachment_mgmt/models/product.py
  mrp_attachment_mgmt/pyproject.toml
  mrp_attachment_mgmt/readme/CONFIGURE.md
  mrp_attachment_mgmt/readme/CONTRIBUTORS.md
  mrp_attachment_mgmt/readme/DESCRIPTION.md
  mrp_attachment_mgmt/readme/USAGE.md
  mrp_attachment_mgmt/static/description/icon.png
  mrp_attachment_mgmt/static/description/index.html
  mrp_attachment_mgmt/tests/__init__.py
  mrp_attachment_mgmt/tests/common.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
  mrp_attachment_mgmt/views/mrp_bom_view.xml
  mrp_attachment_mgmt/views/mrp_production_views.xml
  mrp_attachment_mgmt/views/product_views.xml
  mrp_attachment_mgmt/views/workorder_attachments_views.xml
Labels: bot is merging ⏳, stale

#1446 [17.0] [MIG] mrp_production_quant_manual_assign
  mrp_production_quant_manual_assign/README.rst
  mrp_production_quant_manual_assign/__init__.py
  mrp_production_quant_manual_assign/__manifest__.py
  mrp_production_quant_manual_assign/i18n/es.po
  mrp_production_quant_manual_assign/i18n/fr.po
  mrp_production_quant_manual_assign/i18n/hr.po
  mrp_production_quant_manual_assign/i18n/it.po
  mrp_production_quant_manual_assign/i18n/ja.po
  mrp_production_quant_manual_assign/i18n/mrp_production_quant_manual_assign.pot
  mrp_production_quant_manual_assign/i18n/pt_BR.po
  mrp_production_quant_manual_assign/models/__init__.py
  mrp_production_quant_manual_assign/models/mrp_bom.py
  mrp_production_quant_manual_assign/models/stock_move.py
  mrp_production_quant_manual_assign/pyproject.toml
  mrp_production_quant_manual_assign/readme/CONTRIBUTORS.md
  mrp_production_quant_manual_assign/readme/DESCRIPTION.md
  mrp_production_quant_manual_assign/readme/USAGE.md
  mrp_production_quant_manual_assign/static/description/icon.png
  mrp_production_quant_manual_assign/static/description/index.html
  mrp_production_quant_manual_assign/tests/__init__.py
  mrp_production_quant_manual_assign/tests/test_mrp_production_quant_manual_assign.py
  mrp_production_quant_manual_assign/views/mrp_production_views.xml
  mrp_production_quant_manual_assign/wizards/__init__.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants.py
  mrp_production_quant_manual_assign/wizards/assign_manual_quants_view.xml
Labels: approved, bot is merging ⏳

#1482 [18.0][MIG] mrp_production_back_to_draft: Migration to 18.0
  mrp_production_back_to_draft/README.rst
  mrp_production_back_to_draft/__init__.py
  mrp_production_back_to_draft/__manifest__.py
  mrp_production_back_to_draft/i18n/it.po
  mrp_production_back_to_draft/i18n/mrp_production_back_to_draft.pot
  mrp_production_back_to_draft/models/__init__.py
  mrp_production_back_to_draft/models/mrp_production.py
  mrp_production_back_to_draft/pyproject.toml
  mrp_production_back_to_draft/readme/CONTRIBUTORS.md
  mrp_production_back_to_draft/readme/DESCRIPTION.md
  mrp_production_back_to_draft/static/description/icon.png
  mrp_production_back_to_draft/static/description/index.html
  mrp_production_back_to_draft/tests/__init__.py
  mrp_production_back_to_draft/tests/test_mrp_return_to_draft.py
  mrp_production_back_to_draft/views/mrp_production_views.xml
Labels: approved, bot is merging ⏳

#1520 [17.0][MIG] stock_replenishment_mrp_bom_selection: Migration to 17.0
  stock_replenishment_mrp_bom_selection/README.rst
  stock_replenishment_mrp_bom_selection/__init__.py
  stock_replenishment_mrp_bom_selection/__manifest__.py
  stock_replenishment_mrp_bom_selection/i18n/es.po
  stock_replenishment_mrp_bom_selection/i18n/stock_replenishment_mrp_bom_selection.pot
  stock_replenishment_mrp_bom_selection/models/__init__.py
  stock_replenishment_mrp_bom_selection/models/stock_warehouse_orderpoint.py
  stock_replenishment_mrp_bom_selection/pyproject.toml
  stock_replenishment_mrp_bom_selection/readme/CONTEXT.md
  stock_replenishment_mrp_bom_selection/readme/CONTRIBUTORS.md
  stock_replenishment_mrp_bom_selection/readme/DESCRIPTION.md
  stock_replenishment_mrp_bom_selection/readme/USAGE.md
  stock_replenishment_mrp_bom_selection/security/ir.model.access.csv
  stock_replenishment_mrp_bom_selection/static/description/icon.png
  stock_replenishment_mrp_bom_selection/static/description/index.html
  stock_replenishment_mrp_bom_selection/tests/__init__.py
  stock_replenishment_mrp_bom_selection/tests/test_stock_replenishment_mrp_bom_selection.py
  stock_replenishment_mrp_bom_selection/wizard/__init__.py
  stock_replenishment_mrp_bom_selection/wizard/material_availability_wizard.py
  stock_replenishment_mrp_bom_selection/wizard/material_availability_wizard_views.xml
  stock_replenishment_mrp_bom_selection/wizard/stock_warehouse_orderpoint_replenish_wizard.py
  stock_replenishment_mrp_bom_selection/wizard/stock_warehouse_orderpoint_replenish_wizard_views.xml
Labels: approved, bot is merging ⏳
