Repository OCA/manufacture, pull requests merged in 2025-03, with the labels that each got.

#1491 [16.0][FIX] quality_control_oca: notes width in QC inspection form
  quality_control_oca/views/qc_inspection_view.xml
Labels: approved, bot is merging ⏳

#1492 [17.0][FIX] quality_control_oca: notes width in QC inspection form
  quality_control_oca/views/qc_inspection_view.xml
Labels: bot is merging ⏳

#1487 [14.0][FIX]mrp_bom_attribute_match_semifinished_product : Fixed UoM in header
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#1260 [16] ADD mrp_workcenter_workorder_link
  mrp_workcenter_workorder_link/README.rst
  mrp_workcenter_workorder_link/__init__.py
  mrp_workcenter_workorder_link/__manifest__.py
  mrp_workcenter_workorder_link/i18n/mrp_workcenter_workorder_link.pot
  mrp_workcenter_workorder_link/models/__init__.py
  mrp_workcenter_workorder_link/models/mrp_workcenter.py
  mrp_workcenter_workorder_link/models/mrp_workorder.py
  mrp_workcenter_workorder_link/readme/CONTRIBUTORS.rst
  mrp_workcenter_workorder_link/readme/DESCRIPTION.rst
  mrp_workcenter_workorder_link/static/description/index.html
  mrp_workcenter_workorder_link/tests/__init__.py
  mrp_workcenter_workorder_link/tests/test_action.py
  mrp_workcenter_workorder_link/views/mrp_workcenter_views.xml
  mrp_workcenter_workorder_link/views/mrp_workorder_views.xml
  setup/mrp_workcenter_workorder_link/odoo/addons/mrp_workcenter_workorder_link
  setup/mrp_workcenter_workorder_link/setup.py
Labels: approved, bot is merging ⏳, stale

#1498 [14.0][IMP] mrp_bom_attribute_match_semifinished_product: prefer archive semi finished products. Do not copy semi finished product templates when duplicating product template
  mrp_bom_attribute_match_semifinished_product/models/product_template.py
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.py
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.xml
Labels: bot is merging ⏳

#1443 [17.0][MIG] mrp_production_serial_matrix
  mrp_production_serial_matrix/README.rst
  mrp_production_serial_matrix/__init__.py
  mrp_production_serial_matrix/__manifest__.py
  mrp_production_serial_matrix/i18n/es.po
  mrp_production_serial_matrix/i18n/it.po
  mrp_production_serial_matrix/i18n/mrp_production_serial_matrix.pot
  mrp_production_serial_matrix/models/__init__.py
  mrp_production_serial_matrix/models/mrp_production.py
  mrp_production_serial_matrix/pyproject.toml
  mrp_production_serial_matrix/readme/CONTRIBUTORS.md
  mrp_production_serial_matrix/readme/DESCRIPTION.md
  mrp_production_serial_matrix/readme/ROADMAP.md
  mrp_production_serial_matrix/readme/USAGE.md
  mrp_production_serial_matrix/security/ir.model.access.csv
  mrp_production_serial_matrix/static/description/icon.png
  mrp_production_serial_matrix/static/description/index.html
  mrp_production_serial_matrix/tests/__init__.py
  mrp_production_serial_matrix/tests/test_mrp_production_serial_matrix.py
  mrp_production_serial_matrix/views/mrp_production_views.xml
  mrp_production_serial_matrix/wizards/__init__.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_line.py
  mrp_production_serial_matrix/wizards/mrp_production_serial_matrix_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1499 [17.0][IMP] mrp_mass_production_order: Mass production with one product consumed
  mrp_mass_production_order/README.rst
  mrp_mass_production_order/__manifest__.py
  mrp_mass_production_order/i18n/ca.po
  mrp_mass_production_order/i18n/es.po
  mrp_mass_production_order/readme/USAGE.md
  mrp_mass_production_order/static/description/index.html
  mrp_mass_production_order/tests/test_mrp_mass_production_order.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.py
  mrp_mass_production_order/wizards/mrp_mass_order_wizard.xml
Labels: bot is merging ⏳

#1484 16.0 fix mrp bom tag access rights
  mrp_bom_tag/README.rst
  mrp_bom_tag/__manifest__.py
  mrp_bom_tag/security/ir.model.access.csv
  mrp_bom_tag/static/description/index.html
Labels: bot is merging ⏳

#1385 [16.0][IMP] mrp_bom_tag Quick create tags on BoM form
  mrp_bom_tag/views/view_mrp_bom.xml
Labels: bot is merging ⏳, stale

#1489 [16.0][FIX] mrp_bom_product_price_margin onchange stuck with readonly
  mrp_bom_product_price_margin/views/view_mrp_bom.xml
Labels: bot is merging ⏳
