Repository OCA/manufacture, pull requests merged in 2025-02, with the labels that each got.

#1460 [17.0][FW][IMP] account_move_line_mrp_info: add MO link in tree view and standard filtering
  account_move_line_mrp_info/views/account_move_line_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1462 Revert [FIX] mrp_multi_level: adapt tests to recent upstream changes.
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#1468 [18.0][FW] Revert [FIX] mrp_multi_level: adapt tests to recent upstream changes.
  mrp_multi_level/tests/test_mrp_multi_level.py
Labels: bot is merging ⏳

#1466 [18.0][MIG] mrp_package_propagation: Migration to 18.0
  mrp_package_propagation/README.rst
  mrp_package_propagation/__init__.py
  mrp_package_propagation/__manifest__.py
  mrp_package_propagation/i18n/es.po
  mrp_package_propagation/i18n/it.po
  mrp_package_propagation/i18n/mrp_package_propagation.pot
  mrp_package_propagation/models/__init__.py
  mrp_package_propagation/models/mrp_bom.py
  mrp_package_propagation/models/mrp_bom_line.py
  mrp_package_propagation/models/mrp_production.py
  mrp_package_propagation/models/stock_move.py
  mrp_package_propagation/pyproject.toml
  mrp_package_propagation/readme/CONTRIBUTORS.md
  mrp_package_propagation/readme/DESCRIPTION.md
  mrp_package_propagation/readme/USAGE.md
  mrp_package_propagation/static/description/icon.png
  mrp_package_propagation/static/description/index.html
  mrp_package_propagation/tests/__init__.py
  mrp_package_propagation/tests/common.py
  mrp_package_propagation/tests/test_mrp_bom.py
  mrp_package_propagation/tests/test_mrp_production.py
  mrp_package_propagation/views/mrp_bom.xml
  mrp_package_propagation/views/mrp_production.xml
Labels: approved, ready to merge, bot is merging ⏳

#1476 [17.0][FIX] quality_control_oca: In product category form view, fix quality control tree.
  quality_control_oca/views/product_category_view.xml
Labels: approved, bot is merging ⏳

#1485 [17.0][MIG] mrp_bom_hierarchy
  mrp_bom_hierarchy/README.rst
  mrp_bom_hierarchy/__init__.py
  mrp_bom_hierarchy/__manifest__.py
  mrp_bom_hierarchy/i18n/es.po
  mrp_bom_hierarchy/i18n/fr.po
  mrp_bom_hierarchy/i18n/it.po
  mrp_bom_hierarchy/i18n/mrp_bom_hierarchy.pot
  mrp_bom_hierarchy/model/__init__.py
  mrp_bom_hierarchy/model/mrp_bom.py
  mrp_bom_hierarchy/model/mrp_bom_line.py
  mrp_bom_hierarchy/pyproject.toml
  mrp_bom_hierarchy/readme/CONTRIBUTORS.md
  mrp_bom_hierarchy/readme/DESCRIPTION.md
  mrp_bom_hierarchy/readme/USAGE.md
  mrp_bom_hierarchy/static/description/icon.png
  mrp_bom_hierarchy/static/description/index.html
  mrp_bom_hierarchy/view/mrp_bom.xml
Labels: approved, bot is merging ⏳

#1455 [17.0][MIG] mrp_component_operation
  mrp_component_operation/README.rst
  mrp_component_operation/__init__.py
  mrp_component_operation/__manifest__.py
  mrp_component_operation/i18n/es.po
  mrp_component_operation/i18n/it.po
  mrp_component_operation/i18n/mrp_component_operation.pot
  mrp_component_operation/migrations/17.0.1.0.0/pre-migration.py
  mrp_component_operation/models/__init__.py
  mrp_component_operation/models/mrp_component_operation.py
  mrp_component_operation/models/mrp_production.py
  mrp_component_operation/models/stock_route.py
  mrp_component_operation/pyproject.toml
  mrp_component_operation/readme/CONTRIBUTORS.md
  mrp_component_operation/readme/DESCRIPTION.md
  mrp_component_operation/readme/USAGE.md
  mrp_component_operation/security/ir.model.access.csv
  mrp_component_operation/static/description/icon.png
  mrp_component_operation/static/description/index.html
  mrp_component_operation/tests/__init__.py
  mrp_component_operation/tests/test_component_operate.py
  mrp_component_operation/views/mrp_component_operation_views.xml
  mrp_component_operation/views/mrp_production_views.xml
  mrp_component_operation/views/stock_view.xml
  mrp_component_operation/wizards/__init__.py
  mrp_component_operation/wizards/mrp_component_operate.py
  mrp_component_operation/wizards/mrp_component_operate_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳

#1456 [17.0][MIG] mrp_component_operation_scrap_reason
  mrp_component_operation_scrap_reason/README.rst
  mrp_component_operation_scrap_reason/__init__.py
  mrp_component_operation_scrap_reason/__manifest__.py
  mrp_component_operation_scrap_reason/i18n/es.po
  mrp_component_operation_scrap_reason/i18n/it.po
  mrp_component_operation_scrap_reason/i18n/mrp_component_operation_scrap_reason.pot
  mrp_component_operation_scrap_reason/pyproject.toml
  mrp_component_operation_scrap_reason/readme/CONTRIBUTORS.md
  mrp_component_operation_scrap_reason/readme/DESCRIPTION.md
  mrp_component_operation_scrap_reason/static/description/icon.png
  mrp_component_operation_scrap_reason/static/description/index.html
  mrp_component_operation_scrap_reason/wizards/__init__.py
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate.py
  mrp_component_operation_scrap_reason/wizards/mrp_component_operate_wizard.xml
Labels: approved

#1480 [14.0] [FIX] mrp_bom_attribute_match_semifinished_product: use correct uom in bom line
  mrp_bom_attribute_match_semifinished_product/README.rst
  mrp_bom_attribute_match_semifinished_product/__manifest__.py
  mrp_bom_attribute_match_semifinished_product/static/description/index.html
  mrp_bom_attribute_match_semifinished_product/wizard/finished_product_structure_wizard.py
Labels: approved, ready to merge, bot is merging ⏳
