Repository OCA/manufacture, pull requests merged in 2025-08, with the labels that each got.

#1574 [18.0][MIG] mrp_attachment_mgmt
  mrp_attachment_mgmt/README.rst
  mrp_attachment_mgmt/__init__.py
  mrp_attachment_mgmt/__manifest__.py
  mrp_attachment_mgmt/i18n/es.po
  mrp_attachment_mgmt/i18n/hr.po
  mrp_attachment_mgmt/i18n/it.po
  mrp_attachment_mgmt/i18n/mrp_attachment_mgmt.pot
  mrp_attachment_mgmt/models/__init__.py
  mrp_attachment_mgmt/models/mrp_bom.py
  mrp_attachment_mgmt/models/mrp_production.py
  mrp_attachment_mgmt/models/mrp_workorder.py
  mrp_attachment_mgmt/models/product.py
  mrp_attachment_mgmt/pyproject.toml
  mrp_attachment_mgmt/readme/CONFIGURE.md
  mrp_attachment_mgmt/readme/CONTRIBUTORS.md
  mrp_attachment_mgmt/readme/DESCRIPTION.md
  mrp_attachment_mgmt/readme/USAGE.md
  mrp_attachment_mgmt/static/description/icon.png
  mrp_attachment_mgmt/static/description/index.html
  mrp_attachment_mgmt/tests/__init__.py
  mrp_attachment_mgmt/tests/common.py
  mrp_attachment_mgmt/tests/test_mrp_attachment_mgmt.py
  mrp_attachment_mgmt/views/mrp_bom_view.xml
  mrp_attachment_mgmt/views/mrp_production_views.xml
  mrp_attachment_mgmt/views/product_views.xml
  mrp_attachment_mgmt/views/workorder_attachments_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1578 [15.0][ADD] mrp_production_location_picking_type
  mrp_production_location_picking_type/README.rst
  mrp_production_location_picking_type/__init__.py
  mrp_production_location_picking_type/__manifest__.py
  mrp_production_location_picking_type/models/__init__.py
  mrp_production_location_picking_type/models/mrp_production.py
  mrp_production_location_picking_type/models/stock_picking_type.py
  mrp_production_location_picking_type/readme/CONTRIBUTORS.rst
  mrp_production_location_picking_type/readme/DESCRIPTION.rst
  mrp_production_location_picking_type/readme/USAGE.rst
  mrp_production_location_picking_type/static/description/index.html
  mrp_production_location_picking_type/tests/__init__.py
  mrp_production_location_picking_type/tests/test_mrp_production_location_picking_type.py
  mrp_production_location_picking_type/views/stock_picking_type_views.xml
  setup/mrp_production_location_picking_type/odoo/addons/mrp_production_location_picking_type
  setup/mrp_production_location_picking_type/setup.py
Labels: approved, bot is merging ⏳

#1586 [16.0][IMP] mrp_workorder_last_worker: make field storable
  mrp_workorder_last_worker/models/mrp_workorder.py
Labels: approved, bot is merging ⏳

#1591 [16.0][IMP] mrp_multi_level: add RfQ quantity and button to check RfQs
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: approved, bot is merging ⏳

#1595 [18.0][IMP] mrp_multi_level: add RfQ quantity and button to check RfQs
  mrp_multi_level/models/mrp_inventory.py
  mrp_multi_level/tests/test_mrp_multi_level.py
  mrp_multi_level/views/mrp_inventory_views.xml
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: bot is merging ⏳
